### ISSUE TITLE
back space breaks

### ISSUE THREAD

**Issue by spaceTruckerTucker** [python-cmd2/cmd2#1009]
I am having an issue with cmd2 where I loose the back space after any command is executed, this follows over to the terminal once the script has been exited. I have minimized the code where this issue occurs and attached it for review with a screen shot of the issue. If anyone has any insight into this please let me know as I would really like to to fix it. 

Platforms tested: Kali 2019, kali 2020.3, Mac OSX 
Python version: 3.8.5

```
import cmd2
import sys

class ToolShell(cmd2.Cmd):

     prompt = "MIN$ "
     doc_header = "Here are the currently available commands:\nType help [COMMAND] for more info"
     undoc_header = "These commands currently have no associated documentation:"

     def __init__(self):
         cmd2.Cmd.__init__(self)

     def do_testFunction(self, args):
         "This is a test function"
         print("[*]test!")

if __name__ == '__main__':

    sys.exit(ToolShell().cmdloop())
```

<img width="696" alt="Screen Shot 2020-10-11 at 12 37 51 PM" src="https://user-images.githubusercontent.com/35788232/95684334-ecd4e880-0bbe-11eb-957b-bcf62a49a52a.png">

**Comment by kmvanbrunt** [comment]
I ran into this issue as well a few months ago. I'm assuming your default terminal is set to QTerminal. On Linux and Mac, cmd2 runs `stty sane` after each command. For some reason, this puts QTerminal into the state you are seeing. Try running `stty sane` in bash you'll see the same behavior. The solution is to switch to a different terminal.

`sudo update-alternatives --config x-terminal-emulator` will show your default terminal and allow you to change to another terminal program installed on your system. I think the machine I was running then already had MATE Terminal installed so I chose that. But feel free to choose whatever you want except QTerminal.

**Comment by spaceTruckerTucker** [comment]
Hey, thanks for the information really appreciate it but unfortunately it still did not fix the issue after changing to MATE.

**Comment by kmvanbrunt** [comment]
Did you open a new terminal after changing the default? When you select `Help -> About` in the terminal, does it show it's running MATE?

**Comment by spaceTruckerTucker** [comment]
Yeah even did and init 6 to kick it over but now that I actually went back and checked it. Even tho MATE is selected it's still using QTerminal, so I just had to manually force it to switch over and that fixed the issue. Thank you for all the help.

**Comment by kmvanbrunt** [comment]
I'm happy you got it working.

**Comment by spaceTruckerTucker** [comment]
Thank you very much for the help
