### ISSUE TITLE
TypeError on tab-completion on Windows

### ISSUE THREAD

**Issue by EpicWink** [python-cmd2/cmd2#1013]
When using tab-completion on Windows (ie using `pyreadline`), I get a TypeError.

```python
  File "venv\lib\site-packages\pyreadline\modes\basemode.py", line 267, in complete
    self._display_completions(completions)
  File "venv\lib\site-packages\cmd2\cmd2.py", line 1593, in _display_matches_pyreadline
    readline.rl.mode.console.write(sys.stdout.write(self._build_completion_metadata_string()))
  File "venv\lib\site-packages\pyreadline\console\console.py", line 403, in write
    return self.write_color(text)
  File "venv\lib\site-packages\pyreadline\console\console.py", line 365, in write_color
    n, res= self.ansiwriter.write_color(text, attr)
  File "venv\lib\site-packages\pyreadline\console\ansi.py", line 83, in write_color
    chunks = terminal_escape.split(text)
```

This is due to the line (in the commit that introduced it): https://github.com/python-cmd2/cmd2/blob/e6a9a1c972e5e6195278966c6b134a2f450465e1/cmd2/cmd2.py#L1578

The metadata is being written to stdout, then the return value of that write (the number of characters written, an integer) is passed to `readline.rl.mode.console.write` which is expecting a string. The solution is to change this line to

```python
readline.rl.mode.console.write(self._build_completion_metadata_string())
```

**Comment by tleonhardt** [comment]
@EpicWink Thanks for reporting this!  We'll take a look at replicating and fixing it shortly.

@kmvanbrunt This sounds up your alley ...

**Comment by kmvanbrunt** [comment]
Oops, that was a bad copy/paste error on my part. Pull request is up to fix it.

**Comment by tleonhardt** [comment]
@EpicWink The 1.4.0 release has been published to PyPI which has a fix for this bug.
