### ISSUE TITLE
Incorrect detection of default editor in ubuntu:bionic docker container

### ISSUE THREAD

**Issue by gmmephisto** [python-cmd2/cmd2#1017]
Hi! I found a corner case in the default editor detection where neither `EDITOR` variable set nor any editor installed in the system. The excellent environment to reproduce this case is `ubuntu:bionic` docker container.

Steps to reproduce:
* `$ docker run -ti --rm ubuntu:bionic`
* `(container) # apt update && apt install python3 python3-pip`
* `(container) # pip3 install cmd2`
* `(container) # python3 -c "import cmd2; print(cmd2.Cmd.DEFAULT_EDITOR)`

Result:
```
root@820b205efe1f:/# python3 -c "import cmd2; print(cmd2.Cmd.DEFAULT_EDITOR)"
atom
```

Expected result:
* Empty value ?
* Raise an EnvironmentError ?

**Comment by tleonhardt** [comment]
This was closed by #1018
