### ISSUE TITLE
Printing to CLI from outside the cmd2 event loop

### ISSUE THREAD

**Issue by SolomonSklash** [python-cmd2/cmd2#1019]
Hello,

I am running Flask asynchronously while using cmd2. Occasionally I want to print a message to the cmd2 CLI from inside a Flask HTTP request handler function. I do this simply using `print('message from Flask')`.

Doing this "overwrites" cmd2, appending the message after the prompt and requiring a carriage return to get the prompt back to normal, like this:

```
C2 > Message from Flask
        <---- cursor lands here, carriage return moves it down and back to normal
C2 >
```

Is there a standard way to print to the cmd2 CLI from "outside" of it? I've tried a few things, like variations on calling `cmd2.Cmd.poutput('Message from Flask)`, but I get errors.

Thanks!

**Comment by kmvanbrunt** [comment]
See the [async_printing.py](https://github.com/python-cmd2/cmd2/blob/master/examples/async_printing.py) example for a demonstration of how to asynchronously print in cmd2.

Also reference the [Prompt - Asynchronous Feedback](https://cmd2.readthedocs.io/en/latest/features/prompt.html#asynchronous-feedback) section of the user manual.

**Comment by SolomonSklash** [comment]
Thanks @kmvanbrunt . I'd read through that example, and it makes sense, assuming you are printing from within cmd2. I've not been able to figure out how to call into an existing cmd2 instance and pass in text to print. None of the examples I've looked though seem to have that use case either. I tend to get a lot of `AttributeError: 'str' object has no attribute 'stdout'` errors when I pass a string to print from Flask.

**Comment by kmvanbrunt** [comment]
Is the flask instance running in the same process as the cmd2 instance?

**Comment by SolomonSklash** [comment]
Scratch that, I just got it working. The example helped, I tweaked the `_generate_alert_str()` function to access a globally shared list of alerts, and it work great now. 

Thanks a ton for your help, and your work on this library!
