### ISSUE TITLE
Change Prompt Color with ansi.Style Rules?

### ISSUE THREAD

**Issue by KyleKing** [python-cmd2/cmd2#1023]
If I set the prompt to some color (i.e. `self.prompt = color('blue> ', fg=fg.green`)

Then run a script and capture the output (`run_script script.txt -t transcript.txt`)

The transcript file will have the color formatting

```txt
[39mblue> [50mCommand Output
...
```

Is there a way to safely set the prompt style? So that the transcript.txt looks like this:

```txt
blue> Command Output
...
```

---

Separate, but related question, is there a way to change the color for the entire STDIN prompt?

---

Let me know if a working example would help

**Comment by tleonhardt** [comment]
@KyleKing If I remember correctly, the Transcript Testing feature ignores any ANSI escape codes that are part of the prompt when doing its comparisons - so the presence of them won't hurt.

You can view the transcript in color by using any program which supports rendering of ANSI codes, such as any of the following:
- `cat`
- `less -r`
- `more`

**Comment by tleonhardt** [comment]
@KyleKing An example would definitely help as would an explanation of what it is you are trying to do and/or what you want to accomplish.

First off are you really intending to use a **Transcript** file?  These are for a built-in regression test framework feature called **Transcript Testing**.  If you just to run a script using `run_script` - you are not generating a script in the correct way.

**Comment by KyleKing** [comment]
Thanks for the reply!

My use case is that I'm working on a school project where we have script/transcript files to compare against (hence the burst of issues since it it due tomorrow and we are just trying to complete the last few things 😄 )

My first approach was to use the `--test` transcript feature, but it seemed to be ignoring other commands passed at initialization (i.e. `python main.py "login -u user -p pass" --test ./transcripts/case-1.txt`). So then I switched to `run_script` with `python main.py "login -u user -p pass" "run_script ./transcripts/case-1-script.txt"` (where I isolated only the STDIN command from the case)

I am already converting the TA-provided commands from comma-separated to space (`shlex.join()`), so I could feasibly just add the `login -u user -p pass` to the top of the file, but I would like to avoid keeping the password in plain text. Right now, I can show an input and only store the password in memory

So essentially, there is probably a better way to use cmd2 for this case. Right now is working, but some of it seems kind of hacky and it would be nice to have the cyan prompt

**Comment by KyleKing** [comment]
Merging the discussion from #1024 and from my comments above. Would it be better to pipe the output of `run_script` rather than using `-t`. I haven't tested this yet, but I saw there were options to use `>` etc. but I'm not sure if they are cross-platform. I'll take a look at: https://cmd2.readthedocs.io/en/latest/features/redirection.html

**Comment by tleonhardt** [comment]
If you need to be able to parse additional arguments when launching your cmd2 application, please see [decorator_example.py](https://github.com/python-cmd2/cmd2/blob/master/examples/decorator_example.py#L91-L112) for one example of how to do that.

**Comment by tleonhardt** [comment]
It isn't clear to me exactly what you want to do and/or what you are struggling with, but I'm 95% sure you don't want to be using the **Transcript Testing** feature.  So yeah you probably shouldn't be using `-t`.

All features of `cmd2` are cross-platform and work on Windows, macOS, and Linux unless explicitly stated otherwise.  Redirection and piping work the same on all OSes.

**Comment by KyleKing** [comment]
We turned in the project last night, so I left the tests cases the way they were. I'm planning on using Cmd2 in other projects at work/personal, so I'll have more control over what test scripts/transcripts look like and will be able to use the transcript testing more appropriately
