### ISSUE TITLE
Escaped slash in transcript?

### ISSUE THREAD

**Issue by KyleKing** [python-cmd2/cmd2#1024]
I ran these commands in my app

```
(sw) run_script ./test_transcripts/slash-script.txt
demo,age_20_heroes,Viewers of Marvel/DC under 20
size,10000
current_period,0
previous_period,174000
total,174000
(sw) run_script ./test_transcripts/slash-script.txt -t slash-transcript.txt
(sw)
```

But the transcript introduces an escaped forward slash that is causing issues in my automated tests (`slash-script.txt`)

```
(sw) login -u a26admin -p a26$treaming
(sw) update_demo age_20_heroes 'Viewers of Marvel/DC under 20' 10000
(sw) display_demo age_20_heroes
demo,age_20_heroes,Viewers of Marvel\/DC under 20
size,10000
current_period,0
previous_period,174000
total,174000
```

Is the escaped forward slash an intended behavior?

**Comment by tleonhardt** [comment]
@KyleKing I'm not sure, but I think you might be confusing two completely separate features.

`cmd2` support executing basic ASCII text scripts of commands as you would enter them normally on the command-line using the `run_script` command.  `cmd2` also supports a built-in regression testing framework we call **Transcript Testing** and it has capabilities for automatically generating transcripts.  These transcript tests can be executed by calling your cmd2 application with the `-t` flag and giving it a path to a transcript file.  Transcript files are **NOT** the same as simple script files!

Irrelevant to this discussion, but something very important you should also be aware of, `cmd2` supports the much more powerful capability of executing Python scripts using the `run_pyscript` command.

**Comment by KyleKing** [comment]
Thanks, I'll go ahead and close this issue and continue the discussion in #1023 since this is more about resolving my use case
