### ISSUE TITLE
pyreadline

### ISSUE THREAD

**Issue by KyleKing** [python-cmd2/cmd2#1025]
I ran into a character encoding issue on Windows installing pyreadline with poetry, but was able to manually install it with pip

In case this would be useful, I found that pyreadline hasn't been updated in 5 years, but there is an active fork, pyreadline3, that should be a drop in replacement. See: https://github.com/brgirgis/pyreadline3

**Comment by tleonhardt** [comment]
@KyleKing We'll have to check out `pyreadline3`.  The REAMDE for it says it works with Python 3.8+ and currently `cmd2` supports Python 3.5+, to move soon to 3.6+ - so that could be a blocker.  But maybe it will actually work with earlier versions of Python.

Can you provide more details about the character encoding issue you ran into?

**Comment by KyleKing** [comment]
I saw the encoding issue while remotely debugging over a screen share and don't have access to Windows, but it should be reproducible with `poetry init; poetry add pyreadline`

That's interesting, the pypi README says 3.3+ in the 3.1-3.3 releases, but not the 3.0 release (3.8+) and the current Github README. Their test action does pass on 3.6-3.9: https://github.com/brgirgis/pyreadline3/blob/master/.github/workflows/python-test.yml#L18. There is no way to post issues to the fork

**Comment by KyleKing** [comment]
I think this was the codec issue we saw (we were using python 3.8.3): https://github.com/pyreadline/pyreadline/pull/63

**Comment by tleonhardt** [comment]
`cmd2` already has a conditional dependency on `pyreadline` in the case that the OS is Windows.  Given that `pyreadline` hasn't been updated in about 5.5 years, I think its safe to say it is abandoned.

I'd say that we may want to implement some slightly more conditional dependency logic where for Windows, if they version of Python is newer then we have a dependency on `pyreadline3` and a dependency on `pyreadline` for older versions of Python.
