### ISSUE TITLE
Question: is there a way to have an alias execute multiple commands?

### ISSUE THREAD

**Issue by legacy-code** [python-cmd2/cmd2#1030]
Just curious if there is a way to do this.  I didn't see anything in the docs, so ...

Let's say I have a couple of commands defined: a and b.  If I want to define an alias to perform both of these command with an alias, how would I do that?

`alias create c a;b` or something like that (this doesn't work, btw, or didn't for me), hence, the question.  Is there a way to do this?

Thanks!

**Comment by tleonhardt** [comment]
Aliases are designed to allow users to customize their environment in a cmd2-based application so they can call a single command in a specific way and give that a name.   I don't believe there is currently a direct way to make an alias execute multiple cmd2 commands.

However, cmd2 supports both text-based scripts via the `run_script` command and Python-based scripts via the `run_pyscript` command.  Creating a script and invoking it via `run_script` may be exactly what you are looking for.

Of course, if you are developing a cmd2-based application, you can add a custom command implemented via a `do_*` method which does whatever you want it to, including executing multiple other commands.

Of course, if you want to get creative, you could create the script file containing your commands and then create an alias to call `run_script <your_script_name>` and perhaps that will achieve what you are looking for in a relatively easy fashion.

**Comment by legacy-code** [comment]
Hmmm.  Something to think about.

I'm using a Cmd2 app for myself, where I wanted to string several commands (defined as do_xx) together -- stop server, build stuff, and then restart server.  All of these commands are defined, but not as *one* command.

You did answer my question though.  Aliases are meant as a one-to-one command, not quite like an alias in, say bash, which can do all sorts of things (both good and bad).  That's fair.  I just wasn't sure if I was missing something or not.

I get that I could create another command to do this, but I already have around 45 of _my commands_ in this one app, so ...  Not terribly anxious to add another, but certainly could.  Was just hoping to avoid the boiler-plate of doing another command.

No worries though and thanks for answering!  Cmd2 is an awesome tool that I really like using and developing for!

**Comment by legacy-code** [comment]
As an idea, maybe I could do another command (i.e. do_multcmd or something like that) which would take the passed in string (could be looked up or passed in) and then it would split it and then call the cmd2.onecmd() for each.  Currently, the commands that I would want to run don't have any parameters, so that makes it easier.

That might solve it for me and add something I might use.  Will have to think about it.

Is there any issue(s) with doing something along those lines?

**Comment by legacy-code** [comment]
Looking at the command scripts, you are right.  This might be something that would probably do exactly what I need.  I haven't used them yet, so had to look it up to see what it does.  It looks like exactly what I'm wanting to do in this instance.

I'll have to give it a go and see how it works out!

Thanks!  Really appreciate it!

**Comment by tleonhardt** [comment]
@legacy-code Yeah I think that can work for you.  I would encourage to look at potentially using the [runcmds_plus_hooks](https://github.com/python-cmd2/cmd2/blob/master/cmd2/cmd2.py#L2132-L2158) method which lies at the core of the implementation for the `run_script` command.  It should do 80% of what you are looking for and you just need to add some split logic outside of it in your command.

**Comment by legacy-code** [comment]
@tleonhardt Thanks so much.  This has given me some additional thought on what to add to my app.

Currently, the `run_script` handles what I need.  The only down side is it needs to create a file to execute from, and that's not bad at all, just sort of inconvenient at worst.  

Thanks for the thoughts on using `runcmds_plus_hooks` - I might give that a go as well.  It all depends on how much time I have and how much I need it to work!  😃 

I think this issue can be closed.  Thanks again for the input and ideas.

**Comment by tleonhardt** [comment]
@legacy-code Good luck with your project.  Glad you are enjoying cmd2.  I'll close this now.
