### ISSUE TITLE
non ascii character written to stdout after command finished

### ISSUE THREAD

**Issue by aenima-x** [python-cmd2/cmd2#1031]
when I run a command from command line using "onecmd_plus_hooks" I get a nons ascii character written to stdout.
If the command is executed in the interactive mode it all fine.

The most strange thing is that if i put a print after the line ```app.onecmd_plus_hooks(command_string)```
the character is written after the print.
And that is the last line in the script

**Comment by tleonhardt** [comment]
@aenima-x Could you possibly provide a small code example to help us reproduce this issue?  Also, what OS, version of Python, terminal, and shell are you using?

**Comment by tleonhardt** [comment]
On an unrelated note, you should almost never use a `print` within a cmd2 application.  We have a slew of output methods within the `cmd2.Cmd` class which your application should inherit from such as:
- [poutput](https://cmd2.readthedocs.io/en/latest/api/cmd.html?highlight=poutput#cmd2.Cmd.poutput)
- [perror](https://cmd2.readthedocs.io/en/latest/api/cmd.html?highlight=perror#cmd2.Cmd.perror)
- etc.

See the [Generating Output](https://cmd2.readthedocs.io/en/latest/features/generating_output.html) section of the docs for more info.

**Comment by aenima-x** [comment]
Yes the print was just a test.
I use poutput. 
I will provide the info, I will try in a different OS first

**Comment by aenima-x** [comment]
Forget it, I was doing something un postcmd()

thanx
