### ISSUE TITLE
Add search path functionality for run_script and run_py_script commands

### ISSUE THREAD

**Issue by jayrod** [python-cmd2/cmd2#1040]
It would be helpful if it were possible to add a search path for the run script and py run script commands. This would allow an application to specify a central place to hold scripts. 

As an added bonus it would be great if the scripts were auto-completed as well.

**Comment by tleonhardt** [comment]
@jayrod The `run_script` and `run_pyscript` commands both already use filesystem path completion, so they should tab-complete file names on your path.  Its currently all relative to your current working directory.

**Comment by kmvanbrunt** [comment]
A change like this would require at least 2 things.

1. Edit `path_complete()` to accept a search_dir where any search strings which have no path characters (e.g. dots and slashes) will search from this directory. Similar to how we do shell command completion in that we search through the user's path.

2. Edit run_script and run_pyscript to prepend this script_dir to any files passed to it that have no directory.

@tleonhardt and I don't think these changes are necessary in the cmd2 framework, but you are welcome to customize your application.
