### ISSUE TITLE
2.0 Discussion

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#1044]
@anselor @tleonhardt 
I'd like to move toward getting cmd2 2.0 released. What needs to get done before we do?

My list

- ~~#1042 (Support formatted tab-completion output) (This will only be done on 2.0 branch)~~

**Comment by anselor** [comment]
Not exciting work, but updating the examples to be up to date with our latest improvements is probably a good thing to do. #1000 

Also, #1010 suppressing output of startup scripts.

passing both flake8 and mypy with type annotations throughout would be nice too.

#965 per-CommandSet settables

**Comment by kmvanbrunt** [comment]
We also need to remove the `with_argparser_and_unknown_args` decorator on the 2.0 branch since it was deprecated.

**Comment by kmvanbrunt** [comment]
#1010 has a PR out for it now

**Comment by tleonhardt** [comment]
The things I think are most important are:
- #874  - Travis CI is insanely slow and makes working on this project not fun right now, need to replace with GitHub Actions or fix Travis
- #930  - flake8 runs as part of our build - black, isort, and maybe doc8 should also run as part of the build
- #938 - We need to drop support for Python 3.5 so we can finally start to use f-strings and other good Python 3.6 features

The first two are really infrastructure changes, but important ones.  The last one is a breaking change that should be done as part of the 2.0 release.

**Comment by jayrod** [comment]
On the user end of things, the most awesome thing about cmd2 is how it allows you to rapidly build a feature rich application with minimal effort. The simple app is well, simple and if you look at the larger applications they are exceedingly complex. 

It is difficult for those of us that are advanced but unable to really grok some of the complexities of cmd2.

I.e. you have a plugin example project but its not very effective of guiding you through the framework.

I propose we distill best practices into cookiecutter templates focusing on creating  deliverable cmd2 applications.

**Comment by anselor** [comment]
@jayrod Take a look at #1000 

I was trying to go through and annotate the purpose of each example we have. Probably worthwhile to discuss what examples are missing. 

For some if the more complicated features it'll probably actually make more sense to develop a stand-alone app to demonstrate what it does.

**Comment by anselor** [comment]
PR #1074 Is out and related to this.

**Comment by anselor** [comment]
I think we should try to fully adopt pathlib in our APIs before the 2.0 switch as well. 

What do you think, @tleonhardt @kmvanbrunt

**Comment by tleonhardt** [comment]
I’m a huge fan of both pathlib and f-strings.  But I’m also a fan of not fixing what isn’t broke.  So I could go either way.

**Comment by anselor** [comment]
My specific concern is I'd like to get everything API breaking in together in 2.0 release if possible. So if there are places on our APIs that would benefit from pathlib I'd rather take the hit now than later.

**Comment by kmvanbrunt** [comment]
@tleonhardt @anselor 
`f-string` conversion was completed in #1092.
`pathlib` support can be added later by converting applicable argument types to `Union[str, pathlib.Path]`.

If this approach is acceptable, are we good for releasing 2.0 soon?

**Comment by tleonhardt** [comment]
I think now is a fine time for the 2.0 release and we should get it out very soon to help avoid further customer confusion with examples not working with the latest version of `cmd2` installed from `pip`.

**Comment by kmvanbrunt** [comment]
Closing since 2.0.0 is out
