### ISSUE TITLE
Refactor out boilerplate methods

### ISSUE THREAD

**Issue by catherinedevlin** [python-cmd2/cmd2#105]
We'd like to get "boilerplate" methods, which writers of cmd2-based apps don't need to see or touch, moved off into separate objects.  Then the Cmd app can be instantiated with links to objects containing those infrastructure methods.

I've made a preliminary map of themes to break out Cmd2 methods into.

```

Completion               def _shell_command_complete(search_text):  
Completion               def complete_shell(self, text, line, begidx, endidx):  
Completion               def path_complete(self, text, line, begidx, endidx, dir_
History                  def last_matching(self, arg):  
Input                    def _surround_ansi_escapes(prompt, start="\x01", end="\x
Input                    def do_load(self, file_path=None):  # guts only 
Input                    def pseudo_raw_input(self, prompt):  
Input                    def read_file_or_url(self, fname):  
Lifecycle                def _cmdloop(self):  
Lifecycle                def complete_statement(self, line):  
Lifecycle                def onecmd_plus_hooks(self, line):  
Lifecycle                def postparsing_postcmd(self, stop):  
Lifecycle                def postparsing_precmd(self, statement):  
Meta                     def func_named(self, arg):  
Output                   def colorize(self, val, color):  
Output                   def perror(self, errmsg, exception_type=None, traceback_
Output                   def pfeedback(self, msg):  
Output                   def poutput(self, msg):  
Output                   def redirect_output(self, statement):  
Output                   def restore_output(self, statement):  
Parser                   def _init_parser(self):  
Parser                   def parsed(self, raw):  
Parser                   def parseline(self, line):  
Parser                   def postparse(self, parse_result):  
Parser                   def preparse(self, raw):  
Subcommands              def select(self, opts, prompt='Your choice? '):  
Testing                  def run_transcript_tests(self, callargs):  
```

**Comment by tleonhardt** [comment]
Thanks for documenting this!  As we discussed, some of this will likely require refactoring the runtime settings into their own shareable object so that other objects that need access to runtime settings can all get to them.

**Comment by SpotlightKid** [comment]
Aren't many of these methods (e.g. `preparse` and `postparse`) explicitly there to be overwritten and empty by default? What's the benefit of moving them out of the `Cmd` class then?

**Comment by tleonhardt** [comment]
@SpotlightKid 
The general point of this issue was to move some things related to internal implementation details which should not be publicly accessible to end users out of the cmd2.Cmd class.

This was largely accomplished by the creation of the ``ParserManager`` class which encapsulates most of the **pyparsing** parsing logic.
 
@catherinedevlin I'm going to close this issue.  I think your previous PR took care of the most import aspects of this issue.  Please feel free to re-open if you wish to work on it further.
