### ISSUE TITLE
Sphinx-doc integration question

### ISSUE THREAD

**Issue by jayrod** [python-cmd2/cmd2#1056]
I've been playing with getting sphinx to autodocumenteng cmd2 apps.. It's a bit klugy. I was wondering if anyone had done this as well and if there was a way to best represent the help commands in formal documentation?

**Comment by tleonhardt** [comment]
@jayrod What audience are you trying to generate the documentation for?  Developers of the cmd2 application?  End users of the application who are not developers?

For developers I think Sphinx works great and is pretty straightforward.

For end users, I don't think Sphinx works so well.  I have documented cmd2-based applications using Sphinx, but it involved a lot of cut-and-paste from help menus of the actual application at runtime.

I know @kmvanbrunt has a pyscript for dumping complete help to a text file in our examples which you might find useful: https://github.com/python-cmd2/cmd2/blob/master/examples/scripts/save_help_text.py

**Comment by jayrod** [comment]
I was thinking of turning that help text into a sphinx extension for end users.

**Comment by jayrod** [comment]
After a day of traveling down the Sphinx extension rabbit hole, I'm going to avoid this topic and never speak of it again.. Hopefully.
