### ISSUE TITLE
History repeats index numbers

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#1064]
Once a history file reaches the max limit of items, cmd2 truncates it before closing. When you reopen cmd2, the history file is read and all `HistoryItems` are restored with their previous index numbers. Then `cmd2.History` sets the starting index based on the length of the list, which could be an index already used by a restored `HistoryItem`.

I propose removing the index from `HistoryItem` and instead use its actual index in the `History` list (converted to 1-based as it has been).

**Comment by tleonhardt** [comment]
I like your proposed solution.
