### ISSUE TITLE
global variable is not returning values assigned inside choice=function(globalvariable) . 

### ISSUE THREAD

**Issue by AdityaRajaram** [python-cmd2/cmd2#1071]
Tab completion option working locally but when I ran on remotely it is not working. I saw some gnureadline installation . Can you please tell me how to make completion to work remotely?

**Comment by kmvanbrunt** [comment]
@AdityaRajaram Can you provide more details on how you are accessing your application remotely?
I have used ssh and telnet to run my application, and tab completion works in both.

**Comment by AdityaRajaram** [comment]
x=None
def class(Cmd2.Cmd):
          //init
      @with_argparser(some_parser)
      def hi(self,args):
            global x
            x= args.x
            obj = class2(x)
            obj.cmdloop()
 If I use global variable inside choice=some_funtion(x) in argparse returns None. But it works inside method. how can I use it global variable  inside choice of argparse.add_argument() . I don’t  want to use it as self.x

**Comment by AdityaRajaram** [comment]
x```
=None

def class(Cmd2.Cmd):
          //init
      @with_argparser(some_parser)
      def hi(self,args):
            global x
            x= args.x
            obj = class2(x)
            obj.cmdloop()
```
If I use global variable inside choice=some_funtion(x) in argparse returns None. But it works inside method. how can I use it global variable inside choice of argparse.add_argument() . I don’t want to use it as self.x
