### ISSUE TITLE
Change linked version of document

### ISSUE THREAD

**Issue by anselor** [python-cmd2/cmd2#1075]
I think always linking to latest from master is causing confusion. 

A couple ways to go: 

1) do development on a dev/unstable branch and only update master with each release
2) Change the documentation link to always link to latest stable. instead of latest master.

**Comment by tleonhardt** [comment]
I think the better approach is changing the documentation to by default point to the latest stable.

**Comment by kmvanbrunt** [comment]
I already changed the **About** section of our github page to link to 1.5.0 docs.
But Todd is right. Our documentation is linking to the latest docs.

**Comment by tleonhardt** [comment]
I changed the `Advanced Settings` for our project on readthedocs.org and the `Default version` is now the `stable` one.
