### ISSUE TITLE
_register_subcommands() breaks when methods have been mocked

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#1077]
Steps to reproduce:

1. Create a file `test_patch.py` in `cmd2/tests` with the following contents:
```
import cmd2

def test_patch(mocker):
    mock_cmdloop = mocker.patch("cmd2.Cmd.cmdloop")
    ta = cmd2.Cmd()
    ta.cmdloop()
    assert mock_cmdloop.call_count == 1
```

2. run `pytest tests/test_patch.py`

Expected result: a successfully passed unit test

Actual result: `CommandSetRegistrationError` exception thrown from `_register_subcommands()`

**Comment by kotfu** [comment]
You can demonstrate that `_register_subcommands()` is the problem with the following test:
```
def test_isolate(mocker):
    mock_cmdloop = mocker.patch("cmd2.Cmd.cmdloop")
    mock_register = mocker.patch("cmd2.Cmd._register_subcommands")
    ta = cmd2.Cmd()
    ta.cmdloop()
    assert mock_cmdloop.call_count == 1
```
which causes `_register_subcommands()` to not be called. This test passes.

**Comment by kmvanbrunt** [comment]
@kotfu Because mocked objects create attributes on demand, all calls to `hasattr()` in `_register_subcommands()` are returning `True` . That is causing the mocked `cmdloop` to get flagged as a subcommand method.

Add this line to your unit test and it will work.
`delattr(mock_cmdloop, cmd2.constants.SUBCMD_ATTR_NAME)`

**Comment by kotfu** [comment]
I tried your suggestion as an alternative workaround to the mocking `_register_subcommands()` I already found. It didn't work.

Here's the error from pytest:
```        # iterate through all matching methods
        for method_name, method in methods:
            subcommand_name: str = getattr(method, constants.SUBCMD_ATTR_NAME)
            full_command_name: str = getattr(method, constants.SUBCMD_ATTR_COMMAND)
            subcmd_parser = getattr(method, constants.CMD_ATTR_ARGPARSER)

            subcommand_valid, errmsg = self.statement_parser.is_valid_command(subcommand_name, is_subcommand=True)
            if not subcommand_valid:
>               raise CommandSetRegistrationError('Subcommand {} is not valid: {}'.format(str(subcommand_name), errmsg))
E               cmd2.exceptions.CommandSetRegistrationError: Subcommand <MagicMock name='cmdloop.subcommand_name' id='4506146416'> is not valid: must be a string. Received <class 'unittest.mock.MagicMock'> instead

cmd2/cmd2.py:792: CommandSetRegistrationError
```

I think I know why. Here's a relevant snipped from a debug session:
```
ipdb> method
<MagicMock name='cmdloop' id='4554917968'>
ipdb> dir(method)
['__enter__', 'argparser', 'assert_any_call', 'assert_called', 'assert_called_once', 'assert_called_once_with', 'assert_called_with', 'assert_has_calls', 'assert_not_called', 'attach_mock', 'call_args', 'call_args_list', 'call_count', 'called', 'configure_mock', 'method_calls', 'mock_add_spec', 'mock_calls', 'parent_command', 'reset_mock', 'return_value', 'side_effect', 'subcommand_name']
ipdb> hasattr(method,'fredflintstone')
True
ipdb> dir(method)
['__enter__', 'argparser', 'assert_any_call', 'assert_called', 'assert_called_once', 'assert_called_once_with', 'assert_called_with', 'assert_has_calls', 'assert_not_called', 'attach_mock', 'call_args', 'call_args_list', 'call_count', 'called', 'configure_mock', 'fredflintstone', 'method_calls', 'mock_add_spec', 'mock_calls', 'parent_command', 'reset_mock', 'return_value', 'side_effect', 'subcommand_name']
ipdb> isinstance(method.parent_command, str)
False
ipdb> method.parent_command
<MagicMock name='cmdloop.parent_command' id='4559230768'>
ipdb>
```

It appears that `hasattr()` on a MagicMock has the side effect of creating the attribute if it doesn't exist (and making the attribute be an instance of MagicMock so accesses to that attribute can be intercepted), and always returning true. When `_register_subcommands()` checks for methods with attributes that would indicate they are a subcommand, it will always return true. There is no way to inject code into the middle of that method to remove the attributes before the exception is thrown.

**Comment by kmvanbrunt** [comment]
Look again at my post. It is calling `delattr()` on the mock object.
`delattr(mock_cmdloop, cmd2.constants.SUBCMD_ATTR_NAME)`

That's how you get `hasattr()` to return `False` for a given attribute on mock objects. See the [Python docs](https://docs.python.org/3/library/unittest.mock.html#deleting-attributes) for a full explanation.

This pytest works for me.

```Python
import cmd2

def test_patch(mocker):
    mock_cmdloop = mocker.patch("cmd2.Cmd.cmdloop")

    # Force hasattr to return False for this attribute
    delattr(mock_cmdloop, cmd2.constants.SUBCMD_ATTR_NAME)

    ta = cmd2.Cmd()
    ta.cmdloop()
    assert mock_cmdloop.call_count == 1
```

**Comment by kmvanbrunt** [comment]
You have to call `delattr()` on the mock object.
`delattr(mock_cmdloop, cmd2.constants.SUBCMD_ATTR_NAME)`

That's how you get `hasattr()` to return `False` for a given attribute on mock objects. See the [Python docs](https://docs.python.org/3/library/unittest.mock.html#deleting-attributes) for a full explanation.

This pytest works for me.

```Python
import cmd2

def test_patch(mocker):
    mock_cmdloop = mocker.patch("cmd2.Cmd.cmdloop")

    # Force hasattr to return False for this attribute
    delattr(mock_cmdloop, cmd2.constants.SUBCMD_ATTR_NAME)

    ta = cmd2.Cmd()
    ta.cmdloop()
    assert mock_cmdloop.call_count == 1
```

**Comment by kotfu** [comment]
I tried your suggestion as an alternative workaround to mocking `_register_subcommands()` that I already found. It didn't work.

Here's the error from pytest:
```        # iterate through all matching methods
        for method_name, method in methods:
            subcommand_name: str = getattr(method, constants.SUBCMD_ATTR_NAME)
            full_command_name: str = getattr(method, constants.SUBCMD_ATTR_COMMAND)
            subcmd_parser = getattr(method, constants.CMD_ATTR_ARGPARSER)

            subcommand_valid, errmsg = self.statement_parser.is_valid_command(subcommand_name, is_subcommand=True)
            if not subcommand_valid:
>               raise CommandSetRegistrationError('Subcommand {} is not valid: {}'.format(str(subcommand_name), errmsg))
E               cmd2.exceptions.CommandSetRegistrationError: Subcommand <MagicMock name='cmdloop.subcommand_name' id='4506146416'> is not valid: must be a string. Received <class 'unittest.mock.MagicMock'> instead

cmd2/cmd2.py:792: CommandSetRegistrationError
```
There is no way to inject code into the middle of `_register_subcommands()` to remove the subcommand attributes on the mock after they are created, but before the exception is thrown.

I don't use subcommands, so this doesn't really matter to me. It's unfortunate that the workaround for me to mock a public method on `cmd2.Cmd` is to also mock a private or it throws exceptions. It's pretty brittle.

But the real problem with the current implementation of subcommands is that you can't test them using mocks on `cmd2.Cmd`, because the only workaround I see to this problem requires you to skip registration of subcommands.

I don't know the subcommand code at all, so I'm reluctant to propose a fix, but is it possible to modify this code:
```
        for method_name, method in methods:
            if method_name == 'cmdloop':
                import ipdb; ipdb.set_trace()
            subcommand_name: str = getattr(method, constants.SUBCMD_ATTR_NAME)
            full_command_name: str = getattr(method, constants.SUBCMD_ATTR_COMMAND)
            subcmd_parser = getattr(method, constants.CMD_ATTR_ARGPARSER)
```

so that instead of having type hints for `str` (which don't actually do anything at runtime) it checks if the attrs are strings and if not, silently skips the method without registering it as a subcommand (instead of raising an exception that it's not a valid command)?

**Comment by kotfu** [comment]
Oops, didn't realize I submitted the same comment twice. sorry about that 😞 .

**Comment by kotfu** [comment]
So there are two ways to work around this problem:
```
 mock_cmdloop = mocker.patch("cmd2.Cmd.cmdloop")
 # Force hasattr to return False for this attribute
 delattr(mock_cmdloop, cmd2.constants.SUBCMD_ATTR_NAME)
```
and
```
mock_cmdloop = mocker.patch("cmd2.Cmd.cmdloop")
mock_register = mocker.patch("cmd2.Cmd._register_subcommands")
```
The first one posted by @kmvanbrunt has the benefit of allowing the mock to work if you are using subcommands, and is therefore preferable.

It's unfortunate that mocking any method on `cmd2.Cmd` requires an additional magic incantation to have it not throw exceptions.

I don't know the subcommand code at all, so I'm reluctant to propose a fix, but is it possible to modify this code:
```
        for method_name, method in methods:
            subcommand_name: str = getattr(method, constants.SUBCMD_ATTR_NAME)
            full_command_name: str = getattr(method, constants.SUBCMD_ATTR_COMMAND)
            subcmd_parser = getattr(method, constants.CMD_ATTR_ARGPARSER)
```

so that instead of having type hints for `str` (which don't actually do anything at runtime) it checks if the attrs are strings and if not, silently skips the method without registering it as a subcommand (instead of raising an exception that it's not a valid command)?

**Comment by kmvanbrunt** [comment]
@anselor, since you're the expert on this method, what are your thoughts on the fix proposed by @kotfu?

Not having to include a mock-specific check in your logic is nice and it makes it easier for unit tests to mock cmd2 methods.

**Comment by anselor** [comment]
The line calling `self.statement_parser.is_valid_command(subcommand_name, is_subcommand=True)` is actually doing a check to verify that `subcommand_name` is a string. That's why `subcommand_valid` is false and the exception gets thrown. If you look in the original error message that's exactly what the exception is complaining about: `cmd2.exceptions.CommandSetRegistrationError: Subcommand <MagicMock name='cmdloop.subcommand_name' id='4506146416'> is not valid: must be a string. Received <class 'unittest.mock.MagicMock'> instead`

The point of the check is to have very specific attributes you have to define to be considered a sub-command and then raise an exception if the developer has made a mistake in defining a subcommand. Adding additional checks in front of this to skip this check would result is hiding this class of error.

**Comment by kotfu** [comment]
I agree that it's a good idea to carefully check if subcommands are defined correctly. But if they aren't defined correctly, could an alternative behavior be to just not treat it as a subcommand, ie ignore it, instead of throwing an exception? Especially when, as in my case, I didn't think I was defining a subcommand. Initializing the class (with no commandsets defined) triggered the subcommand processing logic.

**Comment by anselor** [comment]
So I got partway through trying a way to filter out mocks without explicitly filtering out mocks and discovered I added unit tests already specifically dealing with mocks.
 
If you declare the mock with `spec=True`, then MagicMock will use the object being matched as a specifcation rather than automatically reporting it has everything.

```
    mock_cmdloop = mocker.patch("cmd2.Cmd.cmdloop", spec=True)
```

**Comment by anselor** [comment]
See: https://github.com/python-cmd2/cmd2/blob/d05875247c430a1e32a203f9575a93464b5521f1/tests/test_argparse.py#L431

**Comment by kmvanbrunt** [comment]
Apparently we actually documented this. I guess we all forgot :)
https://cmd2.readthedocs.io/en/latest/testing.html#mocking

**Comment by tleonhardt** [comment]
I had some coworkers that ran into the mocking issue and once we finally figured out a solution, I documented it because I knew I would forget ;-)

**Comment by kotfu** [comment]
New pr which adds another example of how to turn autospeccing on, as well as an example of the kind of error message you will see if you forget to turn autospeccing on. I think we can close this issue.
