### ISSUE TITLE
Easy way to integrate use as commandline over socket/telnet?

### ISSUE THREAD

**Issue by FedericoCeratto** [python-cmd2/cmd2#11]
Originally reported by: **Stuart Axon (Bitbucket: [stuaxo](http://bitbucket.org/stuaxo), GitHub: [stuaxo](http://github.com/stuaxo))**

---

I have a homebuild command parser I'm using on my socket server, I'd like to use something like cmd2 instead.

Ideally, all the command history etc would be available - but that seems a bit ambitious .. 

Is there a method I can pass a line of text + then cmd2 call the correct functions + return the feedback ?

That way I could use cmd2 for my ordinary shell and my socket shell.

---
- Bitbucket: https://bitbucket.org/catherinedevlin/cmd2/issue/11

**Comment by tleonhardt** [comment]
Making cmd2 automagically work over a socket in a standard way that would be the same for everyone is far outside the scope of what this module is intended to do. 

For those who want to have commands trigger messages to be sent over a socket, that is readily achievable with the existing infrastructure.  But I don't think it would make sense to try to do it in a completely generic way.
