### ISSUE TITLE
poutput or print string with ansi codes quietly crashes cmd2

### ISSUE THREAD

**Issue by iancote** [python-cmd2/cmd2#1108]
I have a scenario where as string I get back from an api call already has ansi color codes embedded in it (see snippet below).  I'd like to just print that to the screen keeping the existing coloring if possible.  When I try to use poutput or even just print cmd quietly crashes out and I get dropped back to my regular shell.  Using python to print the string from my pycharm python shell window works fine, as does printing it from a simplified script without cmd2 involved.

snippet of the string:
print(repr(a['content']))
'SSH password: \n\nPLAY [Get device facts and configuration] **************************************\n\nTASK [Get committed configuration] *********************************************\n\x1b[1;35m[WARNING]: The value "22" (type int) was converted to "\'22\'" (type string). If\x1b[0m\n\x1b[1;35mthis does not look like what you expect, quote the entire value to ensure it\x1b[0m\n\x1b[1;35mdoes not change.\x1b[0m\n\x1b[0;32mok: [10.66.1.78]\x1b[0m\n\nTASK [Print result] ****'

Here's my script run in a terminal:
(venv) iancote@iancote-XPS-13-7390:~/git/nash$ ./nash.py 
Welcome to UW Network Automation Shell
nash>set debug true
debug - was: False
now: True
nash>login
Password: 
Logged in
nash>list
(venv) iancote@iancote-XPS-13-7390:~/git/nash$

The code is pretty simple:
    def do_list(self, args):
        """ List inventories, groups, or hosts """
        r = self._api_call('jobs/37/stdout/')
        print(r['content'])    <- same behavior with self.poutput()

r is a requests.json() response.

Is there a way to do a "raw" print or something?

Thanks,
-iani

**Comment by kmvanbrunt** [comment]
You don't need to do anything special to print colored text in cmd2. If your console is silently crashing, first check the state of your output streams. Are they closed at the time you are printing?

If just stdout is closed, the following exception will print:
`ValueError: I/O operation on closed file`

If both stdout and stderr are closed, nothing will print.

**Comment by iancote** [comment]
Thank you for the response - this pointed me in the right direction to find my error.  Closing
