### ISSUE TITLE
Change to include_ipy breaks examples with pip installed version 1.5.0

### ISSUE THREAD

**Issue by losalamosal** [python-cmd2/cmd2#1109]
I'm not sure this is a valid beef, but just as an FYI...

A recent change to many examples where `use_ipython` was changed to `include_ipy` (in the example's `__init__` method) breaks the examples with a pip installed version (1.5.0) of `cmd2`. Easy enough to figure out, but when coming to the repo for examples I wonder if they should be expected to run with the most recently released version (especially if they're in the master branch)? Maybe just an artifact of the way your project does development. Or, I'm missing a canonical site with examples per release (the docs include two examples).

In fact I see that you use the `master` branch for _upcoming_ release, so that explains it. Anyway, as I said, just an FYI.

**Comment by losalamosal** [comment]
Your comment to #1110 addresses my issue as well. Feel free to close.

**Comment by kmvanbrunt** [comment]
Sorry for the inconvenience.
