### ISSUE TITLE
Unable to execute argparse_completion.py example. Throwing TypeError.  unexpected keyword argument 'choices_provider'

### ISSUE THREAD

**Issue by sreekarreddy21** [python-cmd2/cmd2#1110]
I tried executing argparse_completion.py. It outputs the following error. 

Traceback (most recent call last):
  File "argparse_compl.py", line 30, in <module>
    class ArgparseCompletion(Cmd):
  File "argparse_compl.py", line 84, in ArgparseCompletion
    example_parser.add_argument(
  File "C:\Users\sr\anaconda3\lib\site-packages\cmd2\argparse_custom.py", line 478, in _add_argument_wrapper
    new_arg = orig_actions_container_add_argument(self, *args, **kwargs)
  File "C:\Users\sr\anaconda3\lib\argparse.py", line 1368, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'choices_provider'

I tried executing a different program with a custom choices provider function and passed it as an argument to the 'choices_provider'  parameter of the add_argument(). 
Example:

def my_choices_provider(self, arg_tokens):
     ....
     ....

example_parser.add_argument( '--arg1', choices_provider=my_choices_provider)

I got a similar error. What changes can I make?

**Comment by kmvanbrunt** [comment]
Sorry, our master branch is for the upcoming cmd 2.0.0 release, which is a bit different from the current version (1.5.0).

For cmd2 1.5.0, use the examples from one of the following sources.

1. 1.5.0 tag on github: https://github.com/python-cmd2/cmd2/tree/1.5.0
2. Download the tar.gz file from: https://pypi.org/project/cmd2/1.5.0/#files

**Comment by sreekarreddy21** [comment]
Great, it's working. 
Thank you so much.
