### ISSUE TITLE
Weird argparse issue

### ISSUE THREAD

**Issue by jayrod** [python-cmd2/cmd2#1112]
I am working on an app based on cmd2  1.5.0 and I am in a weird scenario. 

> Traceback (most recent call last):
>   File "/root/projects/cmd2-black-noir/venv/bin/bln", line 33, in <module>
>     sys.exit(load_entry_point('cmd2-black-noir', 'console_scripts', 'bln')())
>   File "/root/projects/cmd2-black-noir/venv/bin/bln", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/usr/local/lib/python3.9/importlib/metadata.py", line 77, in load
>     module = import_module(match.group('module'))
>   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/root/projects/cmd2-black-noir/cmd2_black_noir/src/cmd2_black_noir/__init__.py", line 2, in <module>
>     from cmd2_black_noir.app import App
>   File "/root/projects/cmd2-black-noir/cmd2_black_noir/src/cmd2_black_noir/app.py", line 20, in <module>
>     class App(Cmd):
>   File "/root/projects/cmd2-black-noir/cmd2_black_noir/src/cmd2_black_noir/app.py", line 66, in App
>     example_parser.add_argument('--completer', completer=Cmd.path_complete, help="tab complete using a completer")
>   File "/root/projects/cmd2-black-noir/venv/lib/python3.9/site-packages/cmd2/argparse_custom.py", line 478, in _add_argument_wrapper
>     new_arg = orig_actions_container_add_argument(self, *args, **kwargs)
>   File "/usr/local/lib/python3.9/argparse.py", line 1416, in add_argument
>     action = action_class(**kwargs)
> TypeError: __init__() got an unexpected keyword argument 'completer'
> 

I will admit I'm doing some weird things like loading commandsets from external plugins but for some reason I can't get Cmd.path_complete to work. 

I was using python 3.7 and had issues then moved to 3.9 and still issues. What is really weird is that if I pull down cmd2 1.5.1 the issue goes away but then tab complete in my app stops working. I also pulled over the argparse_completion example to my venv and it had the same issue. 

Here is my sample code:
https://github.com/jayrod/test-black-noir

**Comment by kmvanbrunt** [comment]
At the time you coded your app, our master branch contained example code for the unreleased `cmd2` 2.0.0 version. Certain features in 2.0.0 are not backward compatible with 1.5.0. For example, `completer` was called `completer_method` in 1.5.0. That's why you received `unexpected keyword argument`. You were using a 2.0.0 keyword in 1.5.0.

I just put out the 2.0.0 release, so all examples in the master branch should match the current `cmd2` version available on pip. Install that and try your code again.

**Comment by tleonhardt** [comment]
I'm going to resolve this since it appears to have been confusion related to unreleased code which has now been released

**Comment by jayrod** [comment]
I can confirm that I no longer get the stack trace. I still can't seem to get readline working but I don't believe that is cmd2's fault.

**Comment by jayrod** [comment]
Ya issue solved. In my python 3.7 release all is working now. When I had the above error I just went and compiled and installed python 3.9.. I don't know what I did but readline was NOT apart of my 3.9 build but my 3.7 it is. 

I used this to verify. 

[f for f in sys.modules.keys() if 'read' in f]
