### ISSUE TITLE
self.self_in_py = True does not add self to ipy shell

### ISSUE THREAD

**Issue by A1-exe** [python-cmd2/cmd2#1144]
I am trying to use self from the ipy shell. I added code:
```python3
self.self_in_py = True
```
To the object before the call to `super().__init__` but self is not added to the shell environment.

**Comment by kmvanbrunt** [comment]
Since `self_in_py` is a member of the `cmd2.Cmd` class, it's being set to `False` in `super().__init__()`. That overwrites the value you set. Therefore set `self.self_in_py = True` after you call `super().__init__()`.

**Comment by A1-exe** [comment]
Thank you. I'm going to credit you on my project at this point. I keep running into tons of semantic issues lol
