### ISSUE TITLE
Aliases not available when using line command arguments and running onecmd_plus_hooks

### ISSUE THREAD

**Issue by jwag59** [python-cmd2/cmd2#1149]
I have a command interpreter that uses a startup-script to define a set of alias for commands I have implemented.
If you run the interpreter without command arguments the aliases are defined correctly. However when using command line arguments I detect this and run the onecmd_plus_hooks (just like the example in the sources) but in this case the aliases are not created and available for use.
I would really like to have the aliases available even when using command line arguments as well.

Here are some snippets of code (with some debug prints) and the output.

The main() that runs the interpreter class:

```
def main(argv=None):
    """Run when invoked from the operating system shell"""

    #parser = argparse.ArgumentParser(description='Commands as arguments')
    parser = cmd2.Cmd2ArgumentParser(description='Commands as arguments')
    command_help = 'optional command to run, if no command given, enter an interactive shell'
    parser.add_argument('command', nargs='?', help=command_help)
    arg_help = 'optional arguments for command'
    parser.add_argument('command_args', nargs=argparse.REMAINDER, help=arg_help)

    args = parser.parse_args(argv)

    # Instantiate the cmd2.Cmd class 
    app = PMShell()
    print("created App")

    sys_exit_code = 0
    if args.command:
        # we have a command, run it and then exit
        print("Doing onecmd: %s" % args.command)
        if args.command in app.aliases:
            print("found alias: %s" % app.aliases[args.command])
        app.onecmd_plus_hooks('{} {}'.format(args.command, ' '.join(args.command_args)))
    else:
        # we have no command, drop into interactive mode
        print("Doing cmdloop")
        sys_exit_code = app.cmdloop()

    return sys_exit_code  

```

And my class __init__
```
    def __init__(self):

        alias_script = "/opt/pkgmgr/conf/.private/cmd2rc"
        if os.path.exists(alias_script):
            print("Processing init with aliases script")
            cmd2.Cmd.__init__(self, allow_cli_args=False, startup_script=alias_script, persistent_history_file='pmsh_history.dat')
        else:
            print("Processing init with NO aliases")
            cmd2.Cmd.__init__(self, allow_cli_args=False, persistent_history_file='pmsh_history.dat')
```

And the content of the /opt/pkgmgr/conf/.private/cmd2rc
```
#
# Aliases for commands in PkgMgr
#
alias create ng nodegroup
alias create expy export
alias create kops kit
alias create mnt mount
alias create pon ipmi poweron
```

And finally when I run the interpreter:
1)  with command line parameters.
```
[root@fxhead1 ~]# pmsh2 ng list
Processing init with aliases script
created App
Doing onecmd: ng
ng is not a recognized command, alias, or macro
[root@fxhead1 ~]#
```

2) Without command line parameters:
```
[root@fxhead1 ~]# pmsh2
Processing init with aliases script
created App
Doing cmdloop
PMSH - Package Manager Shell - V1.0
Alias 'ng' created
Alias 'expy' created
Alias 'kops' created
Alias 'mnt' created
Alias 'pon' created
pmsh2> exit
[root@fxhead1 ~]#
```

So is this a bug or something I did or didn't do?

**Comment by kmvanbrunt** [comment]
There is no need to manually call the `alias create` commands with `runcmds_plus_hooks()`. If they are in the startup script, then cmd2's `__init__()` method already created a `run_script` startup command for you. This will run all commands in your script, including those that create aliases.

That's why I said to call `app.runcmds_plus_hooks(app._startup_commands)`. This line typically runs in `cmdloop()`. Since your application isn't calling `cmdloop()`, you will have to reproduce some of the code it runs.

> It is a bit odd that when using the shell you can easily use aliases but when using the runcmds or onecmd you cannot.

You can use aliases with `runcmds` and `onecmd`. They just need to exist and that's why you need to run the startup script first. The reason **cmd2** waits until `cmdloop()` to run the startup script is to ensure the application is ready to run commands. Commonly a lot of setup is done in `preloop()`, which `cmdloop()` also calls before running any commands.

You can run `cmd2` in a non-interactive way and still call `cmdloop()` which will do all the setup steps for you. Do something like this.

```Python
def main(argv=None):
    """Run when invoked from the operating system shell"""

    parser = cmd2.Cmd2ArgumentParser(description='Commands as arguments')
    command_help = 'optional command to run, if no command given, enter an interactive shell'
    parser.add_argument('command', nargs='?', help=command_help)
    arg_help = 'optional arguments for command'
    parser.add_argument('command_args', nargs=argparse.REMAINDER, help=arg_help)

    args = parser.parse_args(argv)

    # Instantiate the cmd2.Cmd class
    app = PMShell()

    if args.command:
        # we have a command, add it and a quit command to startup commands
        full_command = '{} {}'.format(args.command, ' '.join(args.command_args))
        app._startup_commands.append(full_command)
        app._startup_commands.append('quit')

    sys_exit_code = app.cmdloop()
    return sys_exit_code
```
