### ISSUE TITLE
Testing completions

### ISSUE THREAD

**Issue by matan1008** [python-cmd2/cmd2#1160]
Dear Lords,

I am trying to write some tests to my Cmd2 application completion.
My application looks like:

```python
student_parser = Cmd2ArgumentParser(description='echo student name')
student_parser.add_argument('name')


class StudentsShell(Cmd):
    def __init__(self, completekey='tab'):
        Cmd.__init__(self, completekey=completekey)
        self.students_path = pathlib.Path('.')
        self.complete_student = self._complete_student

    @with_argparser(cd_parser)
    def do_student(self, args):
        print(args.name)

    def _complete_student(self, text, line, begidx, endidx):
        return [str(p) for p in self.students_path.iterdir() if str(p).startswith(text)]

```

And I would like my test to look something like:

```python
def test_completion():
    shell = StudentsShell()
    assert not shell.complete('student M')
    open('Mark', 'w')
    assert shell.complete('student M') == ['Mark']

```

Is that possible? is there any way to test the shell completion?

Thanks in advance!

**Comment by kmvanbrunt** [comment]
Calling `shell.complete()` directly requires mocking out certain functions normally provided by GNU readline. cmd2 does this in our unit tests in [conftest.py](https://github.com/python-cmd2/cmd2/blob/master/tests/conftest.py#L171)

For your case, it's simpler just to test `_complete_student()` directly.

```Python
def test_completion():
    shell = StudentsShell()
    
    text = 'M'
    line = f'student {text}'
    endidx = len(line)
    begidx = endidx

    assert shell._complete_student(text, line, endidx, begidx) == ['Mark']
```

**Comment by matan1008** [comment]
The issue with testing `_complete_student` (which I am already doing) is that I can't test the integration between my code and the completion.
For example, if I had a typo and instead of:
`self.complete_student = self._complete_student` 
I wrote:
`self.complete_studet = self._complete_student`
Testing `_complete_student` alone will not be good enough.
I will try the mock attitude soon and will close the issue if it works, Thanks!

**Comment by tleonhardt** [comment]
@matan1008 Were you able to work around your problem?

**Comment by matan1008** [comment]
Kind of, I did the following:

```python
def get_completions(line, part, app):
    def get_line():
        return line

    def get_begidx():
        return len(line) - len(part)

    def get_endidx():
        return len(line)

    with mock.patch.object(gnureadline, 'get_line_buffer', get_line):
        with mock.patch.object(gnureadline, 'get_begidx', get_begidx):
            with mock.patch.object(gnureadline, 'get_endidx', get_endidx):
                app.complete(part, 0)

    return app.completion_matches


def test_completion():
    shell = StudentsShell()
    assert not get_completions(f'student M', 'M', shell)
    open('Mark', 'w')
    assert ['Mark'] == get_completions(f'student M', 'M', shell)
```

It feels like a really patchy, horrible and unstable workaround tho.
