### ISSUE TITLE
cmd2.ansi.style stopped accepting strings without any deprecation, breaking the world

### ISSUE THREAD

**Issue by duck-rh** [python-cmd2/cmd2#1167]
Quack,

You just released 2.3.0, thanks for your hard work,

I just stumbled upon the fact that `cmd2.ansi.style` suddenly does not support using strings for color names and I was not expecting such incompatibility according to the changelog. I guess that's too late but at least the changelog should be updated with proper warnings.

```
Traceback (most recent call last):
  File "/srv/ldapwalker/./bin/ldapwalker", line 54, in <module>
    app = LdapWalkerApp(config, allow_cli_args=False, lockdown=lockdown, read_only=read_only, cli_conn_name=args.connection, log_debug=args.log)
  File "/srv/ldapwalker/ldapwalker/app.py", line 138, in __init__
    + cmd2.style("Lockdown mode:", fg="red", bold=True)
  File "/usr/local/lib/python3.9/dist-packages/cmd2/ansi.py", line 986, in style
    raise TypeError("fg must be a subclass of FgColor")
TypeError: fg must be a subclass of FgColor
```

Regards.
\\_o<

**Comment by kmvanbrunt** [comment]
@duck-rh Sorry about that. I forgot I made that change when I was writing the change log. I've updated both the change log file and release notes.

**Comment by duck-rh** [comment]
@kmvanbrunt thanks
