### ISSUE TITLE
Shell backgrounding doesn't appear to work in transcript generation or playback

### ISSUE THREAD

**Issue by MrSurly** [python-cmd2/cmd2#1184]
Performing this command:

`shell aplay /dev/zero -f S16_LE -c 2 -r 16000 -t raw -d 3 &`

works as expected, and `aplay` is backgrounded properly.

However, attempting to create a transcript with a backgrounded command via `history -t transcript.txt` will result in the script hanging as the `aplay` command is not backgrounded.

I can actually create the transcript: As a workaround, I hit CTRL-C during transcription recording to kill the process and manually fixup the transcript.

However, the resulting transcript (when replayed) also does not properly background the `aplay` commands as it would in an interactive CLI.

**Comment by MrSurly** [comment]
I also tried `shell bash -c 'aplay /dev/zero -f S16_LE -c 2 -r 16000 -t raw -d 3 &'` -- same effect

**Comment by MrSurly** [comment]
I assumed this was an issue with the ampersand (`&`) character, so I tried using the `bash` keyword `coproc`, which _does work_ in interactive CLI, but when generating a transcript I get: `/bin/sh: 1: coproc: not found`, which implies that the interactive CLI is using `bash`, and the transcript create/replay is using `sh`, which doesn't have `coproc`.

However, on my system (raspi), `/bin/sh` is `dash`, which does have ampersand backgrounding, so I'm not sure why that doesn't work in the first place. or why `bash -c 'command &'` doesn't work.

**Comment by MrSurly** [comment]
This did end up working: `shell bash -c 'coproc aplay /dev/zero -f S16_LE -c 2 -r 16000 -t raw -d 10'`

**Comment by kmvanbrunt** [comment]
I'm curious as to why your transcript environment is running a different shell than the interactive environment.
Our `do_shell()` function obtains attempts to capture the user's shell with `shell = os.environ.get("SHELL")`.
If that is successful, then it passes that as the `shell` keyword argument to `Popen()`.

I created a transcript file using `history -t` with the following contents:
```
(Cmd) !echo $SHELL
\/bin\/bash
```

When I run that transcript, it succeeds, which means my transcripts were kicked off in a `bash` environment.
Can you run that same transcript and see what you get?
