### ISSUE TITLE
cmd2 and libedit

### ISSUE THREAD

**Issue by duck-rh** [python-cmd2/cmd2#1186]
Quack,

While porting cmd2 from 2.1.2 to 2.3.3 on Debian unstable I stumbled onto massive tests failures. It happens that Python 3.10 is now built (3.9 stays the default at the moment) and that it was built with libedit. I found that in `cmd2/rl_utils.py` line 129 you explain cmd2 is not compatible with libedit. This code path  causes `readline` and `rl_force_redisplay` to later be undefined.

I read on the web that libedit made some progress (not sure to what extent except BSD support) and was considered as default for Python 3.10. I thus tried to disable the above check and so far cmd2 is working perfectly.

Could you consider checking if this requirement is not obsolete nowadays?

Regard.
\\_o<

**Comment by kmvanbrunt** [comment]
I'll need to research this. The original reason we didn't support `libedit` can be found in issue #383.
It boiled down to it not supporting [readline.set_completion_display_matches_hook](https://docs.python.org/3/library/readline.html#readline.set_completion_display_matches_hook).

Hopefully this all works now since Python 3.10 may be moving to `libedit`.

**Comment by giovannt0** [comment]
Hey there,

+1'ing this issue as I'm running into similar problems. Native support of libedit would be awesome.

**Comment by kmvanbrunt** [comment]
After researching this, it looks like **libedit** has the same issue it did when I first tried to fix this in 2018.

**cmd2** sets a custom display function using [readline.set_completion_display_matches_hook()](https://docs.python.org/3/library/readline.html#readline.set_completion_display_matches_hook) to support many of the advanced tab completion features (e.g. tab completion tables, displaying path basenames, colored results, etc.)

`readline.set_completion_display_matches_hook()` "sets or clears the `rl_completion_display_matches_hook` callback in the underlying library". **libedit** has never implemented this hook. It merely sets it to NULL and never references it.

Until **libedit** supports a custom completion display function, **cmd2** can't use it.

**Comment by duck-rh** [comment]
@kmvanbrunt thanks a lot for looking into it. Indeed that's a big problem. I've asked the python 10 maintainers if switching back to readline would be possible. I guess in the long run it would be nice if libedit was improved.

**Comment by kmvanbrunt** [comment]
@duck-rh To get around this for now, install [gnureadline](https://pypi.org/project/gnureadline/) in your Python 3.10 environment. **cmd2** tries to load that first.

**Comment by duck-rh** [comment]
@kmvanbrunt thanks for the tip.

Since that changes can break other programs I think it's better to revert to building Python with readline and the Debian maintainer did not even discussed it and changed things back in 3.10.2-2.
