### ISSUE TITLE
back space  output ^H

### ISSUE THREAD

**Issue by morzen** [python-cmd2/cmd2#1196]
Hello, I came across an issue while creating a CLI which I can't show you, so the example will be done using your basic.py program from the example programs.
(although I had to make some modifications around the blue arrows see picture )

changing use_ipython=True to include_ipy=True
other wise i had errors
and change 
self.intro = style('Welcome to PyOhio 2019 and cmd2!', fg='red', bg='white', bold=True) + ' 😀'
to
self.intro = style('Welcome to PyOhio 2019 and cmd2!', bold=True) + ' 😀'
other wise i had error as well 

and has you can see on the screenshot on the first line of the prompt i am able to delete without any issue what I type but if I enter and pass to a new prompt line then when hitting backspace ^H appears.

![image](https://user-images.githubusercontent.com/32000608/151562132-6dae4742-0cf1-460b-99d4-4df05324d4c1.png)

This being quite a specific problem l was unable to find people with similar issue although it appears backspace and ipython have a history.

An important point to note is that cmd (previous version of cmd2) did not suffer from this issue, might be something to look into, in order to improve backward compatibility.

I thank you very much for reading this post

**Comment by kmvanbrunt** [comment]
Check if this post explains the issue you're seeing.
https://github.com/python-cmd2/cmd2/issues/1009

**Comment by morzen** [comment]
IT does indeed, thanks for helping just curious do you think it might risk happening if I put the CLI program I m developing on a docker?

but I am guessing if it does I can run a pre-loop scrip to make the terminal change? because I am trying that the user won't have to do such thing
