### ISSUE TITLE
Failure to import cmd2 in latest version (2.4)

### ISSUE THREAD

**Issue by kpad-git** [python-cmd2/cmd2#1212]
My application has been working fine for a year using cmd2 version 1.5.0. Today I tried to install cmd2_ext_test to expand our testing infrastructure. As part of that, it automatically upgraded cmd2 to version 2.4.0.

Now, even a simple cmd2 application copied from the examples gives me this error on the "import cmd2" line:

```
Traceback (most recent call last):
  File "c:\Users\xxxx\xxxx\src\test.py", line 3, in <module>
    import cmd2
  File "xxxx\Python\Python39\site-packages\cmd2\__init__.py", line 53, in <module>
    from .cmd2 import Cmd
  File "xxxx\Python\Python39\site-packages\cmd2\cmd2.py", line 125, in <module>
    from .rl_utils import (
  File "xxxx\Python\Python39\site-packages\cmd2\rl_utils.py", line 144, in <module>
    if 'libedit' not in readline.__doc__:
TypeError: argument of type 'NoneType' is not iterable
```

I'm using Python 3.9 on Windows 10 Home. For reference, here is the test.py code (again, just copied from an example):

```
#!/usr/bin/env python
"""A simple cmd2 application."""
import cmd2
class FirstApp(cmd2.Cmd):
    """A simple cmd2 application."""
if __name__ == '__main__':
    import sys
    c = FirstApp()
    sys.exit(c.cmdloop())
```

**Comment by kpad-git** [comment]
I should have clarified, this is most likely not a bug with cmd2, but an issue on my side, but I can't find any resources to help narrow it down. Hoping for some sage advice from here... thanks!

**Comment by anselor** [comment]
I think @kmvanbrunt understands this area the best. Based on the error, it would probably help if you also provided the versions of packages installed in your environment. I recall there being some nuance regarding Windows and using a specific readline library.

**Comment by kmvanbrunt** [comment]
Check to see if you have `pyreadline3` installed. Also, make sure it's not simultaneously installed alongside `pyreadline`.

**Comment by kpad-git** [comment]
@kmvanbrunt, thank you for the quick assist, that was indeed the issue: I had pyreadline v2.1 and pyreadline3 v3.3 installed simultaneously. Removing the former, and upgrading the latter to 3.4.1 got it working again (without upgrading, cmd2 complained about disabling tab completion).
