### ISSUE TITLE
Document use of docopt-based parser for option processing

### ISSUE THREAD

**Issue by phrrngtn** [python-cmd2/cmd2#1215]
Hi,
I like to use docopt for simple scripts. I  wrote an integration with Cmd2 yearas ago and have been using it at work. I only noticed recently that there is an argparser integration in Cmd2 and then led me to search for something that converts docopt to argparser and that led me to argopt.

This allows you to write Cmd2 commands with usage-style docstrings and all the completion stuff etc just works.

```python
@hasdocopt
def do_banana(self, opts):
        '''Example programme description.
You should be able to do
    args = argopt(__doc__).parse_args()
instead of
    args = docopt(__doc__)

Usage:
    banana [options] <x> [<y>...]

Arguments:
    <x>                   A file.
    --anarg=<a>           Description here [default: 1e3:int].
    -p PAT, --patts PAT   Or [default: None:file].
    --bar=<b>             Another [default: something] should
                          auto-wrap something in quotes and assume str.
    -f, --force           Force.
'''
```

The implementation of the decorator is very straightforward

```python
from argopt import argopt

def hasdocopt(f, *args, **kwargs):
    parser=argopt(f.__doc__)
    return with_argparser(parser)(f)
```

I have not tested this extensively but I was kind of surprised that it seems to work so well. I wanted to share the results here. Perhaps the recipe could be added to the documentation if you think it may be useful to others.

**Comment by anselor** [comment]
@phrrngtn This looks pretty great. Will have to play with this some and see how it goes. Does docopt allow sub-commands like argparse?

@jayrod You might like this too

**Comment by phrrngtn** [comment]
Will do. I have not been doing anything other than dayjob for several months so it may be some time.

**Comment by tleonhardt** [comment]
I'm going to close this.  But @phrrngtn we would be very happy to accept a PR that adds and example to document this use case.
