### ISSUE TITLE
async_alert causes a double-prompt when called from the main thread.

### ISSUE THREAD

**Issue by anselor** [python-cmd2/cmd2#1221]
It seems if async_alert() somehow gets called from the main thread, it causes the prompt to be doubled.

**Comment by kmvanbrunt** [comment]
`async_alert()` isn't supposed to be called from the main thread. It's only needed when the main thread is blocking at the prompt.

**Comment by kmvanbrunt** [comment]
I'll raise a `RuntimeError` if developers try to call it from the main thread.

**Comment by kmvanbrunt** [comment]
See the [async_printing](https://github.com/python-cmd2/cmd2/blob/master/examples/async_printing.py) example for help with using this function.
