### ISSUE TITLE
How to use a custom namespace from cmd2.Cmd class with CommandSets

### ISSUE THREAD

**Issue by mattsingh** [python-cmd2/cmd2#1232]
As per title.

I am trying to use a namespace provider in the `cmd2.Cmd` to default a value for a command in a `CommandSet`.  How should I go about referencing the namespace provider in the main `cmd2.Cmd` from a `CommandSet`?

**Comment by kmvanbrunt** [comment]
This example shows how to reference a namespace provider in the main `cmd2.Cmd` class from a `CommandSet`.

```Python
import argparse

from cmd2 import (
    Cmd,
    Cmd2ArgumentParser,
    CommandSet,
    with_argparser,
)


class App(Cmd):
    """Main cmd2.Cmd app class"""

    def ns_provider(self) -> argparse.Namespace:
        """Custom namespace provider in the main application class"""
        ns = argparse.Namespace()
        ns.custom_arg = "custom value"
        return ns


class TestSet(CommandSet):
    parser = Cmd2ArgumentParser(description="Test Command")

    # Use the namespace provider from the App class
    @with_argparser(parser, ns_provider=App.ns_provider)
    def do_test_cmd(self, args: argparse.Namespace) -> None:
        # Print the prepopulated value in the namespace
        self._cmd.poutput(args.custom_arg)


if __name__ == '__main__':
    import sys

    app = App()
    sys.exit(app.cmdloop())
```

**Comment by mattsingh** [comment]
Sorry, I should've been more clearer. I also wanted the namespace to overwrite the positional arguments from an argument parser. That way the positional argument wouldn't be required since it was passed with the namespace. I don't think it was possible so I did a workaround respective to my situation.
Thanks though :)
