### ISSUE TITLE
[1.5.0] `choices_method` does not actually restrict argument choices

### ISSUE THREAD

**Issue by ddejohn** [python-cmd2/cmd2#1242]
Using `cmd2` version `1.5.0`, the `choices_method` for an argument *do* help with tab completion, but *do not* actually restrict the choices of values a user can legally input, contrary to how `argparse` module's `choices` works.

**Comment by kmvanbrunt** [comment]
This is documented at https://cmd2.readthedocs.io/en/1.5.0/api/argparse_custom.html

> Of the 5 tab completion parameters, choices is the only one where argparse validates user input against items in the choices list. This is because the other 4 parameters are meant to tab complete data sets that are viewed as dynamic. Therefore it is up to the developer to validate if the user has typed an acceptable value for these arguments.

If you know the dataset beforehand, just uses `choices`. cmd2 will tab complete those just like it does items provided from `choices_method` and `argparse` will validate your input.

When using a dynamic dataset via `choices_method`, you can either validate the input within the `do_` function or you can use a custom `argparse` type which will validate the input while the args are being parsed by `argparse`.

**Comment by ddejohn** [comment]
My apologies, I missed that in the docs.
