### ISSUE TITLE
Can I reuse argparser with printing help properly?

### ISSUE THREAD

**Issue by ymkim92** [python-cmd2/cmd2#1254]
I am using version 2.4.2. When I reuse argparser, the help displays the last command name using the argparser.

```
parser = Cmd2ArgumentParser()
parser.add_argument("value")

@with_argparser(parser)
def do_command1(self, args):
    """command1"""

@with_argparser(parser)
def do_command2(self, args):
    """command2"""
```

```
> command1 -h
Usage: command2 [-h] value   <<< This problem.

command1

positional arguments:
  value

optional arguments:
  -h, --help    show this help message and exit

```

**Comment by tleonhardt** [comment]
@ymkim92 

When I've wanted to re-use a parser like that what I've done is to create a factory function which creates the parser I want and then call that.  That way each one is a separate instance of a parser.  

If you do this in a smart way, you can often create a base parser with common stuff that you then customize and prevent duplicated code.

**Comment by ymkim92** [comment]
@tleonhardt Thanks for the good idea.
