### ISSUE TITLE
Can I call Command Scripts from python code?

### ISSUE THREAD

**Issue by jkeen871** [python-cmd2/cmd2#1261]
I have a python function that will monitor for a specific value to be true or false. 
If the function is true, I would like to call a command script from my python code.

To be clear, in the case that I have my terminology wrong.

Python will monitor an API and look for a value to be true.  When true I want to execute a command script, lets say @foo.  Then continue to monitor the API for the condition to be true again. Then execute @foo again.

Thank you!!

**Comment by kotfu** [comment]
Sure thing. You can use the [onecmd_with_hooks()](https://cmd2.readthedocs.io/en/stable/api/cmd.html#cmd2.Cmd.onecmd_plus_hooks) method. Here's how you could do it using the [pirate.py](https://github.com/python-cmd2/cmd2/blob/master/examples/pirate.py) example included in cmd2.

First, create a file called `foo` in `cmd2/examples` which will contain your script. It should contain:
```
loot
yo rum
loot
drink
```

Then from the `cmd2/examples` directory, run the following interactive python session:
```
python
Python 3.11.1 (main, Jan 28 2023, 14:06:31) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pirate
>>> p = pirate.Pirate()
>>> _ = p.onecmd_plus_hooks("@foo")
Now we gots 1 doubloons
yo ho ho and a bottle of rum
Now we gots 2 doubloons
Now we gots 1 doubloons
Now we gots 1 doubloons
>>>
```

You would still need to put the `onecmd_plus_hooks("@foo")` call inside a loop which calls your monitoring function, and have some exit criteria for leaving the loop, but this should give you what you need from a `cmd2` perspective.
