### ISSUE TITLE
Edit auto complete in a specific directory

### ISSUE THREAD

**Issue by jkeen871** [python-cmd2/cmd2#1266]
How can I set the editor to look at a specific path?

For example scripts directory..

I want to be able to type edit and it will autocomplete from the scripts directory.

**Comment by kotfu** [comment]
The `edit` command built into `cmd2` can not be configured to look at a specific path or to do command completion. However, you can easily create your own new command (and can even call it `edit` if you wish) to add this additional functionality.

`cmd2` includes a method called `run_editor(file_path)` which launches the editor for the passed file. Here's a very simple working example which makes the edit command more convenient to edit scripts in the script directory you provide:
```
#!/usr/bin/env python3
import pathlib
import cmd2

class EditExample(cmd2.Cmd):
    def do_edit(self, arg):
        mydir = pathlib.Path("/my/script/dir")
        file = mydir / arg
        self.run_editor(file)

if __name__ == '__main__':
    # Create an instance of the Pirate derived class and enter the REPL with cmdloop().
    app = EditExample()
    app.cmdloop()
```

See https://cmd2.readthedocs.io/en/latest/features/completion.html for more information on how to add completion to this edit command.

You can also look at how the `edit` command [is implemented](https://github.com/python-cmd2/cmd2/blob/fbabd9bff4c66766f74d50e3c05eaf58e5a6f6de/cmd2/cmd2.py#L4799-L4809) in `cmd2`.
