### ISSUE TITLE
New versions of Statekeeper, ParsedString

### ISSUE THREAD

**Issue by martha889** [python-cmd2/cmd2#1274]
Hi all. I've upgraded my cmd2 version from 0.8.0 to 2.4.3 and seeing an import error while trying to import Statekeeper and ParsedString from the cmd2 package. These classes got removed from  v1.0.0 onwards.

```
ImportError: cannot import name 'Statekeeper' from 'cmd2'
```

Any idea how their functionality has changed/moved since the earlier version?

**Comment by anselor** [comment]
Do either of you remember what Statekeeper and ParsedString are? @kmvanbrunt @tleonhardt

**Comment by kmvanbrunt** [comment]
`ParsedString` became `parsing.Statement`.
`StateKeeper` was split betwen `utils.RedirectionSavedState` and `cmd2._SavedCmd2Env`.

**Comment by martha889** [comment]
Thanks @kmvanbrunt
