### ISSUE TITLE
how to save the Settable

### ISSUE THREAD

**Issue by tangc1986** [python-cmd2/cmd2#1295]
I have customized some Settables and want to keep the values of these Settables on next startup.
How should I save these Settables?
Thanks.

**Comment by anselor** [comment]
It's entirely up to you how you want to persist settings. The `Settable` has as an attribute `onchange_cb` that allows you to provide a callback function when that setting is changed.

On start-up, after the `cmd2.Cmd` constructor is complete, you can load the values from whatever persistence method you choose and load the values in the settables (`cmd2.Cmd.settables`)

**Comment by kotfu** [comment]
Here's an example of a cmd2 based application that saves settables in a TOML file. This method loads the settings from a file and applies them: https://github.com/tomcatmanager/tomcatmanager/blob/main/src/tomcatmanager/interactive_tomcat_manager.py#L1625

**Comment by kmvanbrunt** [comment]
Closing since question was answered.
