### ISSUE TITLE
vertically help menu 

### ISSUE THREAD

**Issue by githubc5** [python-cmd2/cmd2#1299]
Hello, can you tell me how I can display the help menu vertically?
for example like this
(Cmd) help

Documented commands (use 'help -v' for verbose/'help <topic>' for details):
===========================================================================
alias   
history
quit 
run_script  
shell
help
macro
run_pyscript
set
shortcuts

**Comment by kotfu** [comment]
`cmd2` doesn't do this natively, but you can easily override the help command to format the help however you want. See https://github.com/tomcatmanager/tomcatmanager/blob/8a8f7f5ecbeb8eb7fa2c703e7f1b971de7c50bba/src/tomcatmanager/interactive_tomcat_manager.py#L666 for an example.

**Comment by githubc5** [comment]
Спасибо!
