### ISSUE TITLE
Order of shortcuts matter, but defined as dictionary

### ISSUE THREAD

**Issue by FedericoCeratto** [python-cmd2/cmd2#13]
Originally reported by: **Kent Duncan (Bitbucket: [slamduncan](http://bitbucket.org/slamduncan), GitHub: [slamduncan](http://github.com/slamduncan))**

---

When adding to the shortcut list, if one shortcut is the start of another shortcut than it will override it and pass the remainder of the longer shortcut in arg.

Example:
    Cmd.shortcuts.update({
                          'p': 'first_sc',
                          'pcon' : 'second_sc',
     })

When it's running if you type in pcon it will call do_first_sc with the arg 'con'. 

---
- Bitbucket: https://bitbucket.org/catherinedevlin/cmd2/issue/13

**Comment by tleonhardt** [comment]
Within the __init__() initializer for the cmd2.Cmd class, the shortcuts dictionary is sorted in reverse alphabetical order by key (i.e. by shortcut).  I'm not sure when this code was added, but it solves this particular problem.
