### ISSUE TITLE
Getting extra quotes when tab autocomplete(behaviour different when compared with cmd)

### ISSUE THREAD

**Issue by Sripadvallabh** [python-cmd2/cmd2#1300]
I am trying to migrate my cmd script to cmd2 for the enhanced features; however facing one issue with autocomplete which is blocking migration:
As shown in below example, when i try to autocomplete 'param' command to 'param import' by typing i<tab>; rather than getting **'param import'** i am getting the output **'param "import "'** which is not what i had intended to autocomplete:

### Cmd2 behaviour:
>(lӓut-leaf1) param
>import     set
>(lӓut-leaf1) param "import "

### Cmd behaviour with same complete_*()
>(lӓut-leaf1) param
>import     set
>(lӓut-leaf1) param import

```
def complete_param(self, text, line, start_index, end_index):
    wordCount = len(line.split())
    if (wordCount == 1 and start_index == end_index) or (wordCount == 2 and start_index != end_index):
        return [word + ' ' for word in list(self.paramsDict.keys()) + ['set', 'import'] if word.startswith(text)]
    else:
        return []
```

Is there a way i can get the necessary cmd behaviour in cmd2 as much of the script has already been long back written with cmd module & dozens of commands autocompleted this way. Because in my case, i am not using any argparse & when i return a list of strings to be complete it just needs to complete that without adding the extra "".

I had tried to return cmd2.Cmd.basic_autocomplete with the list passed to match_string but still seeing the same issue there.

**Comment by kmvanbrunt** [comment]
cmd2 adds quotes around any completion which contains a space.
Don't add the space to `word` on this line: `return [word + ' ' …]`.

**Comment by Sripadvallabh** [comment]
Got it. It works after removing the extra space(which was necessary in cmd module, since it doesn't add that space)

**Comment by Sripadvallabh** [comment]
Hi, there was another scenario where i didn't want that extra space to be added when i press <tab>:

### cmd behaviour
>(lӓut-xtr7) param a.b.c
>3

### cmd2 behaviour
>(lӓut-xtr7) param a. 

For the above specific case, i am getting a.<space> when i press <tab> in cmd2; whereas in cmd i would get a.b. on <tab>; when i tried to backspace and retry <tab> i get a.b. on cmd2 also but that won't be good. Is there a way to tell cmd2 of this behaviour too?

The complete fn here(basically a dictionary walker, everytime we enter the next nested part we add a '.'):
```
def complete_var(self, text, line, start_index, end_index):
    returnList = []
    wordCount = len(line.split())
    if (wordCount == 1 and start_index == end_index) or (wordCount == 2 and start_index != end_index):
        varPathList = text.split('.')
        currentDict = self.varsDict
        if text == '':
            returnList += [key for key in currentDict.keys()]
        elif text[-1] == '.':
            for key in varPathList:
                if key in currentDict.keys():
                    currentDict = currentDict[key]
            returnList += [text + key for key in currentDict.keys()]
        else:
            for key in varPathList[:-1]:
                if key in currentDict.keys():
                    currentDict = currentDict[key]
            if varPathList[-1] in currentDict.keys():
                if isinstance(currentDict[varPathList[-1]], dict):
                    returnList.append(text + '.')
                else:
                    pass
            returnList += [text + key[len(varPathList[-1]):] for key in currentDict.keys() if key.startswith(varPathList[-1]) and
    return(returnList)
```

**Comment by Sripadvallabh** [comment]
Kevin, thanks for your detailed explanation. Method 1 works for me.
cmd2 has a lot of features over cmd which is why my team is trying to move over to cmd2 now. Thanks for your help & patience in creating this. I also appreciate your close watch over the issues in cmd2. Really excited to move over from cmd to cmd2 without any hassle.
