### ISSUE TITLE
onecmd throwing RecursionError?

### ISSUE THREAD

**Issue by Exvix** [python-cmd2/cmd2#1302]
Python 3.12.2
CMD2 Version 2.4.3
Windows 10 22H2

# Explanation:

In the original cmd module, the self.onecmd basically allows you to run commands from within the class.
```
import cmd

class MyCmd(cmd.Cmd):
    prompt = '> '
    
    def do_greet(self, line):
        print("Hello,", line)
    
    def do_repeat(self, line):
        """Repeat a command"""
        self.onecmd(line)
        self.onecmd(line)

    def do_exit(self, line):
        print("Goodbye!")
        return True

    def default(self, line):
        print("Unknown command:", line)

if __name__ == '__main__':
    MyCmd().cmdloop()
```
The ```do_repeat``` function basically repeats a command 2 times, and it works fine.
However, if I use cmd2 instead of cmd, it returns (with debug enabled):
```
  File [PATH_NOT_IMPORTANT], line 11, in do_repeat
    self.onecmd(line)
  File [PATH_NOT_IMPORTANT], line 2842, in onecmd
    func = self.cmd_func(statement.command)
  File [PATH_NOT_IMPORTANT], line 2815, in cmd_func
    return cast(Optional[CommandFunc], getattr(self, func_name))
                ~~~~~~~~^^^^^^^^^^^^^
  File [PATH_NOT_IMPORTANT], line 395, in inner
    return _caches[func](*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File [PATH_NOT_IMPORTANT], line 1259, in __hash__
    return hash((self.__origin__, self.__args__))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
EXCEPTION of type 'RecursionError' occurred with message: maximum recursion depth exceeded
```
Why?

**Comment by kmvanbrunt** [comment]
`cmd2` commands take `Statement` objects and not strings like `cmd` commands.

https://cmd2.readthedocs.io/en/stable/features/commands.html#statements

To fix the recursion issue, do either of the following:

1. `self.onecmd(str(line))`
2. `self.onecmd(line.args)`

Both approaches will do the same thing, extract only the arguments passed to `repeat`.

**Comment by Exvix** [comment]
Thank you so much. My brain completely skimmed over that bit.
