### ISSUE TITLE
Do you support placeholder

### ISSUE THREAD

**Issue by zhouhao27** [python-cmd2/cmd2#1307]
For example:

```bash
>>> Please input your name
```

The >>> is the prompt. `Please input your name` is the placeholder. The cursor is in front of `Please`. When you input anything, the placeholder will be disappeared.

**Comment by kmvanbrunt** [comment]
No, `cmd2` does not have built-in support for placeholder text.

**Comment by anselor** [comment]
You can do this simply by adding \b to the end of the string you pass to `input()`

for example:
```
placeholder = 'Please input your name'
input(f'>>> {placeholder}' + ('\b'*len(placeholder)))
```

**Comment by zhouhao27** [comment]
> You can do this simply by adding \b to the end of the string you pass to `input()`
> 
> for example:
> 
> ```
> placeholder = 'Please input your name'
> input(f'>>> {placeholder}' + ('\b'*len(placeholder)))
> ```

It works. The only thing is I need to remove the place holder when anything input. How to detect if there is anything input?

**Comment by kmvanbrunt** [comment]
`cmd2` does not provide built-in support for detecting keypresses. This is functionality you'll have to code in your application.
