### ISSUE TITLE
Is it possible to disable other python package to output to console?

### ISSUE THREAD

**Issue by zhouhao27** [python-cmd2/cmd2#1312]
I'm running some third party libraries. I'm wondering if I'm able to disable output from those libraries to console? I tried `set quiet True`. But didn't work. Any idea? Thanks.

**Comment by kotfu** [comment]
The `quiet` setting only controls output from `cmd2`. It will have no impact on output generated from other libraries. You'll have to look for logging/output settings in each of those third party libraries.
