### ISSUE TITLE
Race Condition Involving async_alert

### ISSUE THREAD

**Issue by missimer-tyr1labs** [python-cmd2/cmd2#1319]
I believe there is a race condition involving async_alert related to the call to input at cmd2.py:3192 that can result in the command prompt being printed twice.

Pip freeze output:
```
$pip freeze
attrs==24.2.0
cmd2==2.4.3
pyperclip==1.9.0
wcwidth==0.2.13
```

Python Version: 
```
$python3 --version
Python 3.10.13
```

OS Version:
```
$lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

Minimal Example Program Demonstrating Potential Issue:

```
from cmd2 import Cmd
import threading
import time

class Example(Cmd):

    def thread_main(self):
        with self.terminal_lock:
            self.async_alert("AAAAAAAAAAAAAA")

    def do_test(self, args):
        threading.Thread(target=self.thread_main, daemon=True).start()
        # Sleep to let the thread start and grabbing the lock to increase the chance of race
        # condition
        time.sleep(1)

if __name__ == "__main__":
    Example().cmdloop()
```

Example use case exposing bug with output:
```
$ python3 ./tmp.py 
(Cmd) test
AAAAAAAAAAAAAA
(Cmd) (Cmd) 
```

Note the two `(Cmd)`'s being printed.

------ 

First pass debugging (note all line numbers are based on master as of 8/31/2024):

Note: All of the following is a guess based on a relatively quick glance so take it with a grain of salt.

I believe fundamentally the issue is because when `input` is called on line cmd2.py:3192 it is called without the terminal lock which was released on line cmd2.py:3236.  I get way `input` is called without the lock since it is a blocking call but the issue is that input itself is actually printing the prompt which causes the prompt to be printed twice.  It seems that `terminal_lock` is fundamentally a lock around printing output to the terminal and because the `input` call on cmd2.py:3192 both prints and waits for user input it is breaking the concept that `terminal_lock` as a lock for the terminal output.  Perhaps a fix would involve printing the prompt before release the lock and then having the `input` call on cmd2.py:3192 be without any arguments.  This is just a guess as I haven't looked into this bug more as I'm sure those with more knowledge of cmd2 will come with the best solution.

**Comment by kmvanbrunt** [comment]
Yes, unfortunately there is a known race condition but there isn't anything we can to do fix it. Thankfully it rarely occurs and while an occasional extra prompt looks weird, it doesn't break anything.

The `readline` library needs to know what the prompt is so it doesn't overwrite it during things like up-arrow history. Therefore manually printing the prompt and calling `input()` with no arguments won't work.

If we controlled the `readline` code, then we could sync things a bit better. But that's a third-party compiled C library.
