### ISSUE TITLE
Incorrect indent when display multiline help text using `Cmd2ArgumentParser`

### ISSUE THREAD

**Issue by nfnfgo** [python-cmd2/cmd2#1332]
# Issue

As the title says, the indent behaviour seems incorrect when the help text is in more than one line when printed to the terminal.

**Expected Behaviour**

![image](https://github.com/user-attachments/assets/9fcbe336-4cc9-44ee-8ff3-d7388bf391a5)

**Actual Behaviour**

![image](https://github.com/user-attachments/assets/d596f8ce-f3c5-438b-8ef6-f9c19b58c00d)

-----

After simple debugging, I believe that this issue is caused by `Cmd2HelpFormatter` at /cmd2/argparse_custom.py, which is used as the default value of `formatter_class` for `Cmd2ArgumentParser`.

https://github.com/python-cmd2/cmd2/blob/3062aaa195e1afac2b9058902bb4530b6668787a/cmd2/argparse_custom.py#L1045

https://github.com/python-cmd2/cmd2/blob/3062aaa195e1afac2b9058902bb4530b6668787a/cmd2/argparse_custom.py#L1252-L1262

Also when I changed the super class of `Cmd2HelpFormatter` from `argparse.RawTextHelpFormatter` to `argparse.ArgumentDefaultsHelpFormatter`, the expect behaviour comes back and the issue is resolved.

```diff
- class Cmd2HelpFormatter(argparse.RawTextHelpFormatter):
+ class Cmd2HelpFormatter(argparse.ArgumentDefaultsHelpFormatter):
```

However, currently I'm not sure which part inside `Cmd2HelpFormatter` has led to this issue and whether changing the super class will cause some other unexpected side effects.

**Comment by kmvanbrunt** [comment]
`RawTextHelpFormatter` requires you to include `\n` characters where you want the line breaks.

**Comment by kmvanbrunt** [comment]
We use `RawTextHelpFormatter` because it preserves newlines in our help text. That gives us more control on how the help text looks. However, the wrapping does not account for screen width.

I'm looking to update our help formatter to both preserve newlines and account for screen width.

**Comment by nfnfgo** [comment]
Thanks for the reply! I think my previous description is inaccurate and what you described in your response is actually what I wanted to discuss.

> We use `RawTextHelpFormatter` because it preserves newlines in our help text. That gives us more control on how the help text looks. However, the wrapping does not account for screen width.
> 
> I'm looking to update our help formatter to both preserve newlines and account for screen width.

I get that using `RawTextHelpFormatter` means adding manual newlines to control the help text format. However, in my case, I'm not looking for that much control and I just want the help text to be automatically wrapped based on the screen width.

I could specify another formatter for each `argparser` like this:

```python
export_args = Cmd2ArgumentParser(formatter_class=OtherFormatterClass)
```

But this approach would replace the default `Cmd2HelpFormatter` used by `Cmd2ArgumentParser`, and I'm not sure if that would impact other functionalities provided by the `cmd2` library.

**Comment by kmvanbrunt** [comment]
You can use whatever `formatter_class` you need to for your commands and it won't cause any issues.
The `Cmd2ArgumentParser` does not depend on the `RawTextHelpFormatter` .

Our built-in commands use `RawTextHelpFormatter` only because much of our help text is separated into paragraphs.

**Comment by nfnfgo** [comment]
Got it, thanks for the clarification! I'll go ahead and specify a different formatter when I need automatic wrapping
