### ISSUE TITLE
After exiting ipy, readline tab-completion is broken when using gnureadline + Python 3.13

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#1357]
After exiting ipy ipython shell, prompt color and tab completion are messed up.

Tested on `3.0.0` branch with an example application and verified behavior is the same on the `master` branch.

Tested on macOS Sequoia 15.1 using Python 3.13.0. Used multiple different terminals and behavior was the same. 

The problem does *not* happen when using Python 3.12.7 on the exact same setup.

The problem does happen on Linux when using `gnureadline` + Python 3.13.

Hence the bug is specific to the combination of `gnureadline` + `Python 3.13` + `ipython`

**Comment by tleonhardt** [comment]
After much debugging by commenting out code, the code that breaks everything is:
```Python3
            from IPython import (  # type: ignore[import]
                start_ipython,
            )
```

**Comment by tleonhardt** [comment]
I verified this bug is also impacting the `master` branch

**Comment by tleonhardt** [comment]
This problem is *not* happening when using Python 3.12.7 with the exact same setup on macOS Sequoia 15.1 and testing on the `master` branch.

**Comment by tleonhardt** [comment]
I tested in a fresh Python 3.13 venv installed using `pipenv` on a minimal `python` Docker container and this problem does not exist.

Hence from existing testing, it is limited to the following combination:
- macOS
- Python 3.13
- gnureadline

It would be interesting to temporarily tweak our code to prefer using python-gnureadline on Linux and test there. I'm not sure if the bug is specific to macOS + Python 3.13 or gnureadline + Python 3.13

**Comment by tleonhardt** [comment]
I just verified in a minimal python Docker container that this bug happens on Linux when using Python 3.13 and `gnureadline`.  

Hence this bug is very specific to the combination of `gnureadline` + `Python 3.13`

**Comment by tleonhardt** [comment]
I used a cmd2 app with both `py` and `ipy` commands to inspect `sys.modules` after exiting ipy using py and found readline still points to gnureadline:
```Python
sys.modules['readline']
<module 'gnureadline' from '/Users/toddleonhardt/src/python/cmd2/.venv/lib/python3.13/site-packages/[gnureadline.cpython-313-darwin.so](http://gnureadline.cpython-313-darwin.so/)'>
```

**Comment by anselor** [comment]
Is this something gnureadline needs to fix?

**Comment by tleonhardt** [comment]
I'm not sure yet if the problem is fundamentally in `gnureadline`, `ipython`, or `readline` itself.  But I'm continuing to investigate with help from @kmvanbrunt .

We are also looking to see if there is a way we can recover from it.

**Comment by tleonhardt** [comment]
When it happens there are two side-effects visible to the user:
1. All tab-completion is broken and hitting tab just inserts a tab
2. Any color in the prompt is gone

**Comment by tleonhardt** [comment]
Executing `readline.parse_and_bind(self.completekey + ": complete")` right before returning from `ipy` didn't help.

Doing `from IPython import start_ipython` at the top of cmd2.py before importing anything from our custom cmd2 code does fix the problem. The only problem there is we have also said ipython is an optional dependency and this would make it a required one.  I guess we should wrap that in a try.

**Comment by tleonhardt** [comment]
8.2.13 is the first version of `gnureadline` to support Python 3.13, so I can't install an older version using Python 3.13

I did verify that version 8.2.13 of `gnureadline` doesn't have this problem when running with Python 3.12.7.
