### ISSUE TITLE
Cmd2 2.5.4 When a Custom Setting's onchange_cb Method is Used to Validate the Settable, Cmd2 Issues Misleading Output

### ISSUE THREAD

**Issue by eruber** [python-cmd2/cmd2#1378]
Any validation changes made to a settable inside the onchange_cb method are correctly reflected in the set command's output table; however, Cmd2's interactive output during the update of the settable emits the original set value rather than the validated value set in the onchange_cb method. 

Since the output from the onchange callback is before Cmd2's output, I was expecting the validated value to be used in Cmd2's output rather than the unvalidated value.

Here is an example output...

![Cmd2-Custom-Settable-Output](https://github.com/user-attachments/assets/f4716de1-e73a-445c-9cdb-a76c24d1ec26)

**Comment by kmvanbrunt** [comment]
A `Settable` has two parameters related to this behavior.

```Python
:param val_type: callable used to cast the string value from the command line into its proper type and
                 even validate its value. Setting this to bool provides tab completion for true/false and
                 validation using to_bool(). The val_type function should raise an exception if it fails.
                 This exception will be caught and printed by Cmd.do_set().

:param onchange_cb: optional function or method to call when the value of this settable is altered
                    by the set command. (e.g. onchange_cb=self.debug_changed)
```

The purpose of `val_type` is to validate and finalize the new value whereas the purpose of `onchange_cb` is to respond to the change. Basically `onchange_cb` is for handling anything affected by the settable's new value. This includes things like updating another state variable's value or logging that the settable changed.

What we're printing is the return from the `val_type` function.

To achieve the behavior you want, move your validation code to another function and pass it as the `val_type` parameter.
Something like the following:
```Python
def validate_emit_video_data(val: str) -> str:
    # Remove invalid characters
    sanitized_val = ...

    # Notify user of invalid characters
    self.perror("...")

    return sanitized_val 

self.add_settable(
    Settable('emit_video_data',
    validate_emit_video_data,
    'Video data to emit on search matches',
    self)
)
```

I still may be OK altering our code to print the settable's current value to handle cases where developers make changes to it in `onchange_cb`, but that was not the original intention for the on-change callback.
