### ISSUE TITLE
A serious problem

### ISSUE THREAD

**Issue by MrWQ** [python-cmd2/cmd2#1389]
Hello brother, I have discovered a serious issue. When there is a ">" in CMD2, it can cause a penetration effect. Writing files on the actual computer instead of the terminal simulated by CMD2, and using "../" can cause path traversal, allowing files to be written to any path. In some cases, it can cause file content replacement, such as writing the RSA public key to/root/. ssh/authorized_keys.

Please find attached the code and screenshots.

```
# -*- coding: utf-8 -*-
# @Time : 2024/12/5 18:09
# @Author : ordar
# @Project : aaaa
# @File : cmdddd.py
# @Python: 3.7.5
import cmd2

class SimpleCmdApp(cmd2.Cmd):
    """Simple command processor example using cmd2."""

    # 设置默认提示符
    prompt = '(simple_cmd) '

    def __init__(self):
        super().__init__()

    # 定义帮助信息
    def do_greet(self, args):
        """Greet the person."""
        print("Hello, " + args)

    # 定义退出命令
    def do_exit(self, arg):
        """Exit the application."""
        print('Exiting...')
        return True  # 返回 True 表示退出应用程序

    # 定义一个显示当前时间的命令
    def do_time(self, arg):
        """Display current time."""
        import datetime
        now = datetime.datetime.now()
        print(f"Current time is {now.strftime('%Y-%m-%d %H:%M:%S')}")

    def do_echo(self, args):
        """Echo the arguments back to the user.
        Usage: echo [message]
        """
        if args:
            print(args)
        else:
            print('')  # 如果没有提供参数，则只打印空行

    # 如果输入了不存在的命令，则打印错误信息
    def default(self, line):
        self.perror(f'Unknown command: {line}')
        self.do_help('')

if __name__ == '__main__':
    app = SimpleCmdApp()
    try:
        app.cmdloop()
    except KeyboardInterrupt:
        print("\nApplication interrupted.")

```

![image](https://github.com/user-attachments/assets/34dea1c2-3bde-421c-abf7-30e878ee7078)

**Comment by kotfu** [comment]
Thank you for sharing your sample code and this concern. Your issue description outlines a possible privilege escalation issue (i.e. a non-root user running `cmd2` is able to write files owned by root. However, your sample code and screenshot does not show any privilege escalation. It shows a user `kali` able to overwrite a file owned by user `kali` from within `cmd2`. If you ran the exact same command in the operating system shell:
```
$ echo "aasgagasgasasgasgaggs" > ../.ssh/auth_keys
```
the operating system shell would also happily overwrite the file. Similarly if you ran the following command within `cmd2` as user `kali`:
```
(simple_cmd) echo forged_key > /root/.ssh/authorized_keys
```
the command would fail with a permission denied error.

Here's the design principle for `cmd2`: it has exactly the same privileges as the operating system user that launched the `cmd2` based program. There is no provision in `cmd2` for either "blocking" or "enhancing" the privileges available via the operating system shell.

**Comment by tleonhardt** [comment]
@MrWQ cmd2 supports the ability to [disable redirection](https://cmd2.readthedocs.io/en/stable/features/redirection.html#disabling-redirection).

You can use this feature to disallow allow redirection within your cmd2 application.

**Comment by MrWQ** [comment]
Thank you for your answer, my question seems to have been resolved.
