### ISSUE TITLE
Missing Option to Prevent Processing of CLI Args

### ISSUE THREAD

**Issue by FedericoCeratto** [python-cmd2/cmd2#14]
Originally reported by: **Tyler Abair (Bitbucket: [tabair](http://bitbucket.org/tabair), GitHub: [tabair](http://github.com/tabair))**

---

Cmd2 has a cool feature where it will process all CLI args passed to a script as commands, but there is no option to turn this feature off.

A quick work-around that I'm using at the moment is to save sys.argv to a tmp variable, and then set sys.argv = [tmp[0]] just before calling Cmd.cmdloop() and restore it after, but it'd be much nicer if I could just set an instance variable on my Cmd object to turn this feature off instead.

---
- Bitbucket: https://bitbucket.org/catherinedevlin/cmd2/issue/14

**Comment by tleonhardt** [comment]
When we add this option, we should also do a tiny bit of refactoring so that preloop() and the intro message both run prior to the processing of CLI args.

**Comment by tleonhardt** [comment]
Fixed with PR #44
