### ISSUE TITLE
Missing Option to Disable Redirection and Piping

### ISSUE THREAD

**Issue by FedericoCeratto** [python-cmd2/cmd2#15]
Originally reported by: **Tyler Abair (Bitbucket: [tabair](http://bitbucket.org/tabair), GitHub: [tabair](http://github.com/tabair))**

---

Cmd2's redirection with '>' and piping with '|' is a terrific feature, but I really want to disable redirection and piping sometimes.  Unfortunately, there is no option I can set to make the '>' and '|' characters behave as plain characters.

I can't find a work-around to this without editing the source code.  I did find that setting Cmd.redirrector to a non-printable character like '0x03' will stop redirection, but I can't find any way to touch piping.  Furthermore, this is a TERRIBLE workaround to stop redirection, because a malicious user is capable of sending even non-printable characters through.

---
- Bitbucket: https://bitbucket.org/catherinedevlin/cmd2/issue/15

**Comment by tleonhardt** [comment]
@FedericoCeratto
So adding a settable boolean parameter or two to disable redirection and/or piping could potentially be easy.

Do you think it would be good enough to just ignore the > or | and everything that comes after it?  If so this fix/enhancement should be easy as we can just put the relevant function calls for redirecton/piping inside if statements.

But if disabling redirection means we have to treat the entire line as a command argument, that would require refactoring the pyparsing grammar which would be a much more difficult task.

**Comment by tleonhardt** [comment]
A boolean parameter was added in PR #45 that allows disabling redirection and piping.

It just ignores the > or | and everything after it on the command line and the output of the command goes to the screen as normal.  

If it is important to disable the special parsing of the characters, a new issue can be created.
