### ISSUE TITLE
Use of parse_args in cmdloop

### ISSUE THREAD

**Issue by FedericoCeratto** [python-cmd2/cmd2#16]
Originally reported by: **Bhairav Shah (Bitbucket: [bhairav](http://bitbucket.org/bhairav), GitHub: [bhairav](http://github.com/bhairav))**

---

In the cmdloop method, the following line is present:

```
#!python

(callopts, callargs) = parser.parse_args()
```

Digging deeper into optparse, parse_args() calls the below line:

```
#!python

rargs = self._get_args(args)
```

Which in turn has this:

```
#!python

    def _get_args(self, args):
        if args is None:
            return sys.argv[1:]
        else:
            return args[:]              # don't modify caller's list
```

While it may make sense for _get_args in optparse to use the sys.argv arguments, would it make sense for cmd2 to do the same?  Thinking that cmd2 doesn't need to allow reading from normal shell commandline because it is supposed to be an embedded interpreter within the program.

Wondering if cmdloop in cmd2 can be fixed in one of two ways:

1) To put an empty arg list to force _get_args to not use sys.argv:

```
#!python

(callopts, callargs) = parser.parse_args(args=[])
```

OR

2) To allow the program to put an empty list in cmdloop (though that might break compatibility with cmd:

```
#!python

cmdloop(args=[])
```

I tested with option 1, and was able to make my program work by not having it complain with the following kind of error:

<program> error: no such option: -f

Thanks.

---
- Bitbucket: https://bitbucket.org/catherinedevlin/cmd2/issue/16

**Comment by tleonhardt** [comment]
@bhairav
Being able to  send commands to your app as you invoke it by including them as extra arguments to the program on the command-line is very much an intentional feature of cmd2:
https://cmd2.readthedocs.io/en/latest/freefeatures.html#commands-at-invocation

If in your particular application you wish to disable this feature, you can set the "allow_cli_args" member to False.
