### ISSUE TITLE
self.select list out of index

### ISSUE THREAD

**Issue by FedericoCeratto** [python-cmd2/cmd2#17]
Originally reported by: **Anonymous**

---

When an option that is not in the list is inserted, say:
1. 90
2. 180
3. 360
   Select number of samples:11
   list index out of range

the operation is closed  because the list is out of index, it would be nicer to do nothing until a correct option is entered. 

---
- Bitbucket: https://bitbucket.org/catherinedevlin/cmd2/issue/17

**Comment by tleonhardt** [comment]
This was fixed in PR #46
