### ISSUE TITLE
cannot integrate cmd2 into event loops

### ISSUE THREAD

**Issue by FedericoCeratto** [python-cmd2/cmd2#19]
Originally reported by: **Michael Haberler (Bitbucket: [mhaberler](http://bitbucket.org/mhaberler), GitHub: [mhaberler](http://github.com/mhaberler))**

---

I wish there were a way to register cmd2 input with event loops like zmq.loop, asyncio, poll, gobject/gevent etc without occupying the main loop

the assumption cmd2 owns the inner loop of a program is very restrictive - even Gnu readline can be used from an event loop (C, not Python though)

using threading is an overkill for the purpose, and brings its own set of problems

---
- Bitbucket: https://bitbucket.org/catherinedevlin/cmd2/issue/19

**Comment by tleonhardt** [comment]
@mhaberler
Unfortunately I cannot see an easy way of making cmd2 NOT owning the inner loop of the main thread of its program.  Given that cmd2 inherits from cmd, that is just the way it is designed to work.

I believe most serious use cases for cmd2 involve the use of some sort of concurrency library (be it threading, multiprocess, greenlet, asyncio, or whatnot) for dealing with commands which do not block and can have data being asynchronously provided to the application.

If you have any ideas for how we could incorporate this feature, please let us know.

**Comment by tleonhardt** [comment]
Perhaps adding a simple example for using cmd2 with a background thread for asynchronous feedback would be helpful.

**Comment by tleonhardt** [comment]
After some more thought, cmd2 absolutely can be integrated into event loops.  We just haven't done a good job documenting how to do this or of providing and example for how to do it.

The basic gist of how to do this is:

`class Cmd2EventBased(cmd2.Cmd):
    ... your class code here ...

if __name__ == '__main__':
    app = Cmd2EventBased()
    app.preloop()

    # Do this within whatever event loop mechanism you wish to run a single command
    app.onecmd_plus_hooks("help history")

    app.postloop()
`

Recommend actions to resolve this issue:

1. Add a section on how to integrate cmd2 into event loops to the Sphinx documentation
2. Add an extremely basic code example for how to do this to the examples directory
