### ISSUE TITLE
Remove unused commands

### ISSUE THREAD

**Issue by vvalien** [python-cmd2/cmd2#194]
Would like a option to remove all the included commands that I don't need for instance with this simple example.

```
class NewConsole(Cmd):
    def __init__(self):
        self.prompt = '[>] '
        self.allow_cli_args = False
        Cmd.__init__(self, use_ipython=False)
        
    def do_simpletest(self, line):
        "Print simpletest"
        print("simpletest")
```

I by no means need all the rest of this stuff in the psudo shell, and would only like the ones I define.

```
Documented commands (type help <topic>):
========================================
_relative_load  edit  history  py        quit  save  shell      show
cmdenvironment  help  load     pyscript  run   set   shortcuts  simpletest
```

This might be possible already but I couldnt find a way to do it.

Thanks

**Comment by tleonhardt** [comment]
@vvalien Thanks for your good question.  It prompted me to add an new example "remove_unused.py".  What you want is already possible.  Code from new example is here:

```Python
import cmd2

class RemoveUnusedBuiltinCommands(cmd2.Cmd):
    """ Example cmd2 application where we remove some unused built-in commands."""

    def __init__(self):
        cmd2.Cmd.__init__(self)

        # To hide commands from displaying in the help menu, add their function name to the exclude_from_help list
        self.exclude_from_help.append('do__relative_load')

        # To remove built-in commands entirely, delete their "do_*" function from the cmd2.Cmd class
        del cmd2.Cmd.do_cmdenvironment

if __name__ == '__main__':
    app = RemoveUnusedBuiltinCommands()
    app.cmdloop()
```

You can hide commands from displaying in the help menu by adding them to the ``exclude_from_help`` list.  These commands will still exist, they just won't display in the main help menu.

You can remove unwanted commands entirely by using Python's built-in ``del``.

**Comment by aseemjakhar** [comment]
Hi,

In the latest version do_cmdenvironment has been removed. How does one entirely remove built-in commands now?

**Comment by tleonhardt** [comment]
Hi Aseem,

I'm not sure I understand your question.  Would you like to remove other built-in commands?  Or are you upset that we removed the ``cmdenvironment`` command?

In the latest version the functionality in the **cmdenvironment** command  got combined with the ``set`` command in the form of **set -a**.

If you wish to remove other built-in commands, look at the following example:
https://github.com/python-cmd2/cmd2/blob/master/examples/remove_unused.py
- Come to think of it I need to update this example now the ``do_cmdenvironment`` has been removed

**Comment by aseemjakhar** [comment]
Hi Todd,

Thanks for the quick response.
No, Im not upset :). My query is:
1. To remove all the builtin commands entirely, based on this example we could just del do_cmdenvironment.
2. Now that do_cmdenvironment is removed in the latest version of cmd2. I wanted to know if there is still an elegant way to remove all built-in commands, like a single method to disable all or something similar to the del do_cmdenvironment.
3. Preference would be to disable the commands instead of hiding them.

I hope this clarifies your doubts.

**Comment by tleonhardt** [comment]
Hi Aseem,

Thank you for clarifying you question.  

The previous example for removing a built-in command demonstrated how to remove a **single** command, in particular the **cmdenvironment** command.  There never has been a capability for automatically removing all built-in commands.

You can still remove built-in commands in the same manner.  Just replace the ``do_cmdenvironment`` with the appropriate **do_*** method in the example code above where we delete that specific command.

In the most recent 0.8.0 release, which is currently available via **pip** from PyPI, we significantly reduced the number of built-in commands.  If you do a **help** to view the help menu, it now looks like the following before you add your own commands:
```Bash
(Cmd) help 

Documented commands (type help <topic>):
========================================
edit  help  history  load  py  pyscript  quit  set  shell  shortcuts
```

**Comment by tleonhardt** [comment]
Issue #276 was created to remember to update the relevant example.

**Comment by aseemjakhar** [comment]
Hi Todd,

Thank you for the detailed reply. I just realized, I skipped part of the comments in the code. My bad. It clearly mentions del for each do_* to remove individual commands. The project Im working on, currently needs a command line interface only to execute custom commands and not explore any python/shell specific features. However, going forward I may think of using built-ins.

**Comment by nickwu241** [comment]
I googled how to disable commands from the help menu and got to this issue.
For anyone else looking, you can hide commands from being shown by updating `hidden_commands`

For example:
```
import cmd2

class MyShell(cmd2.Cmd):
    def __init__(self):
        cmd2.Cmd.__init__(self)
        self.hidden_commands += [
            'alias', 'edit', 'history', 'macro', 'py', 'run_pyscript', 'run_script', 'set', 'shell', 'shortcuts'
        ]
```

**Comment by kotfu** [comment]
We also now have documentation showing how to hide, remove, and disable commands available at https://cmd2.readthedocs.io/en/latest/features/disable_commands.html. The method @nickwu241 shows above hides commands from help, but they can still be run if the user knows the command exists. Disabling a command prevents a user from running it in addition to hiding it from help, with the added benefit that the command can be enabled by the developer at runtime. Removing a command makes it permanently unavailable.
