### ISSUE TITLE
cmd2 0.7.5 on python 3.5 bails out if EDITOR environment variable is not set

### ISSUE THREAD

**Issue by niwred** [python-cmd2/cmd2#199]
File "./wesadmin.py", line 3, in <module>
    from lib.admin_interpreter import AdminInterpreter
  File "/home/U805316/projects/wesadmin/lib/admin_interpreter.py", line 5, in <module>
    import cmd2
  File "/usr/lib/python3.5/site-packages/cmd2.py", line 386, in <module>
    class Cmd(cmd.Cmd):
  File "/usr/lib/python3.5/site-packages/cmd2.py", line 428, in Cmd
    if _which(editor):
  File "/usr/lib/python3.5/site-packages/cmd2.py", line 190, in _which
    editor_path = subprocess.check_output(['which', editor], stderr=subprocess.STDOUT).strip()
  File "/usr/lib64/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/site-packages/run/__init__.py", line 145, in __new__
    process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
  File "/usr/lib/python3.5/site-packages/run/__init__.py", line 121, in create_process
    shlex.split(command),
  File "/usr/lib64/python3.5/shlex.py", line 273, in split
    return list(lex)
  File "/usr/lib64/python3.5/shlex.py", line 263, in __next__
    token = self.get_token()
  File "/usr/lib64/python3.5/shlex.py", line 90, in get_token
    raw = self.read_token()
  File "/usr/lib64/python3.5/shlex.py", line 118, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'

**Comment by tleonhardt** [comment]
@niwred Thanks for the bug report.

I would appreciate some additional information so I can reproduce and fix this issue.   Most importantly, **what operating system** (name and version) did this occur on?  Secondly, what version of Python 3.5 (i.e. 3.5.3?  3.5.0?).

Is the original application which you encountered the bug in something you could share to help me quickly reproduce it?

Thanks in advance.  I appreciate you bringing this to our attention.

**Comment by niwred** [comment]
BTW: exact versions:

Python 3.5.3 on CentOS 7.3.1611 (Core)

Von: Erwin Richard
Gesendet: Dienstag, 8. August 2017 17:18
An: 'python-cmd2/cmd2' <reply@reply.github.com>
Betreff: AW: [python-cmd2/cmd2] cmd2 0.7.5 on python 3.5 bails out if EDITOR environment variable is not set (#199)

Hi Todd

Thanks for contacting me and thanks a lot for your work on this module!

I’m writing a little inhouse ops tool, basic Cmd2 usage but with a lot of dependencies on internal code
If the problem is not obvious I could try to extract only the relevant parts.

I’m developing on Windows under Python 3.6 with no Issues (editor = notepad)

Integration Test on CentOS 7.3 with Python 3.5:
If EDITOR environment variable is not set -> crash, if it is set, no problem.
AFAIK, his did not happen with version 0.7.0 of Cmd2.

Thanks and Regards
Erwin

Von: Todd Leonhardt [mailto:notifications@github.com]
Gesendet: Dienstag, 8. August 2017 15:12
An: python-cmd2/cmd2 <cmd2@noreply.github.com<mailto:cmd2@noreply.github.com>>
Cc: Erwin Richard <erwin.richard@octosoft.ch<mailto:erwin.richard@octosoft.ch>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: Re: [python-cmd2/cmd2] cmd2 0.7.5 on python 3.5 bails out if EDITOR environment variable is not set (#199)


@niwred<https://github.com/niwred> Thanks for the bug report.

I would appreciate some additional information so I can reproduce and fix this issue. Most importantly, what operating system (name and version) did this occur on? Secondly, what version of Python 3.5 (i.e. 3.5.3? 3.5.0?).

Is the original application which you encountered the bug in something you could share to help me quickly reproduce it?

Thanks in advance. I appreciate you bringing this to our attention.

**Comment by tleonhardt** [comment]
@niwred Thanks for the update on OS and Python versions.  

Is it just stock CentOS 7.3 with Python 3 and Python 3rd-party packages installed from the CentOS repos using yum?  With cmd2 installed with pip?

If so I'll create a CentOS VM later today and try to reproduce this issue.  

I've worked extensively on various versions of Debian and Ubuntu with Python installed both from apt-get repos and from Anaconda and have never encountered this issue regardless of whether the EDITOR environment variable is set or not.

**Comment by niwred** [comment]
see example in my prev. comment. 
I don't know exactly how the integration machine is set up it's not really under my control. cmd2 installed with pip.

**Comment by niwred** [comment]
@tleonhardt had a brief look at the code and seems to me that the problem stems from an unclean installation of python 3.5 on that system.  a simple

subprocess.check_output(['which','vi'])

produces the same error. so its not cmd2 related. 
Strange thing is that I didn't see any other problems with with testing my application so far. (and it uses quite a bunch of libraries). Sorry to have bothered you.

**Comment by tleonhardt** [comment]
@niwred Thanks for looking into this issue further and closing it once you verified it wasn't cmd2 related!

It is no bother at all.  I would much rather be made aware of a potential issue than not.  

Good luck to you.
