### ISSUE TITLE
feedback_to_output setting doesn't work

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#209]
Feedback always appears to be redirected into the captured output. Discovered on python3.6.

**Comment by kotfu** [comment]
I've forked the repo and am working on a test and a fix.

**Comment by tleonhardt** [comment]
Do you mean that messages printed with the **pfeedback** function are redirected regardless of the **feedback_to_output** setting?

If so then I think the **print** in that function should be replaced with **sys.stderr.write**.  But the **pfeedback** function is used very sparingly within the current code base - mostly for printing command timing if enabled via the appropriate setting, but also with save and run commands, but that's it - everything else goes through **poutput** which is very intentionally redirected.

**Comment by kotfu** [comment]
Correct. Messages printed with **pfeedback()** are redirected regardless of the **feedback_to_output** setting. I agree the fix is easy. The tests are taking me a bit more time.

**Comment by tleonhardt** [comment]
For tests like that the **capsys** fixture in pytest can be helpful.  Combined with a temp file maybe.

**Comment by tleonhardt** [comment]
@kotfu Thanks for bringing the issue to our attention.  Good catch.

**Comment by tleonhardt** [comment]
@kotfu So given that you are a user of ``cmd2`` who has at least played with the **feedback_to_output** feature a little bit, I would like your opinion on something.  I'm thinking of changing the default value of this setting to **False** because that seems to make more sense for use cases I might deal with.  What do you think?

**Comment by kotfu** [comment]
I think about this like I think about bash. stdout and stderr are different unless I specifically redirect them to the same spot. I think that feedback and output should be separate, unless I ask them to go together by setting **feedback_to_output** to true.

The flip side is that many users of cmd2 powered tools may not be as familiar with the unix shell. They may think that all output should go together. When output and feedback are both going to the tty, they look like they are going to the same place. When these users redirect output to a file, and the feedback doesn't go, they might be confused. But I can get over this objection, if they know how to redirect output to a file, they ought to be able to figure out that feedback is different than output.

So I would vote for changing the default value of **feedback_to_output** to false.

Which of course makes me think of a new feature 🤔 , it would be nice if there was a way to send feedback to output for just this one command, without having to change the setting. In bash I would do:

```
$ grep -R foo /etc >/tmp/foo.txt 2>&1
```

That syntax seems way to complex for this project, but if we could settle on the syntax, I would be interested in doing the work to make it happen.

**Comment by tleonhardt** [comment]
@kotfu 
Thanks for the feedback.  I think I will change **feedback_to_output** to default to False.  People familiar with Unix shells is our primary target audience.

@kmvanbrunt and I have previously discussed how it would be nice to be able to optionally redirect stderr in a manner similar to bash.  For a feature like this we could decide whether we want to just redirect the "feedback" which can optionally go to stdout or stderr based on that boolean or whether we redirect stderr.  Implementing the basic logic to do either in Python should be relatively easy.  The hard part is finding a good syntax which is intuitive and easy to use and also isn't too nuts to add to the current Pyparsing logic.  Honestly, I haven't learned pyparsing yet, so I have only made extremely minimal maintenance changes to that part of the code.

I think it would be a great feature.  If you are comfortable modifying the pyparsing code and have a good idea for the syntax it would be a nice addition.  I'd be happy to help work on it if you like.
