### ISSUE TITLE
Missing git tag for 0.6.8 release

### ISSUE THREAD

**Issue by felixonmars** [python-cmd2/cmd2#22]
It would be nice to keep them in sync :)

**Comment by nocarryr** [comment]
:+1:   Also, it would be very helpful to keep version info updated in `setup.py` (so `dependency_links` can be used for requirements in other projects)

**Comment by FedericoCeratto** [comment]
Tag added, thanks for the bug report.

**Comment by nocarryr** [comment]
Thanks!  You made my CI tests happy in Py3.5!
