### ISSUE TITLE
poutput() can not print a zero.

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#222]
Say you built an app which subclasses cmd2. Say you wanted to have an 'exit_code' command in your app which printed out the exit code of the last command processed. Say you wanted to output an exit code of zero, using the poutput() function. It won't print it.

Here's the poutput() function:

https://github.com/python-cmd2/cmd2/blob/5d5675bac5a8d431fbae1e12daf9b27ca4edfe91/cmd2.py#L588-L599

If msg evaluates to false, then nothing is output. An empty string, and a zero both evaluate to false.

Recommended fix:

```
if msg is not None:
```

**Comment by tleonhardt** [comment]
@kotfu 

The original intent of the **if msg** check was to make sure that **msg** is not an empty string and I was making use of the *Falsiness* of empty strings.  My underlying assumption was that **msg** was either of type **str** or something automatically convertible to **str** using **.format()**.  But I didn't think about non-string types which would be Falsy.

So I would recommend slightly modifying your recommended fix to something like the following:

```Python
if msg is not None and msg != '':
```

**Comment by tleonhardt** [comment]
@kotfu 
I'll go ahead and submit a PR for this shortly unless you are already working on it.

**Comment by kotfu** [comment]
Makes sense. The check for None and an empty string is better.
