### ISSUE TITLE
Issue with # character in command strings

### ISSUE THREAD

**Issue by sluser** [python-cmd2/cmd2#225]
Hello,
I recently upgraded my application from 0.6.7 to 0.7.7. This went smoothly with one exception. One one of my cmd2 application's test cases calls a command with a parameter including a '#' character. Previously, this worked fine, but with the new version, the test failed. I found that actually, any time a # appears in the command string, the # and all characters following it are stripped off. This is a change in behaviour.

I did have a quick look into the cmd2 source, and the obvious suspicious area is comment stripping. The question is, was the change in behaviour caused by a new bug, or a bug fix?

If it is the latter, it would be good to have way to disable this behaviour, as I have a need to have # characters in commands but do not need to support comments.

Unfortunately, I cannot share the application in question, but to illustrate the issue:

`Client: call command(arg="abc#def")

*** invalid syntax - 'call command (arg="abc ***

Client: call co#mmand(arg="abcdef")

*** invalid syntax - 'call co ***`

I verified that the truncated string is indeed what gets sent to my command class, i.e. it is being truncated before it reaches my application code.

**Comment by tleonhardt** [comment]
Hi @sluser,

``cmd2`` has always support usage of both C-style comments enclosed within **/*I */** and Python-style comments beginning with **#**.  This feature exists to support comments within scripts, but by necessity of keeping the parsing logic sane it is also supported directly at the command line.

Numerous stability changes were made in the 0.7 release to ensure that all supported features behave consistently across all supported operating systems and versions of Python.  Prior to the 0.7 release some features behaved inconsistently depending on the OS and version of Python.

The ``cmd2`` documentation on comments is located here:
http://cmd2.readthedocs.io/en/latest/freefeatures.html#comments

As mentioned in that documentation, you what the parser views as a comment is set by the ``commentGrammars`` attribute.  So if you have no need to support Python-style comments in your application, the simplest thing for you to do would be do disable them by adding code like the following to your app:

```Python
import pyparsing
import cmd2
from cmd2 import options, make_option

class ArgumentAndOptionPrinter(cmd2.Cmd):
    """ Example cmd2 application where we create commands that just print the arguments they are called with."""

    def __init__(self):
        # Only allow C-style comments embedded within /* ... */ and disallow Python-style comments
        self.commentGrammars = pyparsing.Or([pyparsing.cStyleComment])

        # Make sure to call the super class __init__ after setting commentGrammars
        cmd2.Cmd.__init__(self)

    def do_aprint(self, arg):
        """Print the argument string this basic command is called with."""
        print('aprint was called with argument: {!r}'.format(arg))

    @options([make_option('-p', '--piglatin', action="store_true", help="atinLay"),
              make_option('-s', '--shout', action="store_true", help="N00B EMULATION MODE"),
              make_option('-r', '--repeat', type="int", help="output [n] times")], arg_desc='positional_arg_string')
    def do_oprint(self, arg, opts=None):
        """Print the options and argument list this options command was called with."""
        print('oprint was called with the following\n\toptions: {!r}\n\targuments: {!r}'.format(opts, arg))

if __name__ == '__main__':
    app = ArgumentAndOptionPrinter()
    app.cmdloop()
```

Alternatively, a potentially simpler (trivial) solution is to make sure the **#** is enclosed within single quotes - that way the parser will treat it literally and not as a comment.

**Comment by tleonhardt** [comment]
I think I will add an example app in the **examples** directly similar to the one above to help demonstrate to users both how argument parsing works and how they can change what is considered a comment.

**Comment by sluser** [comment]
Thank you for taking the time to write that example, this is exactly what I need. I was actually still working from an old bookmark of the previous documentation and had neglected to see that there had been an overhaul. Thanks again.

**Comment by tleonhardt** [comment]
@sluser Your welcome!

If you haven't checked out the recent features, I'd highly recommend checking out the following features:

-  improved tab-completion for local file system paths (with functions you can re-use for your own commands)
- improved Python scripting with new ``pyscript`` command
- improved ability to pipe command output to shell commands
