### ISSUE TITLE
Documentation links to wrong issue tracker / repository

### ISSUE THREAD

**Issue by hukka** [python-cmd2/cmd2#23]
Pypi links to https://pythonhosted.org/cmd2/, which links to http://trac-hg.assembla.com/python-cmd2/report/1. The docs in this repository link to bitbucket. Assuming github is now the canonical place (at least it has the latest updates), it should be mentioned in the docs, and the pypi page should be updated.

If the bitbucket is still the canonical place, I think that should be mentioned in the main readme.

**Comment by FedericoCeratto** [comment]
The "Home Page" on https://pypi.python.org/pypi/cmd2 is set to this GH repo, where do you see pythonhosted?

**Comment by hukka** [comment]
Right above the home page:
Documentation: cmd2 package documentation

**Comment by tleonhardt** [comment]
This is fixed for the latest documentation.
