### ISSUE TITLE
can't use colorize

### ISSUE THREAD

**Issue by teto** [python-cmd2/cmd2#232]
Thanks for maintining cmd2, it s a great module. It took me a long time before moving from Cmd to Cmd2 but the transition was seamless and that's great.

colorize  works in terminal, Cmd2 shows errors in colors etc so I thought I would use it in my commands too, to colorize the prompt for instance but then I have

```

Traceback (most recent call last):
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 807, in main
    analyzer = MpTcpAnalyzer(config, **vars(args))
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 104, in __init__
    self.prompt = self.colorize("eqeq" , "blue")
  File "/nix/store/5cr9m9hyr5mpj38bgj1811kcs2zhs33c-python3.6-cmd2-0.7.7/lib/python3.6/site-packages/cmd2.py", line 639, in colorize
    if self.colors and (self.stdout == self.initial_stdout):
AttributeError: 'MpTcpAnalyzer' object has no attribute 'stdout'
```
with 
`class MpTcpAnalyzer(Cmd):`
What's the matter ? I use python 3.6

**Comment by tleonhardt** [comment]
@teto
Can you give me some more information regarding your test setup and specifically what you are doing.  What OS are you using (and version)?  If you have any example code you can share that I could use to reproduce the issue that would be most helpful.

Whatever the problem you are experiencing, it isn't a general problem which always occurs.  I use Python 3.6 as well.  The **python_scripting.py** in the cmd2 examples folder on GitHub is a good example of using ``colorize()`` to make the prompt print in color:
https://github.com/python-cmd2/cmd2/blob/master/examples/python_scripting.py

I just tested that example using Python 3.6 on macOS and it works great without any problems.

If you can get me some more information so I can reproduce and isolate the issue, then we'll get to the bottom of it!  Thanks for reporting it.

**Comment by teto** [comment]
realized file descriptors must have been setup by the constructor so I moved up the constructor call
 `super().__init__(completekey='tab', stdin=stdin)` and it fixed it. Thanks.
