### ISSUE TITLE
command aliases

### ISSUE THREAD

**Issue by teto** [python-cmd2/cmd2#233]
I want to have aliases for my commands with long names.
According to http://cmd2.readthedocs.io/en/latest/settingchanges.html?highlight=shortcuts, the doc advises to use
`Cmd2.shortcuts.update({'l': 'lift_subflows', 'l': 'list_reinjections'})` but here it generates an error
```
An error happened :
'list' object has no attribute 'update'
Displaying backtrace:

Traceback (most recent call last):
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 813, in main
    analyzer = MpTcpAnalyzer(config, **vars(args))
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 167, in __init__
    self.shortcuts.update({'l': 'lift_subflows', 'l': 'list_reinjections'})
AttributeError: 'list' object has no attribute 'update'

```
shortcuts seem to be a list of tuple instead of a dict. 
`[('@@', '_relative_load'), ('@', 'load'), ('?', 'help'), ('!', 'shell')]`

EDIT: a decorator to alias command could be neat too

**Comment by tleonhardt** [comment]
@teto 
The problem is that you need to update shortcuts before calling the super class ``__init__`` method.  You can't update them after that has been called. 

I will update the documentation to make this more clear.  

For now, I would recommend looking at this example:
https://github.com/python-cmd2/cmd2/blob/master/examples/example.py

**Comment by teto** [comment]
that was indeed the case. It's confusing for seemingly no reason (why change the datatype ?). Paired with https://github.com/python-cmd2/cmd2/issues/232, it means using cmd2 requires much attention on where to put each line. One before calling the constructor and one after. I believe it should stick to one or the other (most likely the first one). Or use decorators instead (looks sexy in my opinion but it might change too much of the implentation).

**Comment by tleonhardt** [comment]
I agree, it is confusing.  

However, there is an obscure yet valid reason for why it is done related to shortcut parsing logic and how shortcuts get sorted.  Suppose you define two shortcuts where one is a substring of the other, such as the built-in shortcuts ``@`` and ``@@``.  If you are not exquisitely careful about how you parse and sort the shortcuts you will end up with non-deterministic behavior.

So the way we do the logic is, suppose you have two shortcuts *a* and **ab**.  If you aren't careful about how shortcuts are processed, you might end up parsing "ab" as "shortcut a with argument b", which probably isn't what you want.

**Comment by tleonhardt** [comment]
I do really like the decorator idea for command aliases.  I'll give that some thought.

**Comment by teto** [comment]
I thought that the shortcuts injected new functions so in my example `shortcuts.update({'ls': 'list_subflows', 'l': 'list_reinjections'}) `would inject ` do_ls(**args): do_list_subflows(args)` but apparently you parse the command (maybe because python would refuse `do_@` xD). If order matters than the backend could use an OrderedDict instead ? or use another name than `shortcuts`, make shortcut a property to intercept new shortcuts and convert it to the backend system. This way it doesnt break the API. Sorry but Imy PR backlog is just too big at the moment.

**Comment by teto** [comment]
also it might be nice if "help <shortcut>" would work.
