### ISSUE TITLE
invoke several commands at startup while still allowing manual parsing 

### ISSUE THREAD

**Issue by teto** [python-cmd2/cmd2#234]
Coming from vanilla Cmd, I had some code similar to what allow_cli_args (http://cmd2.readthedocs.io/en/latest/freefeatures.html#commands-at-invocation) does yet I wanted to parse some flags at invocation.

What I did was
```
args, unknown_args = parser.parse_known_args(arguments)
...

        elif unknown_args:
            log.info("One-shot command(s) with unknown_args=  %s" % unknown_args)

            for cmd in unknown_args:
                analyzer.onecmd(cmd)
```
I wonder if I could turn allow_cli_args on while discarding the known flags beforehand ?

That was the last issue opened today. sorry I gathered some xD

**Comment by tleonhardt** [comment]
I imagine you could use **argparse** or whatnot to parse your know flags and then manually reconfigure what is present in ``sys.argv`` before calling ``cmdloop()`` on the ``cmd2`` instance.

**Comment by tleonhardt** [comment]
PR #236 modified argparse_example.py to do exactly what I think you were looking for:
https://github.com/python-cmd2/cmd2/blob/master/examples/argparse_example.py

If this doesn't answer your question, we can re-open this issue, but I'm going to close it for now.

**Comment by teto** [comment]
Sorry for the late thanks but thanks :D
