### ISSUE TITLE
Tab completion not work in win7

### ISSUE THREAD

**Issue by mikusjelly** [python-cmd2/cmd2#238]
In Linux it work.
In Win7, it just give me a space.

**Comment by tleonhardt** [comment]
HI @mikusjelly 

On Windows you need to install pyreadline, so do something like:

```Bash
pip install pyreadline
```

or

```Bash
conda install pyreadline
```

There is a note on the first page of the User Manual that mentions this:
http://cmd2.readthedocs.io/en/latest/

How would you recommend that I document this to make it clear for users?

**Comment by mikusjelly** [comment]
@tleonhardt Thank you very much. 

Maybe you can add **Note** to [installation](https://github.com/python-cmd2/cmd2/blob/master/README.md#installation).

**Comment by tleonhardt** [comment]
@mikusjelly 

I'm working on modifying the dependencies so that pip will view **pyreadline** as a dependency, but only on Windows.  If that doesn't work out, I'll make sure to add a good note.  

Thanks for the feedback.
