### ISSUE TITLE
Unit test failures in Python 3.7.0a3

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#244]
When running the ``pytest`` unit tests for ``cmd2`` with the alpha 3 development version of Python 3.7, there are 7 failures, all within the **test_parse_transcript_expected** test suite.

They all appear to be similar in nature, like the following:

```
AssertionError: assert 'use\\ 2/3\\ cup' == 'use\\ 2\\/3\\ cup'
E         - use\ 2/3\ cup
E         + use\ 2\/3\ cup
```

I have no idea if something changed in Python 3.7 which is causing these failures or if it is a change in pytest which is causing them.

**Comment by tleonhardt** [comment]
@kotfu If you have time, this would likely be a quick fix for you since you wrote these unit tests.

I verified the behavior with a version of Python 3.7.0a3 installed on my system after initially seeing it on Travis CI.

**Comment by kotfu** [comment]
I have also reproduced the errant behavior in 3.7.0a3. It appears that 3.7.0 has a change in behavior in the `re.escape()` method, which is causing the problem. I'll continue to investigate and get it resolved.

**Comment by tleonhardt** [comment]
The docs for 3.7 say this about **re.escape**:
“Changed in version 3.7: Only characters that can have special meaning in a regular expression are escaped.”
https://docs.python.org/3.7/library/re.html

**Comment by kotfu** [comment]
Just one more thought about this whole regular expression business. Regexes are like Perl: they are both write once, read never 😎 . I write that regex code, and wrote it recently, and it still took me forever to figure it out...again.

**Comment by tleonhardt** [comment]
Agree about regexes.  They are powerful, but I use them infrequently enough that it requires relearning except for the most basic cases.

A long term wish would be simplifying the transcript testing slightly somehow, particularly for chained regexes when there are multiple commands.  Maybe a modification that strips all trailing whitespace from the end of both the expected and actual before comparing?  Not sure how easy or hard that would be though.
