### ISSUE TITLE
Move read-only settings from cmdenvironment to set

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#251]
The **cmdenvironment** command outputs settings that the end user can not modify. This command is generally only useful to developers, and may be confusing to users.

Suggest modifying the set command to accept a **-a/--all** option. If you do **set --all** then you get the standard settings, and then a blank line, and then a line that says "Read only settings", and then the output of cmdenvironment. That way this information would still be available, but would be less confusing for end users because there would be no cmdenvironment command in help.

**Comment by tleonhardt** [comment]
When working this issue, it would probably be a good time to remove the **show** command since **set** without an argument provides the same functionality.  The implementation for **do_show** can remain, just as a private method which gets called by the appropriate branch within **do_set**.
