### ISSUE TITLE
Consider adding a feature to support submenus

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#256]
In some types of interactive command-line applications it is desirable to have stateful behavior where the commands available depend on the state and you effectively have sub-menus.

This should not be the "default" behavior in ``cmd2``.  But it would be nice to have it as an optional opt-in behavior through something like a decorator-based approach.

**Comment by tleonhardt** [comment]
Early discussions related to this feature started in Issue #71 about support for sub-commands.

**Comment by lobocv** [comment]
I have a decorator based approach that has zero code changes to the Cmd class. However, it is not developed by me so I will need to ask permission before I make any PR.

**Comment by tleonhardt** [comment]
I look forward to a PR from you and/or your colleague.  A decorator-based approach with zero code changes to the Cmd class sounds perfect!  Thanks.
