### ISSUE TITLE
Discontinuing support for Python 2.7 on April 15, 2018

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#260]
Supporting multiple old versions of Python is becoming more and more burdensome as good features get added to newer versions of Python which don't get back-ported to older versions.

I don't want to abandon support for versions of Python that users are actively using.  But I also don't want to waste developer time supporting versions nobody cares about.

So whoever reads this, please feel free to add a comment and say what versions of Python you care about ``cmd2`` supporting now and in the near future.

**Comment by tleonhardt** [comment]
I only care about Python 3.5, 3.6, and 3.7 at this time.  Supporting each of those versions is important to me for the foreseeable future.

**Comment by kotfu** [comment]
3.4+ for me, although I could be persuaded to discontinue support for 3.4.

As an only partially relevant data point, the [Requests](http://docs.python-requests.org/en/master/) library supports 2.6, 2.7, 3.4, 3.5, 3.6 and 3.7.

**Comment by tleonhardt** [comment]
@kotfu Last night I merged in a change where for Python 3.4 and earlier there is now an additional dependency on ``contextlib2``.  Does that affect you negatively at all?  I hope not.  This was in pursuit of having "help" provide output to stdout for commands using one of the argparse decorators.  For 3.5+ all the good stuff in ``contextlib2`` got merged into the built-in ``contextlib``.

What do you think a reasonable policy would be for announcing an end-of-life for ``cmd`` supporting Python 2.7 for new releases?  Would you prefer it to be based on date (i.e. something like Dec. 31, 2018) or release (i.e. something like 0.8.x)?

Regardless, I would like to somehow give some sort of notice that support will be ending for Python 2.7 in the not-too-distant future and end users know what they can expect.  Of course, older versions of ``cmd2`` could still be used with Python 2.7, we just won't be supporting it in newer versions.

**Comment by kotfu** [comment]
The additional `contextlib2` dependency is no problem for me.

I think we should choose some date when we will no longer be supporting python 2.x. On that date, we make a new release (i.e. 0.12.0 or whatever) that does not run tests against python 2.x and which states that there is no support for python 2.x. Then we can begin cleaning up the 2.x cruft, like the `six` library and the `contextlib2` thing you just added.

**Comment by tleonhardt** [comment]
Ok, I like the date-based approach?  When do you think a good date would be?  The latest I would want it to be would be the end of 2018.  But I would be happy with earlier in the year.  I look forward to cleaning up the codebase by removing the 2.x cruft.  And I would love to start being able to use optional type hints for arguments and return values.

**Comment by kotfu** [comment]
What about end of summer? We give ~ 6 months notice and discontinue support for Python 2.x on Aug 31, 2018.

**Comment by tleonhardt** [comment]
@kotfu What would you think about moving the date we stop supporting Python 2.7 up a little bit so it happens sooner?  I've received multiple complaints from other ``cmd2`` developers that continuing to support Python 2.7 is a significant burden.  Maybe May 31, 2018 or April 30, 2018 could be a possibility?

**Comment by kotfu** [comment]
I stopped supporting python 2 in my own projects almost 5 years ago. I have no problem accelerating the date when we stop supporting python 2.7. 

There are clearly a handful of contributors that would like to stop doing the extra work to support python 2. We may cause some inconvenience for other users of `cmd2` by accelerating the date when we drop support for python 2. It's not like `cmd2` will stop working, they just won't be able to access newer features. I say the risk is with the benefit. Let's move the date up.

**Comment by tleonhardt** [comment]
Ok, I think all active developers are in unanimous agreement that the sooner we stop supporting Python 2, then the easier it is for us to focus on making ``cmd2`` better.

Since supporting Python 2 has essentially been an extra tax on our developers, so as long as nobody objects lets say that April 15, 2018 (USA Tax Day) is the last day that Python 2 will officially be supported.

**Comment by tleonhardt** [comment]
Are there any outstanding features which will be completed in the near term that anyone would like to get into a final Python 2 release? 

If so, we can plan to do an 0.8.5 release on April 15, 2018.  If not, then we can stick with the 0.8.4 release as the final Python 2.7 release.

**Comment by tleonhardt** [comment]
So tentatively, I think we should make the first Python 3 only release 0.9.0 and we should tag the codebase before that with a "Python2" tag and perhaps leave a "Python2" branch around for awhile in case we find any really bad bugs and want to put out a 0.8.x bug release fix for Python 2.

**Comment by kotfu** [comment]
That’s how I did it for my own projects. So we would say the 0.8.x series is the last one that supports python 2. We branch 0.8.4 (or 0.8.5 depending on if we create it or not) and leave it around, maybe indefinitely. That way we can easily produce an additional 0.8.6 release should the need arise.

0.9.0 and forward would only support python 3.

I have nothing outstanding that I think needs to be in the final python 2 release.

**Comment by tleonhardt** [comment]
0.8.5 has been released to PyPI and on GitHub.  

A **python2** branch has been created to facilitate Python 2 bug fix releases in the 0.8.x line and the version on this branch has been bumped to 0.8.6.

The version in the **delete_optparse** branch has been bumped to 0.9.0 and that related PR should merge into master soon.

The cleanup work can begin soon.
