### ISSUE TITLE
Has cmd2 completely dropped support for optparse?

### ISSUE THREAD

**Issue by xNinjaKittyx** [python-cmd2/cmd2#262]
I was unaware that argparse support was released, and it seems like optparse isn't usable anymore either.

The docs say that optparse is deprecated (not removed), but when I try to do 
`from cmd2 import make_option`

I get ImportError

So, is optparse support completely gone?

Edit: This is version 0.8.0 For now, I've just downgrade my cmd2 to 0.7.9 to make it work.
Still the 0.8.0 docs should be fixed to say that optparse is no longer supported if it's completely dropped.

**Comment by tleonhardt** [comment]
@xNinjaKittyx ``argparse`` support was added in the 0.8.0 release which came out early this morning.  In that same release ``optparse`` support was officially deprecated, but not yet removed.

If you wish to continue to use ``optparse`` with the current ``cmd2`` release, then you simply need to import **make_option** directly from ``optarse``:

```Python
from optparse import make_option
```

We did cover this caveat in the CHANGELOG.  If you have a suggestion regarding how we could better document this to make it clearer to users, then I would appreciate it.

Thanks for bringing the issue up.

**Comment by xNinjaKittyx** [comment]
I see. Thanks for the clarification. I've already started to port my code to argparse.
Also it makes a lot of sense to change that import statement to force users to realize that it will be removed eventually. (However, I think print statements could also be helpful in those deprecated files to constantly warn users that it'll be deprecated soon.)

I think the docs could be more clear by at least including 1 example of how the imports look like.

I didn't even know from where to import `with_argparse`, but I just assumed that it would be from `cmd2`, and imported from there.

Examples are great, but I think linking them to the docs would make it more user-friendly as well.

**Comment by tleonhardt** [comment]
Thanks for the feedback.  

I don't want to put in nagging print statements warning users about the ``optparse`` deprecation, at least not yet.

But I will try to make the docs more clear.

**Comment by tleonhardt** [comment]
@xNinjaKittyx I submitted PR #263 to help improve the clarity of the docs in relation to this issue.  Please feel free to comment on that PR if you have further suggestions for improvement and/or to let us know if you think those changes are sufficient to clearly communicate the changes in this release.

Hopefully you are finding porting your ``cmd2`` application code to use the new argparse-based decorators to be a relatively easy process.

**Comment by xNinjaKittyx** [comment]
Looks good!

Yeah I was able to switch over to argparse fairly easily. The only mildly annoying thing is setting up all the parent ArgumentParsers rather than just having make_options assigned to variables and customizing each options parser.

**Comment by tleonhardt** [comment]
We tried hard to find a way to provide something equivalent to **make_option** from ``optparse`` and we couldn't figure out how to do it for ``argparse``.  Their APIs are so close to being compatible, but not quite.

Thanks again for your feedback.
