### ISSUE TITLE
add a 'do_xxx' method to the cmd2 object?

### ISSUE THREAD

**Issue by mgiaco** [python-cmd2/cmd2#267]
Hi, 
Is there a way to extend a Cmd2 object with a custom "do_xxx" method?  I would like to add some "do_xxx" method´s after I have already initialized the object.
```` python
c = Cmd()
c.append("do_xxx")
```
thx

**Comment by tleonhardt** [comment]
Extending a Cmd2 object with a custom ``do_xxx`` method is trivial if you do it **before** you initialize the instance of the object:

```Python
from cmd2 import Cmd

def do_xxx(self, arg):
    """Help for xxx command."""
    print('Hello from xxx')

if __name__ == '__main__':
    Cmd.do_xxx = do_xxx
    app = Cmd()
    app.cmdloop()
```

It is also trivial to extend a Cmd2 object with a custom method **after** you initialize the object **if you don't care about that method appearing in the help menu**:

```Python
    import types
    app = Cmd()
    app.do_xxx = types.MethodType(do_xxx, app)
    app.keywords += 'xxx'
    app.cmdloop()
```

With that code, running the **xxx** command will work and getting help on it with **help xxx** will also work, but if you just do **help** you won't see ``xxx`` in the menu.

If you actually want to extend i with a custom do_xxx method at runtime **and** see that command appear in the help menu, then you would probably need to override the ``cmd.get_names()`` method from the built-in ``cmd`` module which ``cmd2`` extends.  You would need to override it in your custom class which derives from ``cmd2.Cmd``.

**Comment by tleonhardt** [comment]
The entire implementation for **get_names** is:
```Python
    def get_names(self):
        return dir(self.__class__)
```

So if there is some way to get the method dynamically added at runtime to show up in a **dir** for the class, then you wouldn't need to override this method.

**Comment by mgiaco** [comment]
Hi @tleonhardt, as always many thanks for the great answer.  I made a short example and it works for me. Do you see anything I could do in a more pythonic way?

```python

import abc
import inspect

from cmd2 import Cmd


class Base(metaclass=abc.ABCMeta):
    def get_do_functions(self):
        return_list = []
        for name, func in inspect.getmembers(self, predicate=inspect.ismethod):
            if name.startswith("do_"):
                return_list.append((name, func))
        return return_list


class A(Base):

    def __init__(self, a):
        self.a = a

    def do_fa(self, args):
        print("hello from class A fa with args: % and instance var a: %", args, self.a)


class B(Base):

    def __init__(self, b):
        self.b = b
        self.b1 = b * 2

    def do_fb(self, args):
        print("hello from class B fb with args: % and instance var b: %", args, self.b)

    def do_fb1(self, args):
        print("hello from class B fb1 with args: % and instance var b: %", args, self.b1)


class C(Base):

    def __init__(self, c):
        self.c = c

    def do_func_c_long_name(self, args):
        print("hello from class C fc with args: % and instance var c: %", args, self.c)

    do_fc = do_func_c_long_name


def append_do_methods(object_to_inspect, cmd_object):
    for func in object_to_inspect.get_do_functions():
        setattr(cmd_object, func[0], func[1])


if __name__ == '__main__':
    obj_a = A(1)
    obj_b = B(2)
    obj_c = C(3)

    append_do_methods(obj_a, Cmd)
    append_do_methods(obj_b, Cmd)
    append_do_methods(obj_c, Cmd)

    app = Cmd()
    app.cmdloop()

```

thx
mathias

**Comment by tleonhardt** [comment]
What you are doing looks fine to me.  If dynamically adding **do_*** command methods at runtime is a feature multiple end users want, then we could add a method in the ``cmd2.Cmd`` class to better support this.  But so far you are the first user who has mentioned wanting something like this.

**Comment by mgiaco** [comment]
many thanks, works great

**Comment by xNinjaKittyx** [comment]
Is there an easy way to combine Cmd Subclasses together?

I would like to have multiple Cmd Subclasses (so they can access commands like poutput/perror) and combine them together.

**Comment by tleonhardt** [comment]
Hey Daniel,

In the latest version of Cmd2 you can use the SubMenu feature to combine
multiple Cmd subclasses into a menu-based hierarchy.


Hope hat helps,

Todd

**Comment by tleonhardt** [comment]
@xNinjaKittyx A lot has changed!  Since the original post, we created a plugin framework for ``cmd2`` and moved the SubMenu functionality to the following cmd2 plugin package:  https://github.com/python-cmd2/cmd2-submenu
