### ISSUE TITLE
Multiple decorators breaks help on subcommands

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#271]
Make the attached modifications to [examples/subcommands.py](https://github.com/python-cmd2/cmd2/files/1715319/subcommands.txt). I added a simple decorator, which I then added to `do_base()`. With the additional decorator, the `help` command does not behave as expected.

`help base` yields:

```
usage: nimal_decorator [-h] {foo,bar} ...

Base command help

optional arguments:
  -h, --help  show this help message and exit

subcommands:
  {foo,bar}   subcommand help
    foo       foo help
    bar       bar help
```

Notice the incorrect and mangled command name on the first line.

If you switch the order of the decorators on `do_base()`, i.e. so `@minimal_decorator` is first, instead of second, `help base` now behaves properly, but `help base foo` and `help base bar` are not recognized, they return the same thing as `help base`.

**Comment by tleonhardt** [comment]
Hmm .. this one seems like it might be tricky to fix.  Do you have any good ideas?  

Getting the help to work correctly for subcommands at all was a pain, in part because I couldn't find a way to query an ``argparse.ArgumentParser`` to get access to its subparsers - it was easy to find out if it hand any subparsers, but not to get access to them.

**Comment by kotfu** [comment]
I haven't even looked at the help code yet, I'll try and take a peek tomorrow.

**Comment by kotfu** [comment]
Yikes. I'm not sure the current implementation can be modified to solve this problem. I can't think of a way to make the `__dict__['has_parser']` bits work when there could be multiple decorators and those decorators could be in any order. We may have to try and think of an alternative design pattern, like some class method which you call to register your arg parser where you pass the arg parser and the method the arg parser should be applied to.

Still thinking about this one... but totally agree that this might be tricky to fix.

**Comment by tleonhardt** [comment]
I'm not sure, but I think that using the [functools.wraps](https://docs.python.org/3.6/library/functools.html) helper in our decorators to carry over the metadata from the undecorated method may solve a lot of problems for us.

**Comment by kotfu** [comment]
Didn't know about `functools`, looks super useful. `functools.wraps` could solve the problem, but it won't work if you want to use a decorator from another 3rd party package.

**Comment by tleonhardt** [comment]
#283 closes this
