### ISSUE TITLE
SubMenu `shared_attributes` behaviour

### ISSUE THREAD

**Issue by albertored** [python-cmd2/cmd2#303]
The current behaviour for `shared_attributes` in submenus is to copy attributes from parent on entering command loop and then reset original child attributes on exit loop.

Is there a reason for this?

I was expecting to have shared attributes modified on child to be copied back to parent on child loop exit in order to preserve the change.

What do you think? Maybe this behaviour can be conditioned to some arguments of init method of `AddSubMenu`?

**Comment by tleonhardt** [comment]
Honestly I haven't used the submenu feature yet and I'm not sure if there is a good reason for why the ``shared_attributes`` behave like they do.  My guess would be that it met the needs of the people who designed this feature.

@lobocv Is one of the folks who designed this feature.  Calvin, can you speak to why it is implemented like that?

Regardless, I think it would be reasonable to condition the behavior on an argument to the init method of ``AddSubMenu``, particularly if the default behavior is like the current one.  Please feel free to submit a PR to add this if it would be useful for you.  

And if you do that and feel up to the task, if you wanted to add some more unit tests related to the submenu feature that would be awesome ;-)  Issue #268 was previously created for that purpose.

**Comment by albertored** [comment]
Ok, it sounds good to me.

Just to add more info I explain the use case I'm working on.

Suppose you have a main `Cmd` class with a submenu. I would like to be able to set some options (like `debug` and `colors`) globally in my application so I put them in the `shared_attributes` dict argument of `AddSubMenu`. In this way if a user changes one option in the main app and then it enters the submenu the option is correctly set also there. The problem arises in doing the opposite, i.e. setting the option in the submenu and then going back to main app.

**Comment by lobocv** [comment]
I'm fine with changing the behaviour to make it apply the changes to the parent. That actually seems logical otherwise it's basically read-only. Care will have to be made for anything non-mutable such as lists.

**Comment by tleonhardt** [comment]
I believe this issue was closed by PR #306.

@albertored Feel free to re-open this issue if there was more work you want to do with it.
