### ISSUE TITLE
Tab Completion of Paths

### ISSUE THREAD

**Issue by cornerpirate** [python-cmd2/cmd2#341]
Firstly I love cmd2. I have been trying to get tab completion of paths to work. On a Linux environment. I am getting this error below trying to follow the code shown at PyCon Florida:

`AttributeError: class Cmd has no attribute 'path_complete'`

Same error on Python 2.7 and 3 both of which have "cmd2" installed via pip and pip3 respectively.

The source I managed to get from the talk is as below (with foo replaced to be even more trivial):

```
import cmd2

class MyApp(cmd2.Cmd):
    """
    My example app
    """

    def __init__(self):
        cmd2.Cmd.__init__(self)

    def do_foo(self, args):
        """
        This prints out foo
        """
        print("foo")

    complete_foo = cmd2.Cmd.path_complete

if __name__ == '__main__':
    app = MyApp()
    app.cmdloop()
```
Hoping that it is just me being bad at typing but I haven't found code where "path_complete" is publicly available using Google. Or in the "/examples" folder yet.

**Comment by tleonhardt** [comment]
Hey @cornerpirate,

Recently @kmvanbrunt has been working on a lot of improvements to tab completion to handle things like tab completing paths with a space in it (and automatically adding quotes for you).

In the process of his refactoring, in the 0.8.2 release he made an architectural change where things like ``path_complete`` got converted from a method within ``cmd2.Cmd`` to a function outside of that class.

But in the latest code he changed his mind about what the best architecture would be and reverted to the way it was before.

We should put out an 0.8.3 release soon.

@kmvanbrunt We really should put out an 0.8.3 release soon.  This is the 2nd issue report we have received for this exact issue.  Putting out the new release will alleviate any confusion.

**Comment by cornerpirate** [comment]
Thanks for the reply to this. There is now a working solution at least documented if people are hitting the error in this thread. So it is not currently pausing people I hope.

I have to say that I haven't had too many problems apart from that with the library in use today. Knocked out about 3 useful sub-commands with tab completion as required today.

**Comment by tleonhardt** [comment]
We are glad you are finding ``cmd2`` easy to use ;-)

@kmvanbrunt Just put out the 0.8.3 release to PyPI which has the same code as the latest in GitHub.
