### ISSUE TITLE
Optional Formatting of Help Output

### ISSUE THREAD

**Issue by cornerpirate** [python-cmd2/cmd2#342]
Is there an option to control the formatting of commands displayed by the "help" command? By default it lists documented and undocumented commands as categories. What I would like to do is introduce categories. 

So all the commands provided by cmd2 are clearly shown, and then all of my "do_*" functions are clearly identified separately. Am I just missing something in the documentation here or is this a new feature request?

Thanks

**Comment by tleonhardt** [comment]
@cornerpirate I think what you are requesting duplicates Issue #278.  Can you take a look and verify if that sounds like what you are looking for?

We currently don't have a way of separating documented commands into separate lists, but it is a good idea for a feature and one we are considering adding soon-ish.

**Comment by cornerpirate** [comment]
Can 100% confirm that #278 is describing this. 

Close the ticket and dance that you have a plan?
