### ISSUE TITLE
Convert to a package directory structure

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#356]
``cmd2`` has grown to the point where the **cmd2.py** file is over 4000 lines and with new features being added the overall code size is likely to grow substantially.

It has probably reached the point that ``cmd2`` would benefit by becoming a real Python package with multiple source code files.

For this to happen, we will need a **cmd2** directory in which all of the source code lives and there is a dunder init.py file to make it a package.  This article on [Structuring Your Project](http://docs.python-guide.org/en/latest/writing/structure/) has good basic advice on how to approach this.

**Comment by kotfu** [comment]
I like this idea a lot. If we head this direction, I'd recommend we put the parsing classes in a separate file too. They are already separate classes in `cmd2.py`.

**Comment by tleonhardt** [comment]
@kotfu Good call.  I'm not very familiar with making Python packages, are you?

What will the implications be for **setup.py** and the unit tests, for example?

**Comment by kotfu** [comment]
There seems to be no standard best practice for this, but here's how I've done it:

```
cmd2
| cmd2
| | __init__.py
| | cmd2.py
| tests
| |  __init__.py
| | test_cmd2.py
| | test_completion.py
| setup.py
| pytest.ini
| tox.ini
```

So inside the `cmd2` source code there are two packages, one called `cmd2` and another called `tests`. A few minor tweaks to `pytest.ini` and `setup.py` and we are in business.

**Comment by tleonhardt** [comment]
@kotfu I am hesitant to ask you to do anything which will distract you from the ``shlex`` work, but if this is something you think you could knock out in a few minutes, would you like to take a crack at it?

**Comment by kotfu** [comment]
On it.

**Comment by anselor** [comment]
Everyone that's using Cmd2 is probably doing:
  from Cmd2 import Cmd

We probably need something like this in __init__.py:
  from Cmd2 import Cmd

That way when they import from the new Cmd2 directory it'll provide Cmd in the location they expect.

Otherwise everything will break for everyone when we release the next version.

**Comment by anselor** [comment]
Ok, just looked at your branch and looks like you're already on top of this.

**Comment by kotfu** [comment]
The *package* branch is mostly working now. There are lots of functions and static variables that aren't part of a class, so the `__init__.py` file is pretty messy, but that's probably OK. I haven't tried building a package, and this would need lots more testing before merging, but it's a start. I guess we need to decide if we really wanna do this now; if so, let's get this finished up and merge it.

**Comment by tleonhardt** [comment]
I think now is a good time to convert to a multi-file package. 

The 0.9.0 release is going to be a major release with huge backwards incompatible changes.  So I feel like we might was well just rip that bandaid off now.  Given that now is when we have given up supporting Python 2.7 in interests of supporting enhanced ability to refactor and add new features, it feels like an appropriate time.  And I think as we add features to ``cmd2`` it would eventually become inevitable that we would want to split it into multiple files.

Also @anselor looks to be nearly done with the AutoCompleter features which adds over another 800 lines of source.

**Comment by kmvanbrunt** [comment]
Since everyone's so excited to introduce "huge backwards incompatible changes", I'd like to chime in that I still think submenus should be a third party thing since no one stuck around to maintain them or write more unit tests.

**Comment by tleonhardt** [comment]
@kmvanbrunt 
Does the existence of the SubMenu feature significantly detract from the maintainability of ``cmd2``?  If so, then I could see an argument for removing it.

While I haven't used the SubMenu feature myself and I am disappointed better unit tests and comments didn't get added, I do think it is a pretty cool feature that I can see being useful for a certain subset of users.

My personal preferences align with the Zen of Python and "flat is better than nested" so I prefer interactive command line applications where all functionality is exposed at the top level as opposed to a menu-driven stateful system.  However, I know some people like menu-based systems and that feature enables designing that sort of application in a relatively easy and straightforward manner.

**Comment by tleonhardt** [comment]
As a potential aside if we do decide at some point to remove certain features from the core of ``cmd2`, we have the overall **python-cmd2** GitHub organization which we could create an additional repository underneath for for ``cmd2_extras`` or something similar.

**Comment by tleonhardt** [comment]
@kotfu I pushed a few small changes to the *package* branch and everything appears to be working now, or at least all of the unit tests are passing both on my machine locally and on both CI systems.

**Comment by kotfu** [comment]
I'd like to take a closer look at the stuff that's currently in `__init__.py`. I put a lot of things in there because it was an easy way to make the unit tests pass, but many of those things only need to be exposed for unit testing. Those items can/should be imported directly in the unit test.

**Comment by tleonhardt** [comment]
I did a lot of cleanup of ``__init__.py`` in this [commit](https://github.com/python-cmd2/cmd2/commit/9697bf1858c6ef06e13bdfd3dfaea6d0376d9a6a).

I moved all the stuff that was there only to make the unit tests pass out and converted those to be direct imports from ``cmd2.cmd2.<foo>`` within the relevant unit tests.

I think I will go ahead and create a PR.  You can do review it and make any changes you like.
