### ISSUE TITLE
Fix ReadTheDocs build of Sphinx docs

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#357]
By default [ReadTheDocs](https://readthedocs.org) builds the [cmd2 documentation](http://cmd2.readthedocs.io) using Python 2.  

Given that the version of ``cmd2`` on the **master** branch no longer supports Python 2, the *automethod* feature of Sphinx isn't working right now.

So fixing this probably consists of figuring out how to configure ReadTheDocs to build the ``cmd2`` documentation using Python 3.

**Comment by kotfu** [comment]
Whoever has admin access to these docs on https://readthedocs.org (the administrative site for readthedocs.io), needs to log in and go to the "Advanced Settings" page and change the python interpreter from "CPython 2.x" to "CPython 3.x".

**Comment by tleonhardt** [comment]
I have enough access where I can view the build logs, but not enough where I can change the settings for the build.

@FedericoCeratto 
Federico, could you please change the build settings for ``cmd2`` on ReadTheDocs to build with Python 3 instead of Python 2?  Alternatively, could you grand me admin privileges for the ``cmd2`` project on ReadTheDocs?

**Comment by tleonhardt** [comment]
Ok, I have Admin rights for the cmd2 project on ReadTheDocs now and I changed the build to use Python 3 and kicked off a new build.

**Comment by tleonhardt** [comment]
The latest commit to master fixed the Python3 ReadTheDocs build of Sphinx by removing Python 2 backports from the list of packages that get installed before the build.

The docs now look good again with method info auto-populated.
