### ISSUE TITLE
Batch mode and exit on error with code not 0

### ISSUE THREAD

**Issue by albertored** [python-cmd2/cmd2#358]
I need to be able to perform one or more commands directly from CLI call and exit on finish. I've resolved this need overriding the `onecmd_plus_hooks` method of my `Cmd` class to return `True` in some circumstances and adding a flag to the CLI to set the batch mode:

```python
def onecmd_plus_hooks(self, line):
    stop = Cmd.onecmd_plus_hooks(self, line)
   
    if self.mode == self.MODE_BATCH:
        # if there are commands in queue we exec all before stopping
        if self.cmdqueue:
            return stop
        # queue is empty and we are in batch mode, exit
        return True
    else:
        return stop           
```
(This works pretty well so if you think is useful I can try to integrate it in the package)

There is a problem anyway... The expected behaviour of a CLI call in batch mode is that the exit code of the whole call is 0 if the command is successful and different from zero if there are exceptions in command execution or if the user press CTRL+C during the execution.

With the current implementation the command always exits with a 0 code. I'm a bit stuck on how to implement this behaviour. I'm trying modifying a little bit the exceptions handling in `onecmd_plus_hooks`  and `_cmdloop` methods but I don't know if it is the correct way to get a solution. Do you have any comment/suggestion?

If you think is worth I can push a branch with my attempt

**Comment by albertored** [comment]
Thanks @tleonhardt for your reply, nice think that of using `quit` for batch processing!

For  what regards the exit code my use case is calling the cli in some script and being able to catch failures. Using `postloop` seems a lot verbose, the only way I can think of is surrounding all my commands with `try` statements, setting some class attribute in exceptions and use that in `postloop` for exiting with a non-zero code. It also seems not easy to handle exiting with non-zero code on sigint.

I'm pushing a PR with a generic way of solving this, it seems to work but it still under development (some tests are failing). It is not related to the piece of code for handling batch mode that I've shared before. You can take a look and let me know what you think.

Thanks

**Comment by tleonhardt** [comment]
As far as returning an exit code, maybe you just need to change **cmdloop()** so that it saves the return value of **_cmdloop()**.

But I'm curious to see what you come up with.  I'll take a look at your PR.  Thanks.

**Comment by tleonhardt** [comment]
The is some good discussion in PR #359 in relation to this issue.

I think the tentative resolution is that we will leave this issue open and revisit it after Issue #37 is complete and ``cmd2``'s underlying parsing logic has been refactored.

We agree that some sort of standard way of returning a non-zero exit code to the shell is desirable, we just want to be careful about how it is implemented.

**Comment by tleonhardt** [comment]
@albertored 
Hi Alberto,

We are finished with all of the refactoring we wanted to get done before revisiting this issue.  Would you like to take another shot at a PR for this?
