### ISSUE TITLE
Investigate replacing optparse with argparse

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#36]
optparse has been deprecated since Python 3.2 and all development on it has ceased:
https://docs.python.org/3.6/library/optparse.html

We should investigate replacing the usage of optparse with argparse or a similar library such as docopt or click.

Since the APIs aren't identical, it won't be a trivial drop-in replacement.

**Comment by tleonhardt** [comment]
The argparse documentation has a section on upgrading optparse to argparse:
https://docs.python.org/3/library/argparse.html#upgrading-optparse-code

**Comment by tleonhardt** [comment]
Porting from optparse to argparse looks like it will be complicated by two aspects of how their APIs are incompatible:

1. argparse has no equivalent of the optparse.make_option() factory function which returns an Option instance.

2. For optparse, the parse_args() method returns a tuple of (options, args):
     (options, args) = parser.parse_args()
   But for argparse, the parse_args() method just returns an args object:
    args = parser.parse_args() which includes both options and positional arguments.
   This requires you to add additional ArgumentParser.add_argument() calls for the positional arguments.

**Comment by tleonhardt** [comment]
This StackOverflow article has a few interesting ideas:
http://stackoverflow.com/questions/12750393/python-using-argparse-with-cmd

**Comment by tleonhardt** [comment]
We are going to put this on hold for now.  optparse is still in Python 3.6 and is there are currently no plans to remove it for Python 3.7.

**Comment by kotfu** [comment]
I'm gonna take a crack at this. New branch https://github.com/python-cmd2/cmd2/tree/argparse for the work.

**Comment by tleonhardt** [comment]
@kotfu Bless you sir for giving this a shot!  I couldn't find a good way to do it which would preserve backwards compatibility in the API or something close to it.  But I think your Python Fu may be stronger than mine ;-)  Good luck.

**Comment by tleonhardt** [comment]
@kotfu Let me know if you get to the point where there is some code you would like me to look at or if there is anything I can help with related to this issue.

**Comment by teto** [comment]
@kotfu looking forward to this :)

**Comment by SpotlightKid** [comment]
> But for argparse, the parse_args() method just returns an args object:
> args = parser.parse_args() which includes both options and positional arguments.
> This requires you to add additional ArgumentParser.add_argument() calls for the positional arguments.

Just add 'capture all remaining position args' argument with the `nargs` option:

    parser.add_argument('args', nargs='*')

**Comment by tleonhardt** [comment]
@kotfu I saw you pushed some code to the branch.  I'm excited to take a look at it as soon as I have some free time.  I noticed that the build is failing with it for Python 3.3 but works for 2.7 and 3.4+.  If that isn't a glitch and is a real problem, I'd be happy to abandon official support for Python 3.3 and add testing for 3.7.  At this point I don't know anyone using 3.3 anymore.

**Comment by kotfu** [comment]
It’s very early code, but there is some documentation describing my thinking which will let you know which direction I’m headed.  I’m not surprised that the build failed, I didn’t even try it on all the python versions. I’m not aware of a compelling reason we need to dump support for 3.3, so lemme keep working before we decide.

**Comment by tleonhardt** [comment]
@kotfu I finally got around to looking at the code you pushed to the branch.  I added a few comments to the commit:
https://github.com/python-cmd2/cmd2/commit/4f57dc14a7ffc2cbd741622da7d05d42ba7f7789

Let me know what you think.

**Comment by tleonhardt** [comment]
@kotfu The build failing on the argparse branch had nothing to do with any code on that branch.  Apparently Travis CI no longer supports Python 3.3 builds.  So I updated the build scripts and documentation to reflect that we "officially" support Python 3.4+ and 2.7.  Everything should still work on Python 3.3, we just lost a quick and easy way to run automated unit tests on that platform.
