### ISSUE TITLE
Backport bug in help completion handling of commands using argparser_with_unknown_args

### ISSUE THREAD

**Issue by anselor** [python-cmd2/cmd2#364]
During the autocompleter development I found a bug in handling of help completion that affects the 0.8.x line so I'm going to port those changes back to the python2 branch.

**Comment by tleonhardt** [comment]
Sounds good.  Make sure you update the CHANGELOG.md with info on the bug fix.

Actually, you should probably update the CHANGELOG.md on the **master** branch with this info as well.
