### ISSUE TITLE
test_path_completion_expand_user_dir fails in 0.8.5

### ISSUE THREAD

**Issue by felixonmars** [python-cmd2/cmd2#371]
The error isn't present in 0.8.4.

```
=================================== FAILURES ===================================
_____________________ test_path_completion_expand_user_dir _____________________

cmd2_app = <test_completion.CompletionsExample object at 0x7fc527200860>

    def test_path_completion_expand_user_dir(cmd2_app):
        # Get the current user. We can't use getpass.getuser() since
        # that doesn't work when running these tests on Windows in AppVeyor.
        user = os.path.basename(os.path.expanduser('~'))

        text = '~{}'.format(user)
        line = 'shell fake {}'.format(text)
        endidx = len(line)
        begidx = endidx - len(text)
        completions = cmd2_app.path_complete(text, line, begidx, endidx)

        expected = text + os.path.sep
>       assert expected in completions
E       AssertionError: assert '~build/' in ['~builduser/']

tests/test_completion.py:384: AssertionError
============== 1 failed, 287 passed, 1 skipped in 1344.01 seconds ==============
```

Versions:
```
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /build/python-cmd2/src/cmd2-0.8.5, inifile: tox.ini
plugins: xdist-1.22.2, forked-0.2
```

**Comment by tleonhardt** [comment]
@kmvanbrunt Can you take a look at this?

@felixonmars packages a bunch of Python modules up for the Arch Linux distro.  With his build/packaging environment he ends up testing things in ways which are rather non-conventional compared to other Linux distros (but still valid).  

My guess is that we are inadvertently making an assumption which is true 99% of the time on distros such as Debian/Ubuntu, but doesn't have to be that way.  For example, maybe we are assuming that the user name is the same as the base name of the user directory.

**Comment by kmvanbrunt** [comment]
This test needs to go back to using ``getpass.getuser()`` and not be run on Windows.

**Comment by tleonhardt** [comment]
Or even better put and if/else and use ``getpass.getuser()`` when it isn't Windows and use the current hack when it is Windows.

**Comment by kmvanbrunt** [comment]
The hack makes an assumption that was wrong in the case of @felixonmars's test.

**Comment by tleonhardt** [comment]
But would the assumption the hack makes always be correct on Windows?  If not then yeah, go ahead and just skip the test on Windows.

**Comment by tleonhardt** [comment]
This issue was close by PR #372

**Comment by anselor** [comment]
We probably need to cherry pick this change to the python2 branch for the 0.8.6 release.

**Comment by tleonhardt** [comment]
Since it is "just" a unit test fix I don't think we need to both updating the CHANGELOG.  So we should be good to go.
