### ISSUE TITLE
Cmd2.redirector isn't honored any more, either make it work or deprecate it

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#381]
With the merge of PR #370, `Cmd2.redirector` is no longer honored: the redirector symbol is currently hard-coded as '>'. The documentation still states that you can set `Cmd2.redirector` to something like '->' and have the parsing logic honor that change. We need to either fix the code to match the documentation, or deprecate the attribute and fix the documentation to say that you can't change the redirector.

Related to #392.

**Comment by tleonhardt** [comment]
@kotfu Oh wow, I honestly forgot that that was ever a feature ;-)  Every shell I have seen in recent existence uses > and >> for redirection (overwrite and append, respectively).

My vote would be that we remove it and fix the documentation.

If anyone out there is actually using this feature, please chime in ...

**Comment by kotfu** [comment]
I don't use the feature, but I can think of two use cases where being able to change the redirector would be useful:

1. Your `cmd2` application allows the user to enter SQL statements, which often contain '>' as a greater than comparison operator. 
2. As the current documentation points out, if your `cmd2` application does lots of math work, then the '>' would be more likely used as a comparison operator than a redirection operator.

If we remove `Cmd2.redirector` you can still address these use cases by making your commands multi-line: the current parsing logic only treats '>' and '>>' as redirection tokens in multiline commands when they are preceded by the command terminator (usually ';'). The work-around may not be completely desirable because you might want your `cmd2` application to override the `default()` method to execute the SQL, and you can't make the default command be a multi-line command.

While we wait for others to chime in if they use this or not, the following areas of the codebase will need to be modified to fully support this attribute:

- `Cmd2.tokens_for_completion()`
- `Cmd2._redirect_complete()`
- `Cmd2._cmdloop()`
- `StatementParser` class
