### ISSUE TITLE
Unable to run on OSX after 0.8.3

### ISSUE THREAD

**Issue by mlasevich** [python-cmd2/cmd2#383]
Versions prior to 0.8.3 work, but starting with 0.8.3 I get following error on OSX:

    File "<venv>/lib/python2.7/site-packages/cmd2.py", line 164, in <module>
      rl_basic_quote_characters = ctypes.c_char_p.in_dll(readline_lib, "rl_basic_quote_characters")
    ValueError: dlsym(0x7fe1d2703e40, rl_basic_quote_characters): symbol not found

Thanks

**Comment by kotfu** [comment]
We've been doing a lot of work on **readline** related items, and apparently we broke something. I use OSX all the time and don't have any problems, so maybe there is something specific to your configuration that we aren't handling quite right.

Can you answer a few questions about your Mac?

What version of OSX do you have?
It appears you are using a venv, are you using the system python or another version of python?
Would you be willing to try it with a python 3.6 venv and see if you get the same results?
Do you use homebrew and have you used brew to install the **readline** package?
Would you attach the results of `pip list` so we can see which versions of python packages you are using with `cmd2`?

**Comment by tleonhardt** [comment]
Starting with around 0.8.3 on macOS we started requiring either **readine** or **gnureadline** to ensure proper tab completion.  Prior to that version of cmd2, no readline requirements existed on macOS and you could use cmd2 even though tab completion did not work.

**Comment by mlasevich** [comment]
Stood up a quicky ElCapitan Vagrant box with minimal install and can replicate issue.

Note that the issue showed up before I even installed port or gnureadline yet, so that is interesting.

I installed port and readline package as well as py27-gnureadline package - but nothing changed.

I vaguely recall having to do something to activate gnureadline as default readline instead of built in OSX stuff, but I do not recall what it was at this point and clearly that must have gotten undone, as I confirmed that I am using libedit now :-/ ( For what its worth, when downgrading to 1.8.2, tab completion works fine.)

So, is libedit no longer supported as of 1.8.3? And are there instruction on how to make sure you can use gnureadline?

Here is the output of the `pip list`, since I promised:

    Package        Version
    -------------- -------
    cmd2           0.8.3  
    contextlib2    0.5.5  
    enum34         1.1.6  
    pip            10.0.1 
    prompt-toolkit 1.0.15 
    pyparsing      2.2.0  
    pyperclip      1.6.0  
    pyreadline     2.1    
    pyserial       3.4    
    PyYAML         3.12   
    setuptools     39.1.0 
    six            1.11.0 
    subprocess32   3.2.7  
    wcwidth        0.1.7  
    wheel          0.31.0

**Comment by kmvanbrunt** [comment]
@mlasevich 
Can you add a print statement right before the call to set `rl_basic_quote_characters`?
Add `print(readline.__file__)` and let us know the value. That will be the **readline** shared library we are loading. I suspect **libedit** is being used.

@tleonhardt 
readline is still not a requirement unless you want to use tab completion. Even in recent versions, **cmd2** should function without it.

**Comment by kmvanbrunt** [comment]
@mlasevich 
You commented right before my last post :)

Yes, it does appear **cmd2** is loading **libedit**. In 0.8.3, we added some hooks into the GNU **readline** shared library to support automatically adding quotes to tab completed items that have spaces. Therefore we only support GNU and not the **libedit** implementation. We should probably check `readline.__doc__` to see what version was loaded and warn the user that tab completion will be disabled.

@tleonhardt 
Do you have suggestions for how to activate **gnureadline**?

**Comment by mlasevich** [comment]
Yeah, I confirmed that it was `libedit` using  `if readline.__doc__ and 'libedit' in readline.__doc__:` test

The second I added gnureadline to my requirements list, it started working just fine.

**Comment by mlasevich** [comment]
I suppose this ticket, should you care to keep it, can turn into "support libedit again" ticket. Otherwise it can be closed.

**Comment by kmvanbrunt** [comment]
@mlasevich 
I've just been looking at the code for **libedit** and have a theory. Unfortunately, I don't have a Mac to test it on.

Can you please try something for me? Can you set it back to use **libedit** and comment the following lines? The line numbers may be off, but basically I want you to comment out all uses of `rl_basic_quote_characters`.

**164**: `rl_basic_quote_characters = ctypes.c_char_p.in_dll(readline_lib, "rl_basic_quote_characters")`
**165**: `orig_rl_basic_quote_characters_addr = ctypes.cast(rl_basic_quote_characters, ctypes.c_void_p).value`
**2724**: `rl_basic_quote_characters.value = None`
**2781**: `rl_basic_quote_characters.value = orig_rl_basic_quote_characters_addr`

Once these are commented, try using tab completion and see if you get expected results. The best test would be doing something that tab completes with multiple results. For instance, do: `load ~/<TAB><TAB>` to get a file listing.

**Comment by mlasevich** [comment]
Done. Using 1.8.5 install, I removed pyreadline and gnureadline and confirmed I was using libedit and then commented out the 4 lines you mentioned. Tab completion seems to be working fine, although when it has multiple matches it hits BELL on the very first tab,  and only shows options on subsequent tab hits - (not sure if it is how it always was, but I never noticed it before)

**Comment by kmvanbrunt** [comment]
Thanks for testing. From those results, it does look like **libedit** is easily supported. I'll borrow a Mac to double check some other tests and if everything looks OK, I'll add the fix.

Hitting tab twice to show tab completion possibilities is standard behavior and is a function of readline itself.

**Comment by tleonhardt** [comment]
@kmvanbrunt 
If **libedit** can be easily supported that would be great.

If your fix works it should get merged into master and also back ported to the **python2** branch.

**Comment by kmvanbrunt** [comment]
I got everything working except for `readline.set_completion_display_matches_hook()`
For some reason, **libedit** would not call our display function. Python docs don't mention the lack of support for a custom display function but it will not work. Since our recent changes rely on a custom display function, we can't support **libedit** right now.

In the warning I am adding in #361, I will detect if **libedit** is being used and let the user know that tab completion has been disabled.

**Comment by mlasevich** [comment]
Thanks. !!

I wonder why tab completion with **libedit** works for some and not others. FWIW, I could never get tab completion to work under windows at all either.

**Comment by kmvanbrunt** [comment]
@mlasevich 
Windows requires the installation of **pyreadline** which we do support.

cmd2 supports tab completion in **libedit** up to a point. We recently added a custom display function to handle certain types of results. Since it isn't calling that function, you still see tab completions, but not the right ones.

To test this, do the following.

Run `!ls ~/Desktop/<TAB><TAB>`

You should see results like this if our display function is being called:
`code.c file.txt folder1 folder2`

If not it will look like this:
`~/Desktop/code.c ~/Desktop/file.txt ~/Desktop/folder1 ~/Desktop/folder2`

**Comment by mlasevich** [comment]
Makes sense. I do have pyreadline installed on windows and it is not working, but let me not hijack a closed issue. I will do some extra testing and if it is supposed to be supported and still does not work, I will open a separate issue. Thank you very much.
