### ISSUE TITLE
Fix fabfile.py to upload using twine

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#399]
[PEP566](https://www.python.org/dev/peps/pep-0566/#description-content-type-optional) and pypi.org now finally natively support markdown in the long description, see https://github.com/pypa/warehouse/issues/869. To take advantage of this feature you have to upload with `twine`.

In addition, https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi seems to indicate that `python setup.py upload` may not always be secure, and they suggest using `twine` instead.

**Comment by kotfu** [comment]
Maybe do this as part of #408.

**Comment by tleonhardt** [comment]
This was fixed by PR #422
