### ISSUE TITLE
python3 doesn't have file type like python2 does

### ISSUE THREAD

**Issue by FedericoCeratto** [python-cmd2/cmd2#4]
Originally reported by: **Anonymous**

---

Using python3.3 with a cmd2.py modified by 2to3.
There are two instances were cmd2 checks whether some object is of type file. There is apparently no builtin type file.

I fixed the issue this way:

try:
    import io
    file = io.TextIOWrapper
except ImportError:
    pass # Python2

But only tried it on python3 version.

Also your documentation claims that cmd has shortcuts @ and !: there doesn't appear to be any @, but there is a ? shortcut.

---
- Bitbucket: https://bitbucket.org/catherinedevlin/cmd2/issue/4

**Comment by tleonhardt** [comment]
The Python 3 issue with no basic "file" type existing was fixed about a month ago when the use of 2to3 was replaced by the six module.
