### ISSUE TITLE
Investigate refactoring to allow incorporation of prompts from python-prompt-toolkit

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#40]
Python Prompt Toolkit provides some really powerful and cool features:
https://github.com/jonathanslenders/python-prompt-toolkit

It would be nice if a cmd2 user could optionally replace the default prompt with a prompt from python-prompt-toolkit.

This would at a minimum require replacing the simple string prompt with a function which prints a prompt and returns the text the user entered.  It would be somewhat of a departure from cmd.  But it would open up the door for easily incorporating things like syntax-highlighting, input validation, and a bottom toolbar.

I'm not sure it would really be possible to make cmd2 and python-prompt-toolkit play nicely together, but if it is, it would be a great thing.

**Comment by tleonhardt** [comment]
Incorporating ``python-prompt-toolkit`` prompts into ``cmd2`` isn't possible without creating essentially a completely different tool.

``cmd2`` is based on ``cmd`` which in turn is based on the readline C library or an equivalent.  ``prompt-toolkit`` is (among other things) a replacement for readline.  So there is a fundamental incompatibility at a low level.

A fork of ``cmd2`` which removed the inheritance from ``cmd`` and the dependence on readline and replaced it with usage of ``prompt-toolkit`` would make for an interesting project.  If anyone wants to undertake that they have my blessing and I would probably be willing to help out.  I recommend it be called something like ``cmd-prompt``.  This theoretical project could potentially combine the quick, easy, and feature-rich aspects of ``cmd2`` with the power and visual richness of ``prompt-toolkit``.  But I don't have the time to work on such a project at the moment ...

**Comment by shivanshcoder** [comment]
Hey @tleonhardt, I tried doing this, just made extra class for achieving the functionality
Check out my repository
[https://github.com/shivanshcoder/cmd2-prompt](url)

My code simply uses `prompt-toolkit` to display the suggestions, the suggestions are made using the `cmd2` code itself.
I was thinking of starting auto completion from scratch but first tried using already available code

**Comment by anselor** [comment]
@shivanshcoder 
I'll try to take a look at this too. 

I was actually exploring how we could support prompt toolkit integration pretty recently. 

For full-screen prompt-toolkit applications, I think it should be possible to override the `poutput` and `perror` functions to add a destination prompt-toolkit container.

For completions we should be able to bypass our readline usage and use prompt toolkit instead. I was also trying to figure out how to support our argparse/autocompleter this way as well.

I don't fully understand it, but I know prompt-toolkit has its own way of specifying input parameters and completions. If it makes sense what may also be nice is a new command decorator that gathers inputs in a more prompt-toolkit compliant way and then pass them to the command function.

**Comment by shivanshcoder** [comment]
Yes with prompt-toolkit we can even do validations and print helping statements in toolbars.

By modifying `cmd2:Argparse completer` we can provide extra display information with prompt-toolkit toolbars.

I am reading `cmd2` code quite extensively inroder to try make prompt-toolkit as an additional completer with all expected functionalities.

**Comment by tleonhardt** [comment]
@shivanshcoder If you can get this to work in a clean way that would be awesome.  @kmvanbrunt Is a good person to chat with if you have any questions about how our completion stuff works.  Feel free to re-open this issue or create a new one if you think this can be make to work in a clean and maintainable fashion.

**Comment by anselor** [comment]
Also, definitely take a look at the changes being made in the 2.0 branch. There are some API breaking changes coming related to completion.
