### ISSUE TITLE
Improve hooks to better support plugins

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#410]
There is a nice system of hooks in place today, which allows subclasses of `cmd2.Cmd()` to inject code at various places in the command processing cycle. See `hooks.rst` in the documentation for full details. With the recent introduction of the idea of plugins, there is a possibility of multiple plugins now wanting to inject code into the same hook.

You can do this today by carefully specifying the order of your mixin classes in your subclassing statement, and ensuring you have the proper `super()` calls in your methods. However, this method is not super intuitive for those who aren't up to speed on the `super()` chain with multiple inheritance.

I propose we implement a more robust system where a plugin can register functions to be called at various points in the command processing cycle. `cmd2.Cmd()` would keep track of all the registered functions for each "hook", and then call them in sequence when the "hook" was activated.

This approach also could make it easier to define command processing plugins. All of the command processing hooks would call functions with a similar parameter and return signature, which would mean you could define a plugin function, and insert it into whichever hook you wanted. Moving your function to a different hook would not require you to modify the function, just the hook to which it was registered.

I think we can maintain backwards compatibility with the current method of calling hooks by fixing `onecmd_plus_hooks()` to call the registered functions for each hook, and then call the hook method (as it currently does). This approach would allow subclasses of `cmd2.Cmd()` to override `postparsing_precmd()`, while still using plugins which would also like to perform work in that same hook.

**Comment by anselor** [comment]
I like this idea.

**Comment by tleonhardt** [comment]
I'm not sure I fully grok how this would be implemented, but I certainly like the sound of it.

**Comment by kotfu** [comment]
New branch **plugin_functions** for this work. Progress coming along nicely. Suggest fixing #420 in this branch too, since they are related.

**Comment by tleonhardt** [comment]
@kotfu I pushed a minor fix for versions of Python prior to 3.6 to your *plugin_functions* branch.

Apparently, prior to Python 3.6, you can't have a trailing comma after the last argument in a method declaration.
