### ISSUE TITLE
preparse() and postparse() never get called

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#417]
`preparse()` and `postparse()` methods exist in `cmd2.Cmd` and the docstrings say they get called before and after the user input is parsed. Same methods are referenced in `hooks.rst`. However, these two methods are never called the command processing loop in `onecmd_plus_hooks()`.

We need to either call these methods, or remove them from the code and the documentation.

If we decide to call these methods, we will have to make a decision about when the right time to call `preparse()`, because on a multiline command, the line can be parsed multiple times.

`postparse()` would be called at the same place as the existing `postparsing_precmd()` hook.

**Comment by tleonhardt** [comment]
Nice find.

‘’postparse’’ seems redundant with ‘’postparsing_precmd’’, so I think we should only keep one of those.  

I’ve personally never used ‘’preparse’’, but I can envision situations where that may be useful.

**Comment by tleonhardt** [comment]
PR #420 dealt with half of this issue.  The other half should be fixed when Issue #410 is handled.

**Comment by xNinjaKittyx** [comment]
Man, I was wondering why my prompt was case-sensitive. My `preparse()` just executes `raw.lower()` to make it case-insensitive...
