### ISSUE TITLE
Fix twine upload

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#423]
Running the new **invoke pypi** command to build and upload a release to PyPI fails in the very last step with the following error message:

```sh
Uploading distributions to https://pypi.python.org/pypi
Note: you are uploading to the old upload URL. It's recommended to use the new URL "https://upload.pypi.org/legacy/" or to leave the URL unspecified and allow twine to choose.
Uploading cmd2-0.9.0.post1-py3-none-any.whl
100%|██████████| 76.8k/76.8k [00:00<00:00, 721kB/s]
RedirectDetected: "https://pypi.python.org/pypi" attempted to redirect to "https://pypi.org/pypi" during upload. Aborting...
```

The command being executed when this occurs is:
```sh
twine upload dist/*
```

**Comment by kotfu** [comment]
Ensure you have at least twine 1.11.0, wheel 0.31.0, and setup tools 39.1.0. Upgrade via:
```sh
$ pip install --upgrade twine wheel setuptools
```

After upgrading, please create credentials at https://test.pypi.org (you need to create a user separately there from the one you have at https://pypi.org). Once you have test credentials, try:
```sh
$ invoke pypi-tests
```

Report results.

**Comment by tleonhardt** [comment]
@kotfu 
I had older versions of twine and setuptools.  I updated them and registered for an account on test.pypi.org.

I tried doing the **invoke pypi-tests** and got the following error:
```sh
HTTPError: 403 Client Error: The user 'tleonhardt' isn't allowed to upload to project 'cmd2'.
```

How do I get added as a maintainer to the ``cmd2`` project on test.pypi.org?  If that something I can do for myself?  Or can you give me the permissions?  Or do I have to email Catherine?

**Comment by kotfu** [comment]
The first time I uploaded `cmd2` to test.pypi.org, it created me as the owner of `cmd2`, so clearly it's not synced with the real version. I just added you as an owner.

**Comment by tleonhardt** [comment]
After updating my versions of twine and setuptools (and after you granted me access), everything uploaded to test.pypi.org just fine.

I'm about to create a small PR to resolve this issue by requiring a minimum version of ``twine`` in the setup.py file for the "dev" tools.
