### ISSUE TITLE
Create an example demonstrating how to use functionality provided by argcomplete_bridge.py

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#427]
Previously the features provided by [argcomplete_bridge.py](https://github.com/python-cmd2/cmd2/blob/master/cmd2/argcomplete_bridge.py) were demonstrated in the **subcommands.py** example.  But Issue #426 calls for simplifying the **subcommands.py** example.

A new example should be created to demonstrate how to use the features provided by **argcomplete_bridge.py**.

**Comment by tleonhardt** [comment]
@anselor You are the one most familiar with this part of the code.  What would you recommend for an example?

**Comment by tleonhardt** [comment]
@anselor Is this something you could knock out a quick example of in 5 or 10 mins?  It seems like a really cool feature which we haven't adequately made discoverable by end users.

**Comment by anselor** [comment]
I'll try to get something thrown together today to show this off.
