### ISSUE TITLE
Crashing on open() calls

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#430]
Some calls to `open()` are not surrounded by a `try` and are crashing.

`help > ~/fakedir/file` (Crashes with **FileNotFoundError**)

`help > ~/sdkfhksdjfhkjdshfkjsdhfkjsdhfkjdshfkjdshfkjshdfkhdsfkjhewfuihewiufhweiufhiweufhiuewhiuewhfiuwehfiuewhfiuewhfiuewhfiuewhiuewhfiuewhfiuewfhiuwehewiufhewiuhfiweuhfiuwehfiuewfhiuwehiuewfhiuewhiewuhfiuewhfiuwefhewiuhewiufhewiufhewiufhewiufhewiufhewiufhewiufhewiuhewiufhewiufhewiuheiufhiuewheiwufhewiufheiufheiufhieuwhfewiuhfeiufhiuewfhiuewheiwuhfiuewhfiuewhfeiuwfhewiufhiuewhiuewhfeiuwhfiuwehfuiwehfiuehiuewhfieuwfhieufhiuewhfeiuwfhiuefhueiwhfw` (Crashes with **OSError** because the file name is too long)

All `open()` calls need to be checked for this issue.

**Comment by tleonhardt** [comment]
The fix for this should preferably be backported to the *python2* branch.
