### ISSUE TITLE
Unexpected redirection behavior

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#431]
`help > name with space` creates a file called **name with space**
`help > "name with space"` creates a file called **"name with space"** (quotes included)

I would expect the first command to either output to a file called **name** or fail for invalid syntax.
I would expect the second command to output to a file called **name with space** (unquoted)

**Comment by tleonhardt** [comment]
If this bug exists in the *python2* branch, then the fix should be backported there.
