### ISSUE TITLE
set debug true warning in perror

### ISSUE THREAD

**Issue by mtn** [python-cmd2/cmd2#436]
Hi!

In [this issue](https://github.com/uchicago-cs/chistributed/issues/11) from the `chistributed` framework, which implements its repl using `cmd2`, we encountered an issue where `set` was defined as a command, making the `set debug true` warning confusing. I noticed that this is printed conditionally based on a parameter to `perror`, and no option to control this is exposed to the end user.

It seems to me that either `set` should be a privileged command that can't be overloaded, or the end user should be given this option. It could be passed in at initialization, and used if defined (falling back to the current values).

Any thoughts? I'm happy to submit a patch. 🎈

**Comment by tleonhardt** [comment]
@mtn 
Hey, thanks for bringing up the issue you are having.  I wasn't aware of the ``chistributed`` framework.

My first thought is "you break it, you buy it" - as in if you choose to override a built-in command and make it do something totally and completely different in your application which inherits from ``cmd2.Cmd``, then it is your responsibility to also override any impacted methods within your class which derives from ``cmd2.Cmd`` (such as **perror()** in this particular case).  I don't view this as a failing within the ``cmd2`` framework.  For example if you don't want to see that warning you should simply override **perror** in your class to be something like:
```Python
    def perror(self, errmsg, exception_type=None, traceback_war=False):
        """ Print error message to sys.stderr and if debug is true, print an exception Traceback if one exists.

        :param errmsg: str - error message to print out
        :param exception_type: str - (optional) type of exception which precipitated this error message
        :param traceback_war: bool - (optional) if True, print a message to let user know they can enable debug
        :return:
        """
        if self.debug:
            import traceback
            traceback.print_exc()

        if exception_type is None:
            err = self.colorize("ERROR: {}\n".format(errmsg), 'red')
            sys.stderr.write(err)
        else:
            err = "EXCEPTION of type '{}' occurred with message: '{}'\n".format(exception_type, errmsg)
            sys.stderr.write(self.colorize(err, 'red'))
```

Secondly, I would say that the functionality provided by the **set** command is pretty useful.  I would recommend renaming the command provided by ``chistributed`` to be something different.  But if your command absolutely needs to be called "set", then I would copy the existing **do_set** method from ``cmd2`` and rename it to something else so your users have access to it.

Thirdly, this is Python so I'm not sure what you mean by a "privileged command that can't be overloaded".  I know how to do that in any of Java, C++, or C# but I'm not aware of how to do that in Python.  If there is a simple way to do it in Python, then please let me know how to do it and I would be happy to entertain that approach.

Lastly, if you have some good idea of how to make a simple modification to ``cmd2`` which would help you but also be generically useful to a number of other users, then please feel free to submit a Pull Request.  But honestly, this seems like it could probably be handled pretty easily on your end with a small code change.

Any thoughts?

**Comment by mtn** [comment]
What you said makes sense to me -- thanks for the detailed response!

I'm not the owner of `chistributed` and thus won't be making the decision, but I think this information was really helpful and at least helped me see some possible solutions.

I'm going to close this for now.
