### ISSUE TITLE
Windows and async output

### ISSUE THREAD

**Issue by mlasevich** [python-cmd2/cmd2#446]
I am running into an issue on windows - when on windows and have tab completion enabled(i.e. in pyreadline), any async output (i.e. output sent DURING reading of a line) printed via `cmd.poutput()` is erased once you enter a line. If I set `use_rawinput` to false, the problem goes away, but so does tab completion functionality, which is not acceptable....

I worked around the original issue by buffering the output lines that pass through poutput and re-printing them once raw_input completes, which is hacky,  but works, but then I discover that the last line of the output is now being returned by `raw_input` instead of my actual line entered....

I realize it is most likely some pyreadline quirk, but is there a way to get both async output AND tab completion to work under windows? And is there a replacement for pyreadline in the works,  given that pyreadline seems to be abandoned?

Thanks,

**Comment by kmvanbrunt** [comment]
@tleonhardt
Working on something right now. It wouldn't be something I'd include in the official **cmd2** though.

@mlasevich 
What version of **cmd2** and Python are you using? You mention `raw_input `. Does that mean you are using Python 2?

**Comment by mlasevich** [comment]
Yes, sadly I am on Python 2.7 with Cmd2 1.8.7 and pyreadline 2.1, testing on Win10

After beating my head against this for a few hours, I am now convinced it is some "feature" of pyinstaller but I am not able to figure out how to get around it or turn it off. At this point I hackily solved most of my issues (by wrapping chunks of the Cmd2 code), but the main problem remaining is that while it is reading a line (via raw_input), the second I touch a key, it wipes out everything on the screen that appeared since pyreadline started reading. Some sort of a screen redraw, but while gnureadline redraws the line, pyreadline wipes out everything on the screen.

I made a super simple example to demonstrate this:

```python
import threading, time
import readline
from cmd2 import Cmd

readline.parse_and_bind("tab: complete")

class Test(Cmd):
    ''' Test CMD2 Implementation '''

def lines(cmd):
    while True:
        cmd.poutput('Timestamp: %s' % time.time())
        time.sleep(1)

def main():
    cli = Test()
    writer = threading.Thread(target=lines, args=(cli,))
    writer.daemon = True
    writer.start()
    cli.cmdloop()

if __name__ == '__main__':
    main()
```

**Comment by mlasevich** [comment]
Yeah, after digging some more in pyreadline code, I discovered some internal private methods I can user to alter the redraw, which seems to got me to point of "ugly but working as desired"
ended up doing this:

(pyinstaller was a typo, I meant pyreadline, dealing with too many things at once)

```python
    def poutput(self, msg, end='\n'):
        try:
            if hasattr(readline.rl,"prompt_begin_pos"):
                readline.rl._update_prompt_pos(-1)
            if self.active_prompt:
                line_buff = readline.get_line_buffer()
                if line_buff and line_buff[-1] == '\n':
                    line_buff = ""
                reprint = '%s%s' % (self.active_prompt or "", line_buff)
                reprint.rstrip('\n')
                self.stdout.write('\r'+' ' * (len(reprint)+2)+'\r')
                Cmd.poutput(self, msg, end=end)
                if hasattr(readline.rl,"prompt_begin_pos"):
                    readline.rl._update_line();
                else:
                    self.stdout.write(reprint)
            else:
                Cmd.poutput(self, msg, end=end)
        except Exception,ex:
            print "Exception: %s" % ex

    def pseudo_raw_input(self, prompt):
        self.active_prompt = prompt
        line = Cmd.pseudo_raw_input(self, prompt)
        self.active_prompt = None
        return line
```

**Comment by kmvanbrunt** [comment]
That's very close to what I was writing. I didn't have the logic you included for checking if `readline.prompt_begin_pos` exists. That should prevent an exception when the prompt has not been printed yet.

I've had to call directly into **pyreadline** and **gnureadline** for a few things we do in cmd2. I understand your pain :)

Do you plan on upgrading to Python 3? Keep in mind that we aren't adding new features to the Python 2 version of **cmd2**.

**Comment by mlasevich** [comment]
Yeah, when I first tried the `_update_prompt_pos()`  route, it did not work because they do not initialize the variables (shame on them), causing a crash on my part. So, better safe than sorry :-) 

I am aware of the switch to P3 only for Cmd2. I was really hoping to avoid transitioning as long as possible, as there is a bunch of legacy code behind the CLI that I really do not want to go over. But I guess I need to stop being lazy. ;-)

Feel free to close this issue, as this is all on pyreadline's shoulders. Sorry for wasting your time.

**Comment by kmvanbrunt** [comment]
No worries. We're always happy to help.
