### ISSUE TITLE
Plan for 0.9.2 release

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#448]
When would everyone like to put out the 0.9.2 release (with the 0.8.8 going immediately beforehand from the python2 branch)?

The last feature I really want to see go in there is the improvements to hook functions which @kotfu is working on and will likely be wrapping up with soon.

@kmvanbrunt @anselor Is there anything else you would like to see make it into this next release?

**Comment by anselor** [comment]
I noticed today that the legacy CmdResult class and possibly some associated functions are still there. I think we should probably remove that in favor of the new CommandResult provided in pyscript_bridge.

**Comment by tleonhardt** [comment]
I created Issue #449 to replace the legacy CmdResult class with the new CommandResult (as long as nobody objects to this).

**Comment by kotfu** [comment]
Likely be 10-14 days before I have time to get them finished. I’d love to have them included in 0.9.2.

**Comment by tleonhardt** [comment]
@kmvanbrunt @anselor If I recall you were both hoping to get a release out the door pretty soon.  What timeframe were you hoping for?

**Comment by tleonhardt** [comment]
Tentatively I am thinking about doing a release tomorrow night.  If things don't make it into this one, no big deal we can put out 9.3 shortly thereafter if we wish.

**Comment by tleonhardt** [comment]
Both the 0.8.8 and 0.9.2 release were put out this evening.
