### ISSUE TITLE
Replace legacy CmdResult class with new CommandResult class

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#449]
The ``CmdResult`` class in **cmd2.py** should probably be considered legacy and replaced with the ``CommandResult`` class in **pyscript_bridge.py**.  

As long as this wouldn't create an undue burnden on anyone in terms of backwards compatibility, then we should remove all reference to ``CmdResult`` and replace it with reference to ``CommandResult``.

Would anyone object to this?

**Comment by kotfu** [comment]
No objection from me. Should we deprecate it for a release before actually deleting it?

**Comment by tleonhardt** [comment]
@kotfu I would be in favor of deprecating but not fully removing it for a release, but removing it from the imports in ``__init__.py`` while it is deprecated.

@kmvanbrunt As long as deprecating this won't unduly inconvenience you on one of your projects, we will probably move forward with this shortly.
