### ISSUE TITLE
The startup_script feature ignores spaces

### ISSUE THREAD

**Issue by Den1al** [python-cmd2/cmd2#457]
I tried to add a `startup_script` using the following code:
```python
class MyCmd(Cmd):
    def __init__():
        Cmd.__init__(self, startup_script='/home/ubuntu/my folder/start.rc')
        ...
```

However, after debugging the code, it seems that cmd2 is considering that path as two separated elements: `/home/ubuntu/my` and `folder/start.rc', and then of course the parsing fails when trying to see if that's a real file, as I get the following error:

`ERROR: /home/ubuntu/my does not exist or is not a file`

Any help?

**Comment by tleonhardt** [comment]
@Den1al Thank you for reporting this.  I was able to reproduce it and it is most certainly a bug.  We will look into fixing it shortly.

**Comment by Den1al** [comment]
Hi, thanks for the quick response, a quick fix that I found was to wrap the path using double quotes like this: 
![image](https://user-images.githubusercontent.com/7230603/41925232-ac9b2614-7974-11e8-967c-fdf47f7735e3.png)

**Comment by tleonhardt** [comment]
Yup, came to the same conclusion myself and just pushed that fix ;-)  PR coming shortly

**Comment by tleonhardt** [comment]
The fix should merge into master sometime today and then our next release should get put out within two weeks or so.  

Thanks again for reporting this!  And double thanks for proposing a fix.

**Comment by Den1al** [comment]
Great, awesome news!
I'll take this chance to show my immense appreciation to you guys for this awesome library.
