### ISSUE TITLE
Consider refactoring how colorize and colors work in cmd2

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#461]
Currently ``cmd2`` has:
* a required dependency on [colorama](https://github.com/tartley/colorama)
    * provides cross-platform colored terminal text on Window, macOS, and Linux
* a built-in ``colorize`` method in ``Cmd`` class that provides colored terminal text on macOS and Linux
    * uses an internal dictionary which maps string color names to ANSI color escape codes

Having both of these feels awkward and redundant.  There are several possible options I could see for refactoring this including the following:
1.  Make ``colorama`` an optional dependency and refactor the **colorize** method to use ``colorama`` if present and to provide no color if it isn't
2. Keep ``colorama`` as a required dependency and refactor the **colorize** method to use it
3. Remove the dependency on ``colorama`` and use **colorize** where it is currently being used

Other possible additions include things such as:
- adding an optional **color** argument to methods such as ``poutput``
- refactoring the underlying implementation of how colors are stored
- creating a separate module which provides string color codes based on a color name lookup and wraps ``colorama`` and/or ``colored``

I would be curious to hear other people's opinions regarding how to best proceed with this.  What are your thoughts?

**Comment by kotfu** [comment]
Ancient and apparently unmaintained, but https://github.com/kennethreitz/clint has an interesting approach to colors.

**Comment by henryiii** [comment]
If there's interest, I could make [plumbum.colors](http://plumbum.readthedocs.io/en/latest/colors.html) available separately.

**Comment by tleonhardt** [comment]
@henryiii Thanks for making me aware of [plumbum](https://plumbum.readthedocs.io/en/latest/)!  It seems like a great package with a lot of features that ``cmd2`` developers would likely find useful.  I was particularly impressed with the ease of running SSH commands on a remote machine relative to [paramiko](http://www.paramiko.org).  I'm embarrassed to say that I had never heard of it before you mentioned it.  But its feature set is a great fit for the same types of applications that ``cmd2`` are intended for.  The 256 colors it provides is also a lot nicer than the number of colors provided by [colorama](https://pypi.org/project/colorama/).

If we could figure out a good architecture, it might be more work but I like the concept of an abstraction layer around various Python packages which provide color where all of those would be optional dependencies.  So perhaps this abstraction layer could provide a consistent API which is a wrapper around.

**Comment by kotfu** [comment]
As far as I can tell, `colorama` is the only library that supports *nix, macOS, and Windows. Interestingly, the way `colorama` supports Windows is by parsing certain ANSI escape sequences in the output and translates them into Windows API calls. If `colorama` can't translate the ANSI escape sequences, it strips them on Windows. That means that you can use any python color library that generates the basic ANSI color escape sequences, and as long as you pipe the generated strings through `colorama` you get cross platform color support. If you use extended ANSI escape sequences to get more colors on certain terminal emulators, they work where they are supported, and stripped on Windows.

I propose that we:

- deprecate the builtin `cmd2` support for colors, including `self.colorize()` and `self._colorcodes`
- make sure `colorama` gets initialized properly in `cmd2`
- modify the **colors** setting to not be dependent on which platform you are on
- make `poutput()` and `perror()` strip ansi escape sequences if the colors setting is **False**
- make sure `cmd2` intelligently recognizes whether output is a tty and skips color output if it's not. If the **colors** setting is **Force**, then `cmd2` should output the ansi escape sequences anyway
- add some examples and documentation to show the colorizing support you get by default via `colorama`, as well as how you can utilize other python color generating libraries (like `plumbum.colors`, `blessings`, and `termcolor`) and still get full cross-platform functionality via the integrated `colorama` support.

**Comment by tleonhardt** [comment]
Good point about ``colorama`` being the only library of the three mentioned that supports Windows, macOS, and Linux.  I didn't realize that ``colorama`` supported Windows in a way where it would strip out colors if it didn't know how to make the corresponding Windows API call.  I've only ever used the ``Fore`` API within ``colorama``.

I think your proposal sounds excellent.

**Comment by henryiii** [comment]
I like the proposal as well. 👍 

Most other libraries (like Plumbum.colors) just use colorama to do the windows API conversion (by patching sys.stdout, IIRC). Due to the drastically different nature of the API calls and escape sequences, it's the only reasonable way to do it.

The Plumbum.colors code for setting the correct color defaults on common platforms is here if that helps:

https://github.com/tomerfiliba/plumbum/blob/22db2e82b114c02592716530241448bb66b76fdf/plumbum/colorlib/styles.py#L43-L60

Plumbum.colors does strip colors by default, but you can override that by setting the color settings (or by using the HTML output). Putting ansi escape sequences in a log file used to be frowned on as a default, though colors are not too bad. (Cursor movement, on the other hand, is probably always a bad idea).

**Comment by tleonhardt** [comment]
@kotfu I merged *master* into your **colorize** branch where you are doing the work for this Issue and pushed some small changes to fix the documentation build unit test and unit tests on Windows.  I apologize if that interferes with the work you are doing, but it seemed like a good idea.
