### ISSUE TITLE
Version number should be in a single place

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#470]
Currently when we change the version number, this has to be done in 4 places:
- setup.py
- cmd2/cmd2.py
- tests/test_cmd2.py
- docs/conf.py

We should re-architect how the version is done so it only needs to be changed in a single place.  Or worst-case possibly in two places.  Having to change it in 4 places is painful and potentially prone to error.

**Comment by kotfu** [comment]
How about zero places? If we use https://github.com/pypa/setuptools_scm, the version number it automagically is set to the git tag. With this integrated into `cmd2`, all we have to do is tag and upload to pypi.

This approach does mean that there is no meaningful way to "test" the version number, like we do now in `tests/test_cmd2.py`, but I'm not so sure that's helpful anyway.

**Comment by tleonhardt** [comment]
I'd be fine with zero places.  I wasn't aware of [setuptools_scm](https://github.com/pypa/setuptools_scm).

The only reason we have a test for the version number was to make sure we changed it in least the two places associated with that test (on the theory that if you remembered to change it in those two, chances are good you remembered to change it in the other two).  If the version number is in either zero or one place, then I don't see any good reason to "test" that version number.

**Comment by tleonhardt** [comment]
This was closed by #481
