### ISSUE TITLE
Consider using `wrapt` module on app decorators.

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#473]
The [wrapt](http://wrapt.readthedocs.io/en/latest/index.html) module ensures that decorators can be applied properly to any function, class method, static method, or instance method. It also makes decorated functions appear and behave properly in many IDE's.

See https://hynek.me/articles/decorators/ for full explanation.

**Comment by tleonhardt** [comment]
I had vaguely heard about the ``wrapt`` module, but had never looked into it.  It sort of sounds like an improved version of ``functools.wraps`` which sounds like a great thing to me.  

If we are already moving in the direction of adding more 3rd-party dependencies on things like [attrs](https://github.com/python-attrs/attrs), then I don't see any reason to not replace our current usage of ``functools.wraps`` with the ``wrapt`` module.

At one point I believe we were having an internal debate regarding whether we wanted to try to minimize 3rd-party dependencies to move in the direction of possibly having a **cmd2-lite** variant which could eventually replace the current built-in ``cmd`` module.  However, I don't believe any of the current ``cmd2`` maintainers were willing to step up and assume the responsibility of becoming a Python Core Maintainer for the ``cmd`` module.  

The alternative possibility is to continue to strive to be the best possible tool for quickly and easily building feature-rich interactive command-line applications and in that case it is fine to embrace adding 3rd-party dependencies on popular Python modules which are in wide use.  Of course, we have other projects which have ``cmd2`` as a dependency such as OpenStack [cliff](https://github.com/openstack/cliff) so adding dependencies can potentially impact these projects and we shouldn't go too nuts.

**Comment by tleonhardt** [comment]
From re-reading the linked article in the description above, ``@functools.wraps`` works pretty darn well on Python 3.5+  Given that ``cmd2`` only supports back to Python 3.4 and it is questionable how much longer we will continue supporting Python 3.4 for, I don't see a lot of motivation to make changes which might potentially break things for end users if we aren't super careful.  

If any of the other core maintainers feel differently, please feel free to re-open this Issue and work on it.
