### ISSUE TITLE
Fix outdated dependency-ci check

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#476]
Currently all PRs require an Admin to merge them even if all tests pass and a reviewer has approved due to the outdated **dependency-ci** check.  

At some point the Tidelift check replaced the dependency-ci one, but we now for some reason have both.

This should be fixed.

**Comment by tleonhardt** [comment]
I tried removing the hook that looked like it made sense.  Now our Tidelift check is gone, but it is still trying to do the dependency-ci check.  I really don't know where that is coming from.

**Comment by kotfu** [comment]
I'm not an org admin so I can't check, but it could be that **dependency-ci** is an organization web hook. See https://blog.github.com/2014-12-03-introducing-organization-webhooks/

**Comment by tleonhardt** [comment]
@kotfu You should now be an org admin.

I don't see any organization web hooks.  But maybe I'm looking in the wrong place.

**Comment by kotfu** [comment]
Well, that wasn't it. No organization web hooks are defined. I'm stumped.

**Comment by tleonhardt** [comment]
Well I’m glad I’m not the only one stumped :-)

We had integration with dependency-ci forever.  And the. dependency-ci got bought out by Tidelift.  Then we had integration with both, but dependency-ci was deprecated.  

I deleted the integration eith Tidelift in hopes that it would also eliminate the integration with dependency-ci.  But no luck.

**Comment by tleonhardt** [comment]
I have no idea how to fix this.  I suspect it is going to require a support ticket to GitHub.  Anyone know how to go about creating one of those?

**Comment by kotfu** [comment]
Just submitted an issue via https://github.com/contact. We'll see what happens.

**Comment by kotfu** [comment]
Thanks to Leslie at Github. She pointed out that we probably had dependency-ci as a status check on a protected branch. She was right. I've removed it, which I think will solve this problem. Let's leave the issue open until we merge in another PR to make sure.

**Comment by tleonhardt** [comment]
I verified with current PR #517 that this issue is now fixed.
