### ISSUE TITLE
Fix several hack classes built to simulate file descriptors

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#497]
We have several hack classes built to simulate regular file descriptors. There are at least:

- transcript.py::OutputTrap
- conftest.py::StdOut
- pyscript_bridge.py::CopyStream

These should really be replaced with `StringIO` objects.

**Comment by tleonhardt** [comment]
Agreed.  We should either replace all **stdout** hack classes which simulate file descriptors with ``StringIO`` objects or define a single hack class of this nature and use it throughout.

**Comment by tleonhardt** [comment]
I don't think we can create a simple ``io.StringIO`` object which can handle all cases that ``cmd2`` needs.  ``sys.stdout`` and ``sys.stderr`` are complex File Objects in that they support one interface (``sys.stdout.write``) which acts like a text file and accepts ``str`` and another interface (``sys.stdout.buffer.write``) which acts like a binary file and accepts ``bytes``.  And this is the fundamental crux which has thwarted past attempts at solving this problem.

We will need to support both of these interfaces in our class which simulates the behavior of ``sys.stdout``.
