### ISSUE TITLE
filename autocompletion

### ISSUE THREAD

**Issue by teto** [python-cmd2/cmd2#498]
cmd2 has grown so much since last time I checked. I still have sthg I am not  sure how to achieve: filename completion ? This is the feature I miss the most in my app but I am not sure how to implement it, if there is any out of the box solution in cmd2 ?

**Comment by tleonhardt** [comment]
@teto filename autocompletion is easily achieved.  We debated making it a default behavior given how common of a desire, but we decided against it.  But we do have good documentation and a number of examples demonstrating how to achieve what you wish.

For example, see any of the following:
* [Tab Completion](https://cmd2.readthedocs.io/en/latest/freefeatures.html?highlight=path%20completion#tab-completion) section of the [cmd2 documentation](https://cmd2.readthedocs.io/en/latest/)
* [paged_output.py](https://github.com/python-cmd2/cmd2/blob/master/examples/paged_output.py) example
    * simplest use case
* [python_scripting.py](https://github.com/python-cmd2/cmd2/blob/master/examples/python_scripting.py) example
    * case where you only want to match on directories and not files
* [tab_completion.py](https://github.com/python-cmd2/cmd2/blob/master/examples/tab_autocompletion.py)
    * case where you want to use it specifically for ``argparse`` argument completion
* ``shell_cmd_complete`` method in ``cmd2.Cmd`` class
    * example of using it to complete only directories or executables

**Comment by teto** [comment]
Wow that's cool I had no idea, I had looked at the doc but couldnot find it. The readme does say
`Good tab-completion of commands, sub-commands, file system paths, and shell commands` so that's on me. 
It's good to have examples but one might want to mention them in the doc.
I've been playing a bit with ACArgumentParser and cmd2.Cmd.path_complete.
I wonder why one has to set the possible choices in https://github.com/python-cmd2/cmd2/blob/7a24851d1f2f620229ca41a4a008811d8634f5d1/examples/tab_autocompletion.py#L236, couldn't this be guessed from argparse.add_argument( choices=...) ?

While having such an exhaustive example is good, I find it a bit overwhelming :)

**Comment by tleonhardt** [comment]
@teto 
* [tab_completion.py](https://github.com/python-cmd2/cmd2/blob/master/examples/tab_completion.py) is intended to the the simpler example that most people should look at
* [tab_autocompletion.py]() contains a more in-depth demonstration of advanced features

Perhaps we should rename them to something like **tab_completion_simple.py** and **tab_completion_advanced.py**?

The built-in tab-completion of ``argparse`` arguments does automatically handle the possible choices.  See the ``suggest`` command in **tab_autocompletion.py** for an example.

**Comment by anselor** [comment]
I think the confusion here is the relationship between cmd2 and argparse. Python provides argparse and argparse has the ability to receive a static list of choices for arguments for the purpose of input validation. 
In cmd2 we have an autocompleter module that adds enhanced choice matching on top of argparse. Using setattr, we add additional information to arguments for the autocompleter to properly match dynamic completion choices with argparse arguments for the purposes of tab completion.
If you're using argparse for your commands, you should be able to pass the path_complete() function in to setattr().

**Comment by teto** [comment]
I find strange that the file completion is in the "freefeature" section since the author does need to change his code http://cmd2.readthedocs.io/en/latest/freefeatures.html#tab-completion. That might be a reason why I haven't found it.
My understanding is https://github.com/python-cmd2/cmd2/blob/master/examples/tab_completion.py is for people to provide their own completion while https://github.com/python-cmd2/cmd2/issues/498 uses the ACArgumentParser.
Regarding the choice of the completion helpers (flag_based_complete, index_based_complete), I would have preferred complete_flag_based, complete_index_based since it makes discovery easier through IDE completion.
I've seen the ACArgumentParser autocomplete "choices" arguments which was really cool but it seems to do it only if the parser is given through the decorator @with_argparse, is that correct ? If I just define my ACArgumentParser like 
```
do_stuff(self, args):
     parser = argparse.ACArgumentParser() 
```
then I won't get the autocompletion right ?
This argparse autocompletion is a killer feature, I feel like it deserves better documentation :D (in https://cmd2.readthedocs.io/en/latest/argument_processing.html# maybe) !

**Comment by teto** [comment]
I've updated almost all my commands with the completion, it's so very cool. There is one command that resists me, sadly it's also the one people use the most. I have a do_plot command that loads plots as plugins and adds them as subparsers. This means that when creating the ACArgumentParser, I need to access "self" to add the subparsers, but I am not sure how to do it considering I need to pass the ACArgumentParser via with_argparser to get the autocompletion:

```
parser = argparse_completer.ACArgumentParser(description='Generate MPTCP stats & plots')
# Here I need to use "self"/access instance members when generating the parser
# to create the appropriate subparsers
@with_argparser(parser)
def do_plot(self, cli_args, ):
    ...my code
``


My current code (for information)
```
    def do_plot(self, cli_args, ):

        parser = argparse_completer.ACArgumentParser(description='Generate MPTCP stats & plots')

        subparsers = parser.add_subparsers(dest="plot_type", title="Subparsers",
            help='sub-command help',)
        subparsers.required = True  # type: ignore

        def register_plots(ext, subparsers):
            """Adds a parser per plot"""
            parser = ext.obj.default_parser()
            assert parser, "Forgot to return parser"
            subparsers.add_parser(ext.name, parents=[parser], add_help=False)

        self.plot_mgr.map(register_plots, subparsers)

        cli_args = shlex.split(cli_args)
        args, unknown_args = parser.parse_known_args(cli_args)
        # Allocate plot object
        plotter = self.plot_mgr[args.plot_type].obj
```

**Comment by anselor** [comment]
The impression I'm getting is that users would choose one plotting plug-in and then that plug-in would collect additional parameters needed that are specific to that plotting plug-in, is that correct?

If so, what you can do is use with_argparser_and_unknown_args() for do_plot(), which will collect all of the unrecognized parameters. You'll need to define a custom completion for do_plot. You can have a custom completion function in each of your plugins where you pass the extra parameters. The plug-in can have its own autocompleter that handles all the additional parameters. You'll probably need to handle help in this way as well.

**Comment by anselor** [comment]
Also, I'm really glad you like the autocompleter. I'm the primary author of that feature.

**Comment by teto** [comment]
> The impression I'm getting is that users would choose one plotting plug-in and then that plug-in would collect additional parameters needed that are specific to that plotting plug-in, is that correct?

Yes that's it. I use stevedore (https://docs.openstack.org/stevedore/latest/) to dynamically load plugins - including plots. Each plot is a subclass of Plot (https://github.com/teto/mptcpanalyzer/blob/36aba3a99494f7627482488d4428b4c43d77eb61/mptcpanalyzer/plot.py#L63) with its own parser. In do_plot, I create a parser and add these Plot.parser as subparsers https://github.com/teto/mptcpanalyzer/blob/36aba3a99494f7627482488d4428b4c43d77eb61/mptcpanalyzer/cli.py#L895

I am trying to create a single source of truth via creating an instance parser self.plot_parser so that in complete_plot I can just return the completer of this parser instead of having to manually specify the autocompletion options as  in https://github.com/python-cmd2/cmd2/blob/7a24851d1f2f620229ca41a4a008811d8634f5d1/examples/tab_autocompletion.py#L526. But it doesn't seem to work. I am a bit lost when trying to follow the subcmd_args_lookup path. The comments such as 
```
        # Mapping of a specific sub-parser of the 'type' group to a tuple. Each
        #    tuple has 2 values corresponding what's passed to the constructor
        #    parameters (arg_choices,subcmd_args_lookup) of the nested
        #    instance of AutoCompleter
        library_type_params = {'movie': (None, library_movie_subcommand_groups),
'show': (None, library_show_subcommand_groups)}
```
are not helpful to me but maybe I miss sthg.

**Comment by anselor** [comment]
That particular example is my initial approach to handling sub-commands. It's super complicated and hard to understand. Perhaps exposing that in documentation/examples was a mistake and maybe we should just remove it.

The recommended approach is what I added later - the ability to tag each parameter with its own completer using `setattr()` as you found already. Internally it looks for those attributes and generates that complicated data structure.

When do you load the plugins? Is it on application load or dynamically at run time? Or does it get loaded inside of do_plot(). The `with_argparser()` decorator initializes itself with the argparse parser on class instantiation. If the argparse object is changed later (when you load plugins) I don't think it will get picked up.

If you load plugins on application start up or dynamically at run time, I think this might work.
Looking at how the autocompleter is integrated, it is possible you could call `setattr(self._do_plot, 'argparser', new_parser)` when you load the plugins. I don't have time to try it right now but I _think_ that could make it work. You'll have to duplicate some of the logic in `with_argparser()` to update the some of the properties for better help output. Look at: https://github.com/python-cmd2/cmd2/blob/7a24851d1f2f620229ca41a4a008811d8634f5d1/cmd2/cmd2.py#L243

**Comment by teto** [comment]
Stevedore loads plugins at runtime according to specific "entry_points"  (I define some here https://github.com/teto/mptcpanalyzer/blob/36aba3a99494f7627482488d4428b4c43d77eb61/setup.py#L80). The point is I can load them in the Cmd2 class constructor (https://github.com/teto/mptcpanalyzer/blob/36aba3a99494f7627482488d4428b4c43d77eb61/mptcpanalyzer/cli.py#L191)


> Looking at how the autocompleter is integrated, it is possible you could call setattr(self._do_plot, 'argparser', new_parser) when you load the plugins. I don't have time to try it right now but I think that could make it work. You'll have to duplicate some of the logic in with_argparser() to update the some of the properties for better help output.

Why the leading underscore in _do_plot ? I tried putting a placeholder argparser for do_plot and update it later via `setattr(self.do_plot, 'argparser', self.plot_parser)` but got:

```
    stop = self.onecmd(statement)
  File "/nix/store/hv546m71gfdzhrvlb2b6lbdvv1giyh4q-python3.6-cmd2-0.9.3/lib/python3.6/site-packages/cmd2/cmd2.py", line 1951, in onecmd
    stop = func(statement)
  File "/nix/store/hv546m71gfdzhrvlb2b6lbdvv1giyh4q-python3.6-cmd2-0.9.3/lib/python3.6/site-packages/cmd2/cmd2.py", line 199, in cmd_wrapper
    return func(instance, args, unknown)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 922, in do_plot
    setattr(self.do_plot, 'argparse', self.plot_parser)
AttributeError: 'method' object has no attribute 'argparse'
```
The argparse is an attribute of the wrapped function so it seems tricky. I could definitely use an example (when you get the time).

**Comment by teto** [comment]
That's awesome ! I could make it work. Thanks a lot !!
Closing since I got the basics covered. I might reopen in case I discover a strange behavior but so far so good.
