### ISSUE TITLE
Better document tab-completion of file paths, argparse arguments, etc.

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#500]
``cmd2`` has top-notch tab-completion capabilities that are leaps and bounds above some similar alternatives that make things easy for developers.  However, we haven't always done the best job of making these features discoverable and/or documenting them.

We should do our utmost to make it easy for new ``cmd2`` users to discover and use these capabilities.

Possibilities include:
- Add links to relevant examples to the README and/or Sphinx docs
- Add code snippets demonstrating basic usage to the REAMDE and/or Sphinx docs
- Updated bulleted feature list in README and PyPI to explicitly call out argparse autocompletion

**Comment by teto** [comment]
Slightly related but is it possible to setup a filter for filename autocompletion ? I wonder if it's possible to display matches only for filenames with `pcap` extension for instance.

**Comment by tleonhardt** [comment]
@teto Your feature suggestion is a good one.  I created Issue #590 for it.
