### ISSUE TITLE
Argparse decorators are treating quoted flags as actual flags

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#506]
In the argparse decorators, `parse_quoted_string()` is being called which strips quotes from all arguments before parsing them with argparse. Therefore something like "-s" will be seen as -s.

This behavior is consistent with a Python script using argparse on options sent from the shell (ex: bash) since they also remove quotes first. However it still feels wrong. When I removed the behavior, lots of unit tests fail so we are obviously relying on it.

@kotfu @tleonhardt @anselor 
Do you have any thoughts on this behavior?

**Comment by tleonhardt** [comment]
Apparently the deficiencies in argparse were reported as a bug in 2010 and nobody can figure out how to fix argparse correctly and in a way that would make everyone happy:
https://bugs.python.org/issue9334

That bug ticket is still open!

**Comment by kmvanbrunt** [comment]
Closing since it matches shell behavior
