### ISSUE TITLE
What should show in cmd2 history?

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#545]
@kotfu @tleonhardt 
This question pertains to cmd2's history and not readline's.

Currently we put what the user typed in history. (`statement.raw`) Is there any reason why can't put what was run instead? (`statement.command_and_args`)

That would make it clearer when things like shortcuts and aliases are entered. You will have a record of what actually occurred.

**Comment by kotfu** [comment]
I had this same thought last time I fixed a transcript bug. It's confusing now because you can't see what actually got run when you type an alias. If we switched it it would be confusing because when you   use the history command it won't show what you typed.

What do you think about a developer setting (not a user available setting) which would allow the developer to choose one of these behaviors?

**Comment by tleonhardt** [comment]
As long as it doesn't present too big of a maintenance headache, I like the idea of a developer setting which would allow ability to choose one of these behaviors; because as you discussed there is a potential confusion either way.

**Comment by kmvanbrunt** [comment]
What would the default be?

**Comment by kotfu** [comment]
I think the default should be to put what the user typed into the history. That's what cmd.cmd does, and that's what cmd2 has done thus far. 

We need to proceed carefully here. A quick look at the code indicates that we could easily break transcripts by messing with this. `statement.command_and_args` excludes any output redirection clauses the user typed. Our current unit tests don't cover these types of scenarios very well, so if we proceed to make a change, I suggest we create more robust history and transcript tests, and then once those are committed and passing with no code changes to `cmd2.Cmd`, then we can start to implement this new setting.

A completely different alternative might be to add a new command line switch to the history command, which outputs the commands with shortcuts and aliases expanded. This would make it explicit, available to the user, and wouldn't break any existing functionality.

**Comment by kmvanbrunt** [comment]
What about adding a member to `HistoryItem` that's the resolved command? The history output could somehow print both if the `raw` is different than `command_and_args`.

**Comment by kmvanbrunt** [comment]
Even if we add flags to the `history` command, I believe we still need to store both the `raw` and `command_and_args` values in `HistoryItem`. That way we only have to resolve the command once.

Plus, a user's parsing hooks might be dependent on state and resolve a command differently if run again. Therefore we need to store what was resolved at the time the user ran it.

**Comment by tleonhardt** [comment]
Excellent conversation and suggestion!  So here is my summary and proposal of what we want to do moving forward:

* By default the **history** command will print what the user typed, just like it does now
* A new ``-x/--expanded`` flag will be added to the **history** command which expands aliases, macros, and shortcuts to show the fully-resolved command which got executed
    * Note: ``-e`` was already taken for ``--edit``
* A new ``-v/--verbose`` flag will be added to the **history** command which will output both what the user typed and the fully resolved command
* The ``HistoryItem`` class will be modified to store both what the user typed and the resolved command
* The separators between history items in the printout will be removed and we will switch to a more bash-like presentation that starts with a right-aligned number followed by a left-aligned command

Does that work for everyone?  Or is there something you thing should be different?

**Comment by lancestarr** [comment]
In my ideal world, `history -v` would always show the raw command first, then, _only if the expanded command differs_, show it also. I'd have to play with it to see whether I'd prefer the expanded command in a separate column (that is, the output would be in tabular format) or simply enclosed in parentheses or some other begin-end pair of characters. My main point is to get rid of the possible interpretation that it would **always** show both commands, even if they were identical. Given the other two ways to run the history command, I see no need for showing the duplicate information.

These flags will combine with the _script output_ flag to remove the command numbers.

Do they also need to combine with the transcript output? I believe so--at least for the `-x` flag--but I bring it up just to see if anyone really cares about the transcript output. The help text for it is confusing and @kmvanbrunt and I weren't able to fix it or figure out (in the twenty seconds we spent on it) what it was really supposed to do. Does it save the results from every command you've run so it can show the results to you again? Does it rerun the commands? Or am I just confused about what it's supposed to do? Anyway, I figured one way to quell some of the confusion would be to eliminate it.

**Comment by kotfu** [comment]
I like all of this. One suggestion: lets add a deep copy of the Statement object to the HistoryItem instead of raw, command and args, etc. That way we are sure to have everything we might ever need, and can continue to encapsulate any code to split/join parts of the statement into that class.

**Comment by kotfu** [comment]
@kmvanbrunt you are currently assigned to this issue, are you OK if I work on it?

**Comment by kmvanbrunt** [comment]
@kotfu I'm definitely OK if you'd like to work on it.

I did some work already on the history branch and accomplished the following:

1. Added **Statement** member to **HistoryItem** class
2. Added -v to **history** command that shows both the raw and expanded commands when they differ
3. Changed history output to look more like bash
4. Added `expanded_command_line()` property to **Statement** class that attempts to piece together the full expanded command with redirection and stuff
5. Updated unit tests to work with the updates to **HistoryItem**

Honestly I've run into some stumbling blocks which I'll list

1. The output of **history -v** is ugly.
2. I haven't added the **-x** flag to **history** yet. That one should make it possible to do all things the history command currently does, but on expanded commands.
3. I added the -v flag to the `history_parser_group` since it seems like it should be independent of the other flags. However, the -x flag seems like it shouldn't be part of that group since it affects how all the flags would function. This means that -x and -v wouldn't be mutually-exclusive according to argparse. So what happens if a user has both of them on the command line?
4. What happens if a user searches history (string and regex) using the -v flag? Will that search both the raw and expanded commands? 
5. The -e, -s, and -o flags of **history** command need to be updated to convert multi-line commands into one line before placing them in script format. Text scripts process one line at a time and therefore cannot properly handle a command split over multiple lines.
6. When I print the output of -v, I check if the expanded command differs from the raw command to determine if the expanded one is printed. In multi-line commands, this is always the case since the `expanded_command_line()` property doesn't contain newlines. Perhaps we should remove the newlines in raw before doing the string compare.

I'll go ahead and assign this issue to you. If you find my current approach isn't what you had in mind, I won't be offended if you start from scratch. Otherwise, just take over the history branch. I've been merging master into it regularly, so it's in a good state.

**Comment by kmvanbrunt** [comment]
@kotfu How are things going on the history stuff?

**Comment by tleonhardt** [comment]
@kotfu @kmvanbrunt I merged all of the latest changes from *master* onto the *history* branch since I put out the 0.9.8 release last night.  

One way or another, we should make sure we finish addressing this issue for the next release.

**Comment by kotfu** [comment]
Making good progress, I think I've got most of it working, expect for the multiline issues (listed by @kmvanbrunt as stumbling blocks 5 and 6 above). I'm trying out an output format for `history -v` that looks like bash, but if the expanded command is different than the entered command, it is displayed as the number followed by an `x`, like this:
```
(Cmd) alias create sc shortcuts
Alias 'sc' created
(Cmd) sc
Shortcuts for other commands:
!: shell
&: speak
?: help
@: load
@@: _relative_load
(Cmd) history -v
    1  alias create sc shortcuts
    2  sc
    2x shortcuts
```

My thinking is that if you want to process the output of the history command with the shell, this approach lets you easily find the expanded commands with grep, while still allowing you to see what command number they were. If you want to ignore expanded commands with the shell processing, you can grep for the number followed by a space. What do you think about this format for the output?

**Comment by kmvanbrunt** [comment]
@kotfu I like that format.

**Comment by tleonhardt** [comment]
@kotfu @kmvanbrunt I just merged the lastest stuff from the *master* branch into the *history* branch and resolved conflicts.  You guys might want to check and make sure you agree with how I resolved the conflicts.

But on another note, I noticed that the tests on the *history* branch run significantly slower and it appears to be due to a single test:  **test_exclude_from_history**.  We may want to spend a little bit of time trying to improve the performance of this test.

**Comment by tleonhardt** [comment]
I fixed the unit test problem.  I had just messed up one of the merge conflicts and missed out on a previous unit test fix.

**Comment by tleonhardt** [comment]
@kotfu @kmvanbrunt I just pushed some changes to the *history* branch which contain potential fixes for the existing multiline command issues.  The modified behavior is shown as exercised using the **colors.py** example script and it's ``orate`` multiline command:

```sh
14:50 $ examples/colors.py
(Cmd) orate foo
> bar
> "baz gee"
>
foo bar baz gee
(Cmd) history
    1  orate foo bar "baz gee";
(Cmd) history -s
orate foo bar "baz gee";
(Cmd) history -x
    1  orate foo bar "baz gee";
(Cmd) history -v
    1  orate foo
bar
"baz gee"
    1x orate foo bar "baz gee";
(Cmd)
```

In all cases other than "-v", multiline commands are shown in a single line with a default terminator character manually appended.  This makes it safe to use multiline commands with -e, -o and -s flags.  But this allows users to get access to the "raw" multiline input with -v if they really want to.

I intentionally broke with showing the raw input with the base option (no flags) because showing multiline output there made it look ugly and broke up the 1 command per line flow.

Let me know what you guys thing.  This is one potential solution, though there are others.  If you are ok with it, then I think we really only need to add a few unit tests before this is ready for a PR.

**Comment by tleonhardt** [comment]
I pushed another change to the *history* branch where I fixed a couple minor bugs in and added unit tests to cover the ``Statement.expanded_command_line`` method.
