### ISSUE TITLE
Some pytest unit tests are not fully isolated

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#547]
In the past few days, it has become apparent that under certain circumstances, some state is being preserved while executing the ``pytest`` unit tests and hence the unit tests are not fully isolated from each other.  This has resulted in some limited unit test failures and caused refactoring other unit tests so that they do not fail.

Regardless, we need to understand the underlying cause of the problem and figure out if this is a new problem or not.

@kmvanbrunt @lancestarr 
Would one of you gentlemen please add more information?

**Comment by kmvanbrunt** [comment]
I've gone as far back in the git log as May just to see if this is a new problem. It existed then as well.
Easy way to resproduce this is by adding the following line to the top of `test_alias_create_with_quotes()`
`assert(len(base_app.aliases) == 0)`

That will fail because `base_app` has the aliases created in `test_alias_create()`.

**Comment by tleonhardt** [comment]
Someone on the [Test Podcast Slack channel](https://testpodcast.slack.com) recommended using the following flag to list the fixture setup and teardown calls in the order they execute in:
```sh
py.test --setup-show
```

**Comment by tleonhardt** [comment]
Here is some further information.  In the above, I tried replacing the call to ``run_cmd`` with a call to ``onecmd_plus_hooks`` and the same problem still existed.

Then I tried replacing it with a call to ``onecmd`` instead and the problem was still there.

Finally, I replaced it directly with a call to ``do_alias`` and the problem was gone.

**Comment by tleonhardt** [comment]
To try to simplify things a little, I modified the same section of **test_cmd2.py** on the *master* branch to look like the following:
```Python3
class MyApp(cmd2.Cmd):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class YourApp(cmd2.Cmd):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

def test_alias_create():
    my_app = MyApp()
    my_app.stdout = utils.StdSim(my_app.stdout)
    line = 'alias fake pyscript'
    statement = my_app._complete_statement(line)
    my_app.do_alias(statement)
    assert True

def test_alias_create_with_quotes():
    your_app = YourApp()
    assert (len(your_app.aliases) == 0)
```

This still reproduces the identical issue.

**Comment by tleonhardt** [comment]
The problem appears to be that ``aliases`` is a class attribute within the ``cmd2.Cmd`` class, but it should be an instance attribute.
