### ISSUE TITLE
CommandResult is False for cmd2 built-ins

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#566]
Since no built-in **cmd2** command fills out `self._last_result`, `CommandResult` is always **False** when running these commands in `pyscript`.

**Comment by kmvanbrunt** [comment]
Consider changing CommandResult.__bool__ to:

```py
def __bool__(self):
    """If data has a __bool__ method, then consider it when determining success of command"""
    if self.data is not None and callable(getattr(self.data, '__bool__', None)) and not self.data:
        good_data = False
    else:
        good_data = True

    return not self.stderr and good_data
```

Or we could only consider `self.data` and ignore `self.stderr` if `self.data` has a `__bool__()` method.

**Comment by tleonhardt** [comment]
The first of your code snippets above seems reasonable to me.

**Comment by lancestarr** [comment]
If the first code snippet is good, please consider optimizing it. Start
with if self.stderr return False. (I can't see the code on my phone right
now, so that may not be quite correct, but the idea should be right.)

Lance

**Comment by kmvanbrunt** [comment]
Is it really an error if the user's data says everything was fine? What if they printed things like a warning message to stderr?

**Comment by tleonhardt** [comment]
We get to decide what writing something to stderr means and as long as we document and communicate to end users how this behaves then I don't think there is any particular "right" or "wrong" answer.
