### ISSUE TITLE
Goals for 1.0 release of cmd2

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#572]
What are and/or should be our goals for a 1.0.0 release of ``cmd2``?  This issue is for discussing that topic.

Tentatively, my goals for a 1.0 release are as follows:
1. Stabilize the API so we don’t have many deletions or deprecations in the future
1. Make any remaining big changes we want before this
1. Improve documentation
1. Release 1.0 when it is ready
1. Once 1.0 has been released, do a better job of making its existence known in the community

The following Milestones were created to work towards whatever goals we mutually agree to:
* 0.9.14 - Get any remaining “big changes” into this release if possible.  Any remaining deprecations prior to 1.0.0 should go in this release.  We should also strive to fix as many known bugs as possible in this release.
    * July 2019
* 0.9.15 - Last release prior to 1.0.0. No further deprecations, but deletion of previously deprecated OK.  We should strive hard to have a stable API at this point.
    * August 2019
* 1.0.0 - Stable 1.0.0 release ready for wide usage.  Bug fix and polish release. Focus on documentation improvements, bug fixes, etc. but not major new features. No deletions or deprecations.
    * September 2019

**Comment by marklalor** [comment]
For 0.9.9, can there be discussion about some high-level documentation ideas, like the order that documentation is presented in. As an example, I think tab completion should be higher up in the "Features requiring no modifications" section. I'm sure there are plenty of things of that nature that I haven't thought about.

**Comment by tleonhardt** [comment]
I like he idea of having a discussion for the 0.9.9 release about how to best improve the existing documentation.  A significant reorganization would be beneficial - we have added a lot over time, but haven’t made the effort to go back and reorder things.

I think that documentation improvements are **the** most important improvements we can make for a 1.0.0 release.

**Comment by tleonhardt** [comment]
I'm going to close this since I think the goals are clear and the only thing really remaining is to improve the documentation a bit further, and there is another ticket for that open.
