### ISSUE TITLE
0.9.5 broke something with cmdloop()

### ISSUE THREAD

**Issue by marklalor** [python-cmd2/cmd2#577]
Has anything been changed recently regarding the cmdloop command or some of the core loop functionality? It seems that upgrading from `0.9.4` to `0.9.5` broke my existing program. The `cmdloop` method seems to just return.

```
mark@charmander:~/.local/bin$ ls
chardetect  clanvas  html2text  tabulate
mark@charmander:~/.local/bin$ ./clanvas
mwl58@canvas.case.edu:~:~/.local/bin $ lc
EECS455-13682
EECS428-15077
EECS444-14976
EECS341-14990
mwl58@canvas.case.edu:~:~/.local/bin $ quit
mark@charmander:~/.local/bin$ pip3 install -U cmd2
Collecting cmd2
  Using cached https://files.pythonhosted.org/packages/5f/c9/f45aeb4b0c24413f00084d9e46f90a52717acaa9fc3fb2a9ce67b90d334b/cmd2-0.9.5-py3-none-any.whl
Collecting attrs>=16.3.0 (from cmd2)
  Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Collecting colorama (from cmd2)
  Using cached https://files.pythonhosted.org/packages/0a/93/6e8289231675d561d476d656c2ee3a868c1cca207e16c118d4503b25e2bf/colorama-0.4.0-py2.py3-none-any.whl
Collecting pyperclip>=1.5.27 (from cmd2)
Collecting wcwidth; sys_platform != "win32" (from cmd2)
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Installing collected packages: attrs, colorama, pyperclip, wcwidth, cmd2
Successfully installed attrs-18.2.0 cmd2-0.9.5 colorama-0.4.0 pyperclip-1.7.0 wcwidth-0.1.7
mark@charmander:~/.local/bin$ ./clanvas
mark@charmander:~/.local/bin$ echo ":("
:(
```

It seems like stuff not through `cmdloop` will run as usual though.

```
mark@charmander:~/.local/bin$ python3
Python 3.6.6 (default, Sep 12 2018, 18:26:19)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from clanvas import clanvas
>>> cmd2 = clanvas.Clanvas()
>>> cmd2.cmdloop()
>>> cmd2.onecmd('help')

Documented commands (type help <topic>):

Clanvas
=======
catann  cc  la  lann  lc  lg  login  pullf  ua  whoami  wopen

Other
=====
alias  edit  history  macro  pyscript  set    shortcuts
cd     help  load     py     quit      shell

>>>
```

All this tested on a fresh install of Ubuntu 18.04.1

**Comment by kmvanbrunt** [comment]
@marklalor Sorry something isn't working. I'll get a copy of Clanvas from your github page to test.

Also, check [CHANGELOG.md](https://github.com/python-cmd2/cmd2/blob/master/CHANGELOG.md) for anything that would break your software.

**Comment by marklalor** [comment]
> @marklalor Sorry something isn't working. I'll get a copy of Clanvas from your github page to test.
> 
> Also, check [CHANGELOG.md](https://github.com/python-cmd2/cmd2/blob/master/CHANGELOG.md) for anything that would break your software.

Right, I will try debugging by stepping into `cmdloop` when I get some time to see why cmdloop is returning. I assumed it must be a cmd2 issue because it stopped working after a version update, and I don't think I was using anything that was deprecated/removed in 0.9.5, but perhaps I am doing something wrong and it just happened to work with 0.9.4.

I probably should have debugged a bit more before submitting an issue here, I don't mean to burden you with pulling a copy of my software and testing it. I was hopefully looking to find out if something  changed between 0.9.4 and 0.9.5 that didn't make the changelog.

**Comment by kmvanbrunt** [comment]
@marklalor Perhaps you can help me get Clanvas working. Every time I try to run it, I get this error.
I've tried running it within a Python shell and by calling clanvas from the pip bin directory.

```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from clanvas import clanvas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kevin/.local/lib/python3.5/site-packages/clanvas/clanvas.py", line 128
    self.poutput(f'cd: no such file or directory: {path}')
                                                        ^
SyntaxError: invalid syntax
```

**Comment by marklalor** [comment]
@kmvanbrunt It requires python 3.6+ for the f-strings.

**Comment by kmvanbrunt** [comment]
Oh, stupid Debian is stuck at 3.5. I'll set up an Anaconda environment to test.

**Comment by marklalor** [comment]
Ah I think I found out where the problem is. Although I'm not completely sure what is causing the problem that breaks out of the loop. It seems like it jumps into the finally block because of a problem.

What Clanvas does: I wanted to make my prompt dynamic, so I I made the prompt variable delegate to a method: [See here](https://github.com/marklalor/clanvas/blob/563577d778ae4b582762603e5b1763c7b5e4b412/clanvas/clanvas.py#L89)

It looks like `pseudo_raw_input` [saves the prompt in a temporary variable](https://github.com/python-cmd2/cmd2/blob/11bc029a20168312eaa999e62b45989b6b1d11ef/cmd2/cmd2.py#L2079):

```
orig_prompt = self.prompt
self.prompt = prompt
```

It looks like this ends up setting orig_prompt to the literal string value that is returned which will definitely cause some problems, but I guess there is some other problem that actually causes the loop to exit.

Looks like this code doesn't exist in the most recent commits on the master branch though.

**Comment by marklalor** [comment]
> Looks like this code doesn't exist in the most recent commits on the master branch though.

In fact, I tried running everything with the latest `cmd2` from the master branch, and Clanvas works again.

**Comment by kmvanbrunt** [comment]
Are you serious? I actually removed that code about an hour after doing the 0.9.5 release because it caused an issue for me as well. Sorry that broke your stuff, too.

**Comment by tleonhardt** [comment]
If it was problematic for both of you, chances are it will be for others and we should put out the 0.9.6 release very soon.

**Comment by kmvanbrunt** [comment]
It was fixed in #575.

**Comment by kmvanbrunt** [comment]
@marklalor I have one more PR. When its merged in, I'll release 0.9.6 with the bug fix. Hopefully that will be today.

**Comment by marklalor** [comment]
@kmvanbrunt ok nice, don't rush yourself though, I just updated Clanvas to use 0.9.4 for now so it's really quite fine on my end.

**Comment by tleonhardt** [comment]
@marklalor The 0.9.6 release of cmd2 is now available via pip/PyPI.  Can you please verify that this works well with Clanvas?

**Comment by marklalor** [comment]
Yup! Works again with 0.9.6.
