### ISSUE TITLE
Improve path_complete to filter by file extension and/or glob pattern

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#590]
Currently the **path_complete()** method of ``cmd2.Cmd`` provides path-based tab-completion.  It currently has the ability to filter results to either:
* Directories only
* Directories and executables only

It would also be beneficial in some circumstances if it had the ability to filter by file extension and/or glob pattern.

For example, suppose a user wants a command which will only tab-complete files that end in *.pcap*.

**Comment by teto** [comment]
I think a nice UI would be to let the user pass a function which accepts as parameter the filename and returns a bool (as to wether the inode is a valid completion candidate or not).

**Comment by kmvanbrunt** [comment]
I was thinking something like this.

```Python
class PathCompleteConfig:
    class ResultType(Enum):
        ALL,
        DIR_EXE,
        DIR_ONLY

    def __init__():
        self.result_type = ResultType.ALL

        # Filters file names unless result_type is DIR_ONLY, then it filters directory names 
        self.filters = []

def path_complete(self, text: str, line: str, begidx: int, endidx: int,
                  config: Optional[PathCompleteConfig])
```

Maybe `PathCompleteConfig.filters` could either be a list or a function?

**Comment by tleonhardt** [comment]
@kmvanbrunt Yeah, I'm fine with you deleting those current flags as long as the new API is equally as simple and more likely to remain stable.

I also really like @teto's idea passing in a filter function which returns a bool.  I envision it something like this:
```Python3
def path_complete(self, text: str, line: str, begidx: int, endidx: int,
                                 filter: Optional[Callable[[str], bool]]=None) -> List[str]:
```
