### ISSUE TITLE
Strip escape codes when redirecting via ppaged()

### ISSUE THREAD

**Issue by ethanmcc** [python-cmd2/cmd2#594]
Is there a reason ppaged doesn't strip escape codes when redirecting? Could look into creating a patch if it would be welcome.

**Comment by tleonhardt** [comment]
No good reason that I can recall.  Id say there is a high probability that we simply forgot to replace that self.stdout.write call with one to self.decolorized_write.

So yes, a PR would be welcome.  Thanks for reporting this Issue!
