### ISSUE TITLE
Pass a custom Namespace to args

### ISSUE THREAD

**Issue by teto** [python-cmd2/cmd2#596]
Kind of a follow up on https://github.com/python-cmd2/cmd2/issues/498

I want to pass a custom Namespace when parsing arguments while keeping the autocompletion:

```
    @with_argparser(parser)
    def do_load_pcap(self, cmdline):
          myNamespace = Namespace()
          myNamespace.toto = self.data
          args = parser.parse_args(shlex.split(cmdline), myNamespace)
          
```
I modified 
https://github.com/python-cmd2/cmd2/blob/b6c39365e0331ab64aad074565fe73fb074a3a7f/cmd2/cmd2.py#L270-L271
so that it doesn't parse stuff.
```
def with_argparser_test(argparser: argparse.ArgumentParser,
                   preserve_quotes: bool=False) -> Callable[[argparse.Namespace], Optional[bool]]:
    """A decorator to alter a cmd2 method to populate its ``args`` argument by parsing arguments
    with the given instance of argparse.ArgumentParser.

    :param argparser: unique instance of ArgumentParser
    :param preserve_quotes: if True, then arguments passed to argparse maintain their quotes
    :return: function that gets passed the argparse-parsed args
    """
    import functools

    # noinspection PyProtectedMember
    def arg_decorator(func: Callable[[Any], Optional[bool]]):
        @functools.wraps(func)
        def cmd_wrapper(instance, cmdline):
            # lexed_arglist = parse_quoted_string(cmdline, preserve_quotes)
            # try:
            #     args = argparser.parse_args(lexed_arglist)
            # except SystemExit:
            #     return
            # else:
            return func(instance, cmdline)

        # argparser defaults the program name to sys.argv[0]
        # we want it to be the name of our command
        # argparser.prog = func.__name__[len(COMMAND_FUNC_PREFIX):]

        # If the description has not been set, then use the method docstring if one exists
        if argparser.description is None and func.__doc__:
            argparser.description = func.__doc__

        # Set the command's help text as argparser.description (which can be None)
        # cmd_wrapper.__doc__ = argparser.description

        # Mark this function as having an argparse ArgumentParser
        setattr(cmd_wrapper, 'argparser', argparser)

        return cmd_wrapper

    return arg_decorator

```
which can be used like
```
    @with_argparser_test(parser)
    def do_load_pcap(self, args):
        """
        Load the file as the current one
        """
        args = shlex.split(args)
        parser = self.do_load_pcap.argparser
        args = parser.parse_args(args)
        
        self.poutput("Loading %s" % args.input_file)

```

I wonder if cmd2 could propose some better interface. This is just an example, that adds a parameter "dont_parse" to the with_argparser decorator. If it's true, cmd2 could pass the parser along to the member function (instead of `parser = self.do_load_pcap.argparser` which requires some knowledge about cmd2 implementation)
```
@with_argparser(dont_quote, dont_parse=True)
def func(self, parser, args):
      parser.parse_args(args)
```

**Comment by tleonhardt** [comment]
@teto I don't understand your motivation.  What capability do you want that our current ``argparse`` decorators don't support?  If you are going to end up parsing the command line arguments with ``argparse`` anyways inside your command method, why not just let one of our decorators do it for you?

If you can explain your use case and it is something that would also plausibly make sense for other users, then I would be happy to create an additional decorator that accepts an ``argparse.ArgumentParser`` and uses it for tab-completion purposes but doesn't parse the command line args and simply passes both the command line arguments and the parser to the method.  The hardest part of that would likely be coming up with a good name for the new decorator.  I would strongly prefer to not combine this functionality with the existing decorator via an optional argument as I think that could lead to confusion for users.

But for starters, please explain your motivation further and why you can't accomplish what you want with ``cmd2`` as it exists now ...

**Comment by teto** [comment]
sorry if I was not clear: parse_args accepts a Namespace as an optional second parameter https://docs.python.org/3.7/library/argparse.html#argparse.ArgumentParser.parse_args . How can I pass a Namespace as a parameter while keeping autocompletion with the current UI ?

Now if your question is why do I need to pass a custom Namespace, it is because it allows me to pass information belonging to the instantiated class (self.data) and that my parser has custom actions operating over class member variables.

**Comment by kmvanbrunt** [comment]
How about something like: `@with_argparser_for_completion(parser)`?
 It would only need one argument, since preserve_quotes doesn't apply.

**Comment by kmvanbrunt** [comment]
@teto In your example, you've commented out code that would affect help text generation.
Ex:
`# argparser.prog = func.__name__[len(COMMAND_FUNC_PREFIX):]`
`# cmd_wrapper.__doc__ = argparser.description`


What's the reason for this?

**Comment by teto** [comment]
no reason :) just experimenting leftover

**Comment by tleonhardt** [comment]
@teto 
Thanks for clarifying your use case - it makes sense to me now.

@kmvanbrunt 
I like the name ``@with_argparser_for_completion(parser)`` and think that adequately captures the intent.

**Comment by teto** [comment]
I wonder on how best to implement that. Right now I have in my code a few parsers that reference member variables which isn't possible/straightforward with the current API.

I wonder if it would be possible instead of proving a parser, to provide a function to generate the parser instead
```
@with_argparser_for_completion(generate_parser)
def do_dump_pcap(self, ...) :
```
with 
`def  generate_parser(self) -> argparse.ACArgumentParser():`
so that it can access the instance data.

**Comment by tleonhardt** [comment]
If we go the route of providing a function to generate the parser instead I would prefer to make it so that ALL of the ``argparse`` decorators in ``cmd2`` are capable of accepting either an ``argparse.ArgumentParser`` OR a callable which returns an ``argparse.ArgumentParser``.

**Comment by kmvanbrunt** [comment]
@teto Since the wrapped functions are created before any instances of the class, I don't see a way to pass the generator function to them since `generate_parser()` needs to be passed `self`.

I still think the original idea of `@with_argparser_for_completion(parser)` will meet your original request. What do you think?

**Comment by kmvanbrunt** [comment]
@tleonhardt @teto The decorators can already be used with a function that returns an ArgumentParser as long as that function doesn't require `self`.

```Python
def generate_parser() -> argparse.ArgumentParser:
   return argparse.ArgumentParser()

@with_argparser(generate_parser())
def do_dump_pcap(self, ...) :
```

**Comment by kmvanbrunt** [comment]
@teto This ticket has sat longer than usual because I'm still thinking about the best solution. While adding a third decorator will certainly work, I hate passing the burden of parsing the arguments to the programmer. That opens up too many future maintenance issues.

As I understand it, you have a Namespace that contains state data used by the parser and therefore want that Namespace passed into `parse_args`.

I have another idea that involves adding an optional parameter specifying the name of a Namespace to both existing decorators.

```Python
@with_argparser(parser, namespace='myNamespace')
```

The assumption is that `myNamespace` would be an instance variable in your **cmd2** class. Then in the `cmd_wrapper()` function of the **argparse** decorators we could call `getattr()` on `instance` and verify it returns an argparse.Namespace. If so then we could pass the Namespace into `parse_args`.

@tleonhardt What are your thoughts on this?

**Comment by kmvanbrunt** [comment]
@teto The approach I suggested (providing the Namespace name) leaves the burden on the programmer to reset the Namespace between commands. That would get annoying. So here is yet another suggestion. This one is based on your idea of providing a generator function to create the parser.

Write a method that generates your namespace:
```Python
def generate_namespace(self) -> argparse.Namespace:
    myNamespace = Namespace()
    myNamespace.toto = self.data
```

Provide the name of that method to the decorator.
```Python
@with_argparser(parser, ns_generator='generate_namespace')
```

Then `cmd_wrapper()` would resolve the method with:
```Python
getattr(instance, ns_generator, None)
```

@teto @tleonhardt Thoughts?

**Comment by teto** [comment]
hum this doesn't solve the problem of passing a custom namespace, yet still a cool API imo

**Comment by kmvanbrunt** [comment]
The decorators do a lot more than could be provided in parser_XXX functions. Most important is the `cmd_wrapper` functionality that allows developers to call do_XXX functions and have the argparse logic work seamlessly. In addition they tie a parser to each do_XXX function which is used by help, sub-command, tab completion, and scripting code.

Because parsers are tied to class functions, they aren't meant to be instance-specific. If you need your parsers to see instance data, then a Namespace is the best place to store it. I also like adding Namespace support because **cmd2** shouldn't be blocking argparse functionality.

Adding an optional namespace provider method to the decorator as described earlier will solve the issue of passing instance data to a non-instance parser.

**Comment by tleonhardt** [comment]
If anything, I would strongly prefer to move **more** to a decorator-based API in lieu of moving away from decorators for argument parsing.

I really love the way [click](https://click.palletsprojects.com/en/7.x/) works where you can define options via decorators and it composes a parser for you.

**Comment by tleonhardt** [comment]
@teto Is this issue something you would like us to keep open for consideration?

**Comment by teto** [comment]
I've got my own solution that works for now https://github.com/teto/mptcpanalyzer/blob/4d90a6917373037d00f8192a3a85969f6d45fc3e/mptcpanalyzer/parser.py#L123 but I am not 100% I won't tweak it again so I am wary of pushing anything to cmd2. Once I am fully satisfied with the API, I will reopen it.

**Comment by teto** [comment]
upon updating to next cmd2, I got annoyed by my custom argparse copied from cmd2 just to change 3/4 lines https://github.com/teto/mptcpanalyzer/blob/7a82031202e470cb08a46da93fe788a2978e113b/mptcpanalyzer/parser.py#L144 . I think cmd2 should provide parity with plain argparse facilites (for release 1.0). 

I haven't thought about the design much but @with_argparse could accept a callback to parse the arguments or alternatively the doc could explain how to get autocompletion using the parser as a member rather than as a decorator.

**Comment by kmvanbrunt** [comment]
I still prefer the following approach to allow a custom namespace during parsing:

Write a method that provides your namespace:
```Python
def generate_namespace(self) -> argparse.Namespace:
    myNs = argparse.Namespace()
    if preload_pcap:
        myNs._dataframes = {"pcap": instance.data}
    return myNs
```

Pass the that method to the decorator.
```Python
@with_argparser(parser, ns_provider=generate_namespace)
```

Then `cmd_wrapper()` would then do something like:
```Python
if ns_provider is not None:
    ns = ns_provider(instance)
else:
    ns = argparse.Namespace()

args = argparser.parse_args(parsed_arglist, ns)
```
