### ISSUE TITLE
Cannot override self.default() without numerous imports. 

### ISSUE THREAD

**Issue by mlongval** [python-cmd2/cmd2#603]
Hi folks. 

I use cmd2 in a program to manage my patient notes (medical records). 
I wrote it initially with the old cmd library. 

In my program I override the self.default() method to this: 
```
def default(self, line):
 """Called when unrecognized command is entered on the command line.
    By default it will run select on the entered string.
    This has the effect that just typing the patient
    name will search for it."""

    print("Unrecognized command. Running select")
    self.do_select(line.strip())
```
Please note that 'self.do_select()' is NOT the same one that is in cmd2 (I don't think I knew there was a do_select() in the old cmd when I wrote my program.) My do_select() searches my database using the supplied string. 

Anyway what I want to happen here is that when I type in something that is not recognized as a command for the interpreter, it will assume that what I want is for it to search for the string in the patient database. It is simply a shortcut. I can thus type: 
```
> silver.john
and it would be as if I typed:
> select silver.john
```
My problem is that with the new cmd2 library, if I override self.default(), to simply send a string to self.do_select() like in the old version I have to somehow get the string from 'Statement', which must be imported, like in the main cmd2.py file. 
I would like to keep the imports to a minimum. 
```
from .parsing import StatementParser, Statement, Macro, MacroArg
```
Is there a way to get the current command string without importing Statement?
Anyway I'm sorry if I'm bothering you with this, I'm not a programmer, just an old family doc.

**Comment by mlongval** [comment]
Ok so I kind of found a way to fix this:
(I also changed the function from 'select' to 'search') 

```
def default(self, whatever):
 """Called when unrecognized command is entered on the command line.
    By default it will run search on the entered string.
    This has the effect that just typing the patient
    name will search for it."""

    print("Unrecognized command. Running search")
    self.do_search(whatever.raw.strip())
```
Sorry to have bothered you with this.

**Comment by tleonhardt** [comment]
Hi @mlongval,

Thanks for both bringing a potential issue to our attention and solving your own problem ;-)

Your solution is exactly what I would recommend if you to search for a multi-word name.  If you only wanted to search for a single-word name then you could do ``whatever.command`` instead of ``whatever.raw.strip()``.

If there is anything else we can do to help, let us know.  But it looks like you have things figured out, so I'm going to close this issue for now.
