### ISSUE TITLE
Fix pytest warnings

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#606]
``pytest`` 4.x has warnings that should be addressed, including **mock** being deprecated and replaced by **mocker**.

**Comment by kotfu** [comment]
How did you see these warning? `pytest -Wa` gives just one, and it doesn't have anything to do with **mock**. I rebuilt new cmd2 envs using current packages, and I get no errors or warnings. Python 3.7.1, pytest 4.0.1 and pytest-mock 1.10.0.

**Comment by tleonhardt** [comment]
I ran ``pytest`` from the **master** branch on macOS with:
* Python 3.7.1
* pytest 4.0.1
* pytest-mock 1.10.0

It gives the following warnings:
```sh
================================================== warnings summary ==================================================
tests/test_bashcompletion.py::test_invalid_ifs
  /Users/toddleonhardt/anaconda/envs/py37/lib/python3.7/site-packages/pytest_mock.py:177: DeprecationWarning: "mock" fixture has been deprecated, use "mocker" instead
    DeprecationWarning)

tests/test_bashcompletion.py::test_fail_alt_stdout
  /Users/toddleonhardt/anaconda/envs/py37/lib/python3.7/site-packages/pytest_mock.py:177: DeprecationWarning: "mock" fixture has been deprecated, use "mocker" instead
    DeprecationWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

But our CI systems all show additional warnings, see the latest [AzurePipelines build](https://python-cmd2.visualstudio.com/cmd2/_build/results?buildId=557) for an example.

**Comment by kotfu** [comment]
I installed `argcomplete`, got the **mock** deprecation warnings, and fixed them. I only got the deprecated escape sequence warnings on one run of pytest. I didn't change any code, ran pytest again, and didn't get the warnings. I tried to figure out why, but to no avail. I've fixed the escape sequence warnings too, but I'm puzzled why they show up in CI, but not always in my dev environment. 🤔
