### ISSUE TITLE
Investigate reducing complexity of cmd2.Cmd.complete method

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#608]
The ``cmd2.Cmd.complete`` method is currently around 215 lines of code (including whitespace and comments).  It is certainly more than can fit on the screen and is quite complex.  We should investigate simplifying this however possible.  Extracting some private helper methods is one likely approach.

If we are able to simplify it, then we should lower the maximum cyclomatic complexity tolerated by our ``flake8`` check.

**Comment by tleonhardt** [comment]
@kmvanbrunt If you don't have any bright ideas for how to achieve this, I recommend just closing this Issue as it was simply aspirational in nature to begin with.

**Comment by kmvanbrunt** [comment]
@tleonhardt I haven't had time to look at it, but I'm sure it would involve breaking the function up and passing state data between the resulting functions.

**Comment by tleonhardt** [comment]
I'm going to close this because I don't think it is a high priority and we have plenty of other stuff to worry about.
