### ISSUE TITLE
The select() method needs to check for a user response of 0.

### ISSUE THREAD

**Issue by jpaul** [python-cmd2/cmd2#611]
The select() method presents a numbered list, starting with "1", for the user to choose from. When a 0 is entered, the last item in the list is automatically selected. Depending on the list size, some negative numbers are also accepted. I would suggest changing the code as follows to flag anything less then 1 as invalid:

```Python3
choice = int(response)
if choice < 1:
     self.poutput("{!r} isn't a valid choice. Pick a number between 1 and {}:\n".format(response, len(fulloptions)))
     continue
result = fulloptions[choice - 1][0]
```

**Comment by tleonhardt** [comment]
@jpaul Thanks for reporting this bug and thanks again for also providing a reasonable suggestion for a fix!
