### ISSUE TITLE
StdSim should not write strings to inner_stream.buffer

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#618]
`StdSim.write()` currently converts a string to binary and sends it to `self.buffer.write()`.
Since that method writes the bytes to its stream's buffer, any line buffering is ignored and output does not print when expected.

The behavior should be changed to write all string data directly to inner_stream and let it handle the buffering based on mode.

**Comment by tleonhardt** [comment]
This was closed by #619
