### ISSUE TITLE
Allow the "|" pipe character be read from input

### ISSUE THREAD

**Issue by xttjsn** [python-cmd2/cmd2#626]
I am developing a syntax which allows output of my cmd commands to pipe to my other cmd commands as input (as a contrary to piping output to shell commands). I have found a way via #15 to disable the redirection, but then everything after "|" is ignored. I hope there is a way to disable the redirection and still receiving "|" and everything that follows it.

**Comment by kmvanbrunt** [comment]
@xttjsn Unless your are using the command function decorators, the object passed into your command function is a `Statement` object. It contains a member called `pipe_to` which contains a list of tokens that appeared after the pipe.

```Python
def do_test(self, stmt: Statement):
        print(stmt.raw)
        print(stmt.command_and_args)
        print(stmt.pipe_to)
```

Check out parsing.py for a detailed list of Statement's members.

**Comment by tleonhardt** [comment]
@xttjsn Your use case is an interesting one that I don't believe we have ever considered, but I can see that it would be a useful feature for some subset of users.

I think with the suggestion from @kmvanbrunt you should be able to get things working like you want.  

If not, we do have various constants defined which determine which characters are treated as redirection characters and tokens in [cmd2/constants.py](https://github.com/python-cmd2/cmd2/blob/master/cmd2/constants.py).  If need be, we could probably make the ``REDIRECTION_CHARS`` and ``REDIRECTION_TOKENS`` lists modifiable by **cmd2** application developers.  I haven't tested it, but I think that if we simply removed ``REDIRECTION_PIPE`` from each of these lists, then things would work as you want.

**Comment by xttjsn** [comment]
@kmvanbrunt Thanks for the suggestion! It works well.

@tleonhardt Thanks for the hint, I changed `REDIRECTION_PIPE` to `||`, so that `|` pipes to another cmd command, and `||` pipes to shell command.
