### ISSUE TITLE
Keyboard interrupt arbitrarily produces an unexpected exception.

### ISSUE THREAD

**Issue by soutzis** [python-cmd2/cmd2#632]
Hello.

I'm using cmd2, but I have encountered a problem that I cannot solve, as I am not very familiar with Python.

Basically, I have a method in my CLI (initialised with the do_ method name prefix).

That method starts an infinite loop, which I want to exit with a keyboard interrupt, hence I catch that keyboard interrupt and specify what happens in my method.

However, some times (NOT ALWAYS), I get this error and I don't know why. Should this be happening?

```
File "/home/user/.local/lib/python3.6/site-packages/cmd2/cmd2.py", line 1643, in sigint_handler
    raise KeyboardInterrupt("Got a keyboard interrupt")
KeyboardInterrupt: Got a keyboard interrupt
```

**Comment by tleonhardt** [comment]
Hi @soutzis, thanks for reporting this issue you are having.  

We would appreciate it if you can provide us with more information so that we can reproduce the issue on our end.  For starters, it would be helpful if you could provide version info for all of the following:
- ``cmd2``
- Python (looks like 3.6)
- OS (looks like Linux, but distro and version could be useful) 

Also it would be extremely helpful if you could provide us with code for your ``do_method`` or a simplified version thereof that contains the essential loop and try/catch infrastructure at least.

**Comment by kmvanbrunt** [comment]
@soutzis The exception you see comes from **cmd2's** method called `sigint_handler`. We catch Ctrl-C events to handle **cmd2** specific things and then re-raise the `KeyboardInterrupt` so other functions can also process it.

Are you wanting to catch the `KeyboardInterrupt` in your `do_method`? If so, writing your function as follows should prevent you from seeing the unhandled exception text.

```Python
def do_stuff(self, args):
    while True:
        try:
            # do stuff
        except KeyboardInterrupt:
            # do exit stuff
            break
```

There are other times when you might need to catch `KeyboardInterrupts` to set state variables which affect the whole application. In that case, you will need to override **cmd2's** `sigint_handler` method with something like this.

```Python
def sigint_handler(self, signum: int, frame) -> None:
    # Do my application specific stuff

    # Call cmd2's sigint_handler if necessary
    super().sigint_handler(signum, frame)
```

**Comment by tleonhardt** [comment]
@soutzis Did the info from @kmvanbrunt help you solve your problem?  If so great and please let us know and we will close this issue.  If not, then please provide us with additional information as requested so we can try to reproduce your issue on our end.

**Comment by soutzis** [comment]
@kmvanbrunt your example is exactly how I had written my method. This is basically the same:
```
def do_stuff(self, args):
    try:
        while True:
            # Do stuff
    except KeyboardInterrupt:
        # Do exit stuff
```

I could recreate the error when issuing a KeyboardInterrupt multiple times.
E.g: From CLI execute `$ stuff` and then press `Ctrl + C`. (Doing this multiple times, threw the above error).

I overwrote the `sigint_handler()` method and now it seems to have stopped crashing on multiple interruptes. I will now close this issue. 

Thanks again for your prompt responses. Highly appreciated!
