### ISSUE TITLE
with_argument_list breaks when using preserve_quotes argument

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#633]
The following function causes this exception
`TypeError: with_argument_list() missing 1 required positional argument: 'func'`

```Python
@with_argument_list(preserve_quotes=True)
    def do_blah(self, args):
        print(args)
```

**Comment by tleonhardt** [comment]
This StackOverflow post has a code example that demonstrates how we could’ve  perhaps make  the **with_argument_list** decorator work both with and without parentheses:  https://stackoverflow.com/questions/35572663/using-python-decorator-with-or-without-parentheses
