### ISSUE TITLE
Improve pyscript documentation

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#644]
The section in Sphinx  on `pyscript` command needs a bit of updating.
Topics to cover:

- Running commands with `app()`
- Developing a basic scripting API that only relies on stdout and stderr in `CommandResult`
- Developing an advanced scripting API that includes populating `cmd2.last_result` which becomes `CommandResult.data`
- Utilizing `StdSim.pause_storage` to avoid duplicating data already stored in `CommandResult.data`
- Processing a `CommandResult` object returned from app()
- Exposing custom data values with `self.py_locals`.

**Comment by tleonhardt** [comment]
Given the power of ``pyscript``, our documentation has been sorely lacking in helping making this discoverable to end users

**Comment by kotfu** [comment]
We have some basic pyscript documentation now. I propose we move this issue out of the 1.0.0 milestone so that we can release. Any objections?

**Comment by tleonhardt** [comment]
@kotfu Sure moving this issue out of 1.0.0 sounds fine.  We really could benefit from some improved pyscript documentation at some point, but it can happen after the 1.0 release.

@kmvanbrunt Do you have any pyscript documentation that you have been working on?

**Comment by anselor** [comment]
It's probably also worth nothing that the external test plugin simply opens up the pyscript as a cmd2 member function to make it easier to unit test cmd2 application commands.

**Comment by jayrod** [comment]
I've written a fair bit of pyscript and would gladly add some documentation. Is this still a requirement?

**Comment by anselor** [comment]
@jayrod Yes, if you're willing to improve this area of documentation and/or provide additional examples of how this can be used it would be appreciated!

**Comment by jayrod** [comment]
I'm actually not sure what is meant by "Processing a CommandResult object returned from app()"  I presume you mean when the application returns a complex object via last_result that the script can then use for data?

**Comment by jayrod** [comment]
After looking at the code and tinkering around a bit this also makes me scratch my head a bit.

Utilizing StdSim.pause_storage to avoid duplicating data already stored in CommandResult.data

i.e. what *is* a good use case for StdSim.pause_storage?

**Comment by jayrod** [comment]
PR submitted. https://github.com/python-cmd2/cmd2/pull/1187

doesn't include anything about StdSim however.

**Comment by kmvanbrunt** [comment]
@jayrod Thanks for taking the time to write documentation. I'm just finishing my vacation, so please allow me a few days to read over your PR.

**Comment by jayrod** [comment]
i *may* be able to add an example with self.py_locals. I've not used it before but it does seem super useful. But it's also difficult to document for end users.

**Comment by tleonhardt** [comment]
This was closed by #1187 

We can always improve it further.  But this is a great start.
