### ISSUE TITLE
Stop supporting cmd2 outside of main thread

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#657]
Much of **cmd2** relies on catching `KeyboardInterrupts`, which means it has to be run in the main thread.  In issue #584, we added a check in `cmdloop()` to prevent installing a signal handler if it is not running in the main thread.

Much of the new additions, especially multiple levels of redirection/piping rely on the user being able to hit Ctrl-C to raise a `KeyboardInterrupt`. I propose we reverse the fix made in #584 since so much of the code can't work outside of the main thread.

**Comment by tleonhardt** [comment]
I think I'm OK with saying that **if** a `cmd2` application is using ``cmdloop()`` as its REPL, then it **must** be running in the main thread.  If we go that route, I would still want a check, but I would be OK with failing with an error message.

However, I would be very hesitant to begin enforcing using ``cmd2`` exclusively via ``cmdloop()``.  We have always endeavored to support use-cases where users want to roll their own REPL/event-loop but make use of the great features provided by ``cmd2`` and ``onecmd_plus_hooks``.  We even have an entire [section of the cmd2 docs](https://cmd2.readthedocs.io/en/latest/integrating.html) devoted to how to do this.

**Comment by kmvanbrunt** [comment]
I agree. The built-in `cmdloop()` should be compatible with all built-in functionality, so raising a `RuntimeError` if not in the main thread is proper.
