### ISSUE TITLE
Add a double space option

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#658]
Add option to print an extra line between prompts.

**Comment by tleonhardt** [comment]
This seems like a simple option which may be appealing to a wide range of users and would be easy to implement.

**Comment by kotfu** [comment]
Or you can just put a newline in your prompt. You you can create a **cmdfinalization** hook which outputs a blank line.

**Comment by kmvanbrunt** [comment]
@kotfu Funny enough, those approaches are the reasons behind my current changes.

I recently did a PR where we now support a multiline prompt in `async_alert`.
And issue #659 exists because the newline printed in a **cmdfinalization** hook got captured by pyscript.

So after these changes are merged, those approaches will work well.
I just figured a flag would make it easy for users that wanted it.

**Comment by kmvanbrunt** [comment]
I'm going to close this ticket now that `async_alert` supports having a new line in the prompt.  That way we won't have another setting to maintain.
