### ISSUE TITLE
Discuss when we should end support for Python 3.4

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#661]
The [last release of Python 3.4](https://www.python.org/dev/peps/pep-0429/) was on March 18, 2019.  At this point not even security updates will be provided for Python 3.4.  

We should discuss at what point we would like to formally stop supporting Python 3.4  At this point there is no burning need to end support for Python 3.4 or anything.  However there are a few points in our code that could be cleaned up where we have conditionals that look like the following which could be cleaned up:
```Python3
# Python 3.4 require contextlib2 for temporarily redirecting stderr and stdout
if sys.version_info < (3, 5):
    # noinspection PyUnresolvedReferences
    from contextlib2 import redirect_stdout
else:
    from contextlib import redirect_stdout
```

**Comment by kmvanbrunt** [comment]
Maybe start warning users now like we did for Python 2.7.

**Comment by anselor** [comment]
It's difficult to warn users by posting here since they likely don't check here. Maybe we can add a check on cmd2 startup and print something on the prompt with a warning about ending support for 3.4?

**Comment by kmvanbrunt** [comment]
For previous deprecations, we've used the change log to inform users prior to the actual deletion of support.

**Comment by anselor** [comment]
Right,
I think last time we got some people angry because they were only using it
as a pip module and not paying attention to the changelog or github
project.
Printing a message may be a benign way to make it more apparent for those
people so they have the opportunity to either update their code or their
dependency declarations.

**Comment by tleonhardt** [comment]
If we can find a way to print a warning upon doing a pip install of cmd2, but not every time a cmd2 app runs, then that would be great.

**Comment by anselor** [comment]
On the flip side, would it be possible for us to publish a final package of
cmd2 for Python 3.4 and a different version for 3.5 and greater? Can we put
the burden on our side so that breaking changes won't affect users on older
versions?

**Comment by kmvanbrunt** [comment]
Do you mean like we did with cmd2 0.8.9 being the last version meant for Python 2.7?

**Comment by anselor** [comment]
Right, but it didn't work right last time. It still gave people problems
that were still on 2.7.

**Comment by tleonhardt** [comment]
I think other than a brief hiccup, version 0.8.9 of `cmd2` still works for Python 2.7.

**Comment by tleonhardt** [comment]
`pip` is doing a good job of warning about deprecated Python versions these days.  If I try installing *anything* using pip on a Python 3.4 instance, I get the following warning (warning text prints in yellow):
```sh
(py34)$ pip install -U pip
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
```

**Comment by tleonhardt** [comment]
As long as nobody objects, let's plan on remove support in the next release.  I'd like it to happen before the 1.0 release because I want the 1.0 release to be clean and there is the potential for us to muck this up and have to do another release.

As long as we do it correctly, people using Python 3.4 will still continue to be able to use the last supported version.

**Comment by kmvanbrunt** [comment]
What about allowing my last two changes (#654 and #659) to go out in 0.9.13? Then we wait to make sure everything is stable and devote 0.9.14 to removing Python 3.4 support. That way the last 3.4 supported version has all the latest changes we are planning.

**Comment by tleonhardt** [comment]
@kmvanbrunt Yeah, I like that idea a lot.  Let's announce in the CHANGELOG for 0.9.13 that support for Python 3.4 will be discontinued in the next release.

**Comment by tleonhardt** [comment]
Once Python 3.4 has been deprecated, we can also consider beginning to incorporate [pathlib](https://docs.python.org/3/library/pathlib.html) usage in place of `os.path` since `pathlib` has several [advantages](https://treyhunner.com/2018/12/why-you-should-be-using-pathlib/).
