### ISSUE TITLE
error in installation fedora 29

### ISSUE THREAD

**Issue by LaurianoElmiroDuarte** [python-cmd2/cmd2#665]
erro installation package cmd2 in the feodora .
 
[laurianoelmiroduarte@lauriano]$ pip install cmd2
Collecting cmd2
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/cmd2/
  Using cached https://files.pythonhosted.org/packages/e9/40/a71caa2aaff10c73612a7106e2d35f693e85b8cf6e37ab0774274bca3cf9/cmd2-0.8.9-py2.py3-none-any.whl
Requirement already satisfied: contextlib2; python_version < "3.5" in /usr/lib/python2.7/site-packages (from cmd2) (0.5.5)
Requirement already satisfied: pyperclip in /usr/lib/python2.7/site-packages (from cmd2) (1.7.0)
Requirement already satisfied: wcwidth; sys_platform != "win32" in /usr/lib/python2.7/site-packages (from cmd2) (0.1.7)
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from cmd2) (1.11.0)
Requirement already satisfied: enum34; python_version < "3.4" in /usr/lib/python2.7/site-packages (from cmd2) (1.1.6)
Requirement already satisfied: pyparsing>=2.0.1 in /usr/lib/python2.7/site-packages (from cmd2) (2.2.0)
Collecting subprocess32; python_version < "3.0" (from cmd2)
  Using cached https://files.pythonhosted.org/packages/be/2b/beeba583e9877e64db10b52a96915afc0feabf7144dcbf2a0d0ea68bf73d/subprocess32-3.5.3.tar.gz
Installing collected packages: subprocess32, cmd2
  Running setup.py install for subprocess32 ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-JnZsRn/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-h4TLez/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying subprocess32.py -> build/lib.linux-x86_64-2.7
    running build_ext
    running build_configure
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for unistd.h... (cached) yes
    checking fcntl.h usability... yes
    checking fcntl.h presence... yes
    checking for fcntl.h... yes
    checking signal.h usability... yes
    checking signal.h presence... yes
    checking for signal.h... yes
    checking sys/cdefs.h usability... yes
    checking sys/cdefs.h presence... yes
    checking for sys/cdefs.h... yes
    checking for sys/types.h... (cached) yes
    checking for sys/stat.h... (cached) yes
    checking sys/syscall.h usability... yes
    checking sys/syscall.h presence... yes
    checking for sys/syscall.h... yes
    checking for dirent.h that defines DIR... yes
    checking for library containing opendir... none required
    checking for pipe2... yes
    checking for setsid... yes
    checking whether dirfd is declared... yes
    configure: creating ./config.status
    config.status: creating _posixsubprocess_config.h
    building '_posixsubprocess32' extension
    creating build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c _posixsubprocess.c -o build/temp.linux-x86_64-2.7/_posixsubprocess.o
    In file included from /usr/include/python2.7/pyconfig.h:6,
                     from /usr/include/python2.7/Python.h:8,
                     from _posixsubprocess.c:16:
    /usr/include/python2.7/pyconfig-64.h:1232: warning: "_POSIX_C_SOURCE" redefined
     #define _POSIX_C_SOURCE 200112L
    
    In file included from /usr/include/sys/cdefs.h:23,
                     from _posixsubprocess.c:12:
    /usr/include/features.h:265: note: this is the location of the previous definition
     # define _POSIX_C_SOURCE 200809L
    
    In file included from /usr/include/python2.7/pyconfig.h:6,
                     from /usr/include/python2.7/Python.h:8,
                     from _posixsubprocess.c:16:
    /usr/include/python2.7/pyconfig-64.h:1254: warning: "_XOPEN_SOURCE" redefined
     #define _XOPEN_SOURCE 600
    
    In file included from /usr/include/sys/cdefs.h:23,
                     from _posixsubprocess.c:12:
    /usr/include/features.h:202: note: this is the location of the previous definition
     # define _XOPEN_SOURCE 700
    
    gcc -pthread -shared -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld build/temp.linux-x86_64-2.7/_posixsubprocess.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/_posixsubprocess32.so
    running install_lib
    copying build/lib.linux-x86_64-2.7/_posixsubprocess32.so -> /usr/lib64/python2.7/site-packages
    error: [Errno 13] Permission denied: '/usr/lib64/python2.7/site-packages/_posixsubprocess32.so'
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-JnZsRn/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-h4TLez/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-JnZsRn/subprocess32/

thankful

**Comment by tleonhardt** [comment]
@LaurianoElmiroDuarte  First off I would strongly recommend using Python 3 instead of Python 2.7.  I believe that Fedora 29 should have both Python 3.6 and 3.7 available and then you should be able to install additional packages using **pip3**.  If you use Python3, pip will install a much newer version of cmd2.  Additionally all support for Python2 ends on December 31, 2019.

I tested installation of cmd2 0.8.9 in Python2 using pip on Ubuntu recently and it worked fine.  So your error appears to be unique to either your particular setup or Fedora 29 or possible a transient error in PyPI.

**Comment by LaurianoElmiroDuarte** [comment]
i solved this problem @tleonhardt , need this package of Python2.7, i installed it from the fedora repository  
https://fedora.pkgs.org/29/fedora-x86_64/python2-cmd2-0.8.8-5.fc29.noarch.rpm.html
i will stop of Python2.7 .. 
thankful

**Comment by tleonhardt** [comment]
@LaurianoElmiroDuarte I'm glad you were able to solve your problem.  Good luck to you!
