### ISSUE TITLE
Don't print complete help text on argparse error

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#667]
**ACArgumentParser** overrides **argparse.ArgumentParser's** `error()` function. One of its behaviors is to print all of the help text when there is a parsing error. Help text can be pretty long and has the tendency to scroll the actual error message off the screen.

I suggest we use the normal behavior of only printing the error and usage statement when a parsing error occurs.

**Comment by tleonhardt** [comment]
@kmvanbrunt Your suggestion sounds like a good one.

**Comment by kmvanbrunt** [comment]
The `error()` function in **ACArgumentParser** prints its error in `Fore.LIGHTRED_EX` like `perror()` does. But this code was written before we added the `colors` setting in **cmd2**.

Should we make `colors` a setting that is shared across modules so **ACArgumentParser** and other modules in a **cmd2** app can access it?

**Comment by tleonhardt** [comment]
It would perhaps be good to add the default error and warning colors to a common location such as **constants.py**.
