### ISSUE TITLE
Give informative error message for invalid completer instead of empty completion results.

### ISSUE THREAD

**Issue by marklalor** [python-cmd2/cmd2#668]
The following code suppresses an error when a completion function with an invalid signature is provided https://github.com/python-cmd2/cmd2/blob/de701086ff832bad0f0d97ffb10c2159d56ede7d/cmd2/argparse_completer.py#L691-L693

Instead of returning an empty list, I think that an informative error message explaining that the function signature is incorrect would be much more helpful. When I was implementing completion I was confused about why my completer wasn't returning any results until I traced it to this `return []`.

**Comment by tleonhardt** [comment]
@marklalor Thanks for reporting this.  I think it would be helpful for users to get a good error message informing them that there is a problem and roughly what it is likely to be.  

I think it is debatable whether we should fail fast at that point or march on and return an empty list like we are doing now.

@kmvanbrunt What do you think?
