### ISSUE TITLE
Rename load command

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#675]
I propose renaming **load** to **load_script**.
This will certainly be a breaking change, but it will make the command name more descriptive in what it actually loads.

**__relative_load** will also be renamed to **__relative_load_script**.

**Comment by tleonhardt** [comment]
I prefer to not make major breaking changes like this without good reason.  However, I have seen end customers get confused by the **load** command on multiple occasions - in both cases they mistakenly assumed that it was intended to load a different type of file which made sense for the particular `cmd2` application.  And this occurred for two different `cmd2` applications with two different customers.  So in this case, I think changing to this more precise name could help avoid confusion such as this.

Regardless, I want to get any remaining breaking changes like this into the 0.9.13 release so we can work on striving for stability as we lead up to a 1.0 release.

**Comment by teto** [comment]
+1 for me. I want to use load for sthg else.

**Comment by kmvanbrunt** [comment]
I'm gonna start this ticket soon, but I want to confirm the name choice with everyone.
**load_script** is descriptive, but it's long. **__relative_load_script** is even longer.

Is **script** a good name? It fits nicely with **pyscript**. Also consider that **__relative_load** would become **__relative_script**.

**Comment by tleonhardt** [comment]
I would be fine with either `load_script` or `script`.  

`load_script` has the advantage of being more descriptive where it is obvious what that command should do.  However, `script` has the advantage of being shorter and more in-sync with naming for `pyscript`.  

Another aspect in favor of `load_script` would be that end-users who are currently familiar with starting to type `load` and using tab-completion to finish the command name may find an easier time transitioning to the new command name.

**Comment by teto** [comment]
`load_script` is better imo, one can alias the command if it feels it's too long (and with autocompleiton anyway that's less of a problem). And because load_script can be confused with a program command, maybe it should be prefixed with `cmd2` ? `cmd2_load_script`

**Comment by kmvanbrunt** [comment]
I'd like to avoid using `cmd2` in command names since end users of applications may be unaware of the underlying framework and `cmd2` won't be a familiar term to them.

Right now I'm leaning toward `script` just because it relates so well with `pyscript`. Then our commands reflect the fact that we have normal scripts and Python scripts.

@teto What are the reasons you like `load_script` better?

**Comment by teto** [comment]
`script` meaning is pretty fuzzy while `load_script` is clearer. Also I like the discoverability reason given by @tleonhardt, when users realize `load` doesn't work anymore, load_script is close enough thay could discover it via autocompletion or help.

**Comment by lancestarr** [comment]
How about run_pyscript() and run_script(), and deprecate the others (continue supporting them until the next major version)?

**Comment by tleonhardt** [comment]
@lancestarr I like the suggestion of `run_pyscript()` and `run_script` - I think having the verb in the name helps clarify intent and potentially makes these more discoverable.

I also like the idea of deprecating prior to removing them.  I think when we do that we should probably also replace their help text with a deprecation warning.

**Comment by tleonhardt** [comment]
@kotfu Do you have an opinion on this one?

**Comment by kotfu** [comment]
I like the deprecation path where we have both the current names and the new names work for some period of time. As for the new names, I think I like the `run_pyscript` and `run_script` options the best.

**Comment by tleonhardt** [comment]
Since this will be a major break with backwards compatibility which will affect all consumers of `cmd2` and will cause some of them to have to update code and/or documentation, we should consider reaching out to some of the larger users of `cmd2` such as `cliff`, `CephFS shell`, etc.
