### ISSUE TITLE
Handle return code of onecmd_plus_hooks

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#687]
There are a few cases in **cmd2** where `onecmd_plus_hooks()` returns **True**, which means stop the command loop, but stop is not passed up. Evaluate these cases and determine if stop should be handled.

**Comment by teto** [comment]
any code to test :p ? looking forward to this

**Comment by tleonhardt** [comment]
@teto 
There is some code on the `script_refactor` branch which I believe addresses this issue. @kmvanbrunt isn't done with it yet.  But I believe he *is* done with this part of it, so you should be able to test that if you like and leave any feedback you have here.
