### ISSUE TITLE
Define a formalized way to mark classes, methods, functions, and attributes as deprecated

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#714]
As we get more formalized in our semantic versioning, it becomes highly desirable to have a formalized method to mark classes, methods, functions, and attributes as deprecated, both in code and in documentation. I think an ideal solution would:

- have deprecations indicated in source code
- have those deprecations appear in our API documentation (without having to make the edits in two places)
- emit some warning to developers at runtime when they use a deprecated element

If these are the desirable criteria, then it appears that there is already a python library that will do this for us. It's called [deprecated](https://deprecated.readthedocs.io/en/latest/). I suggest we consider using this library, finding one similar to it, or rolling our own somehow to accomplish the three objectives above.

**Comment by tleonhardt** [comment]
I wasn't aware of the `deprecated` library.  From looking at the documentation, it seems pretty decent.

The [deprecation](https://deprecation.readthedocs.io/en/latest/) library is another alternative and it has what I view as several advantages:
* Available in most modern Linux distros via package manager
* Provided decorator allows you to specify not only what release it was deprecated in, but also what release it will be removed in
* Has built-in mechanism to use in unit tests to prevent you from forgetting to deprecate something when you said you would

However, `deprecation` only supports deprecation of functions and methods; whereas `deprecated` also supports deprecation of classes.  I don't believer either supports deprecation of attributes.

So I don't see a clear-cut winner here, though I do slightly favor `deprecation` for the reasons mentioned.

**Comment by tleonhardt** [comment]
I think we have done fine without a library, but in the future if we want one, [deprecated](https://github.com/tantale/deprecated) seems to be both more popular and more maintained than [deprecation](https://github.com/briancurtin/deprecation).

I'll resolve this since I don't think any further action is going to be taken on it at this time.
