### ISSUE TITLE
self.statement_parser was changed to self._statement_parser even though Docs suggest to use it.

### ISSUE THREAD

**Issue by xNinjaKittyx** [python-cmd2/cmd2#716]
self.statement_parser was changed to self._statement_parser, but in the docs, we have put it as a part of the processing hook (see [Postparsing Hooks](https://cmd2.readthedocs.io/en/latest/features/hooks.html) section)

**Comment by tleonhardt** [comment]
@xNinjaKittyx Good catch.  

When I was working on minimizing the public API, I thought there wasn't a valid use case for developers using `cmd2` to make sure of the `StatementParser` instance inside a `cmd2.Cmd` instance.  However, I had not considered the case of developing post-parsing hooks and the fact that we intentionally made `Statement` instances immutable (and even if we hadn't manually altering one would be fraught with peril unless done correctly.  This is a valid use case, and heck we even documented it ;-)

So this was a mistake on my part.  I apologize for any inconvenience.  I'll restore it to the previous name and we should be putting out a release within the next couple weeks.
