### ISSUE TITLE
run_script command documents an invalid option --record-transcript

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#723]
The `run_script` help message says you can use the `-r/--record-transcript` option, however, this option is not actually valid. It appears if you want to record a transcript while executing the script, you use the `-t/--transcript` option.

When fixing this help message, we might also consider changing it from `-t TRANSCRIPT` to `-t TRANSCRIPT_FILE`.

**Comment by kmvanbrunt** [comment]
The history command also has -t TRANSCRIPT. I will change both metavar values to TRANSCRIPT_FILE.
