### ISSUE TITLE
Running a shell command that crashes can exit a cmd2 application silently

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#742]
```sh
./basic.py
(Cmd) !cat scripts/
cat migrating.py  scripts/
cat: migrating.py: No such file or directory
cat: scripts/: Is a directory
```

One time when I ran this it crashed the cmd2 application.  But then I tried to reproduce it and ran it like 20 times and it was fine.

**Comment by kmvanbrunt** [comment]
After discussing with @tleonhardt, we decided to close the ticket since we can't reproduce it.
