### ISSUE TITLE
Purpose of allow_redirection

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#746]
What is `allow_redirection` supposed to do? Is it there only to prevent redirection of stdout or is it also intended to alter parsing behavior?

When set to **False,** it slightly, but not completely, alters parsing.
- `command > out.txt` results in `command `
- `command >out.txt` results in `command  >out.txt`

If  `allow_redirection` is False, should we treat redirectors as literals or preserve normal parsing behavior and just consider `allow_redirection` to be a security setting?

See #15 and #45 for some context.

**Comment by tleonhardt** [comment]
The [Output Redirection](https://cmd2.readthedocs.io/en/latest/features/generating_output.html?highlight=allow_redirection#output-redirection) section of the Sphinx docs states:
> If you wish to disable cmd2’s output redirection and pipes features, you can do so by setting the `allow_redirection` attribute of your cmd2.Cmd class instance to False. This would be useful, for example, if you want to restrict the ability for an end user to write to disk or interact with shell commands for security reasons.
> cmd2’s parser will still treat the `>`, `>>`, and `|` symbols as output redirection and pipe symbols and will strip arguments after them from the command line arguments accordingly. But output from a command will not be redirected to a file or piped to a shell command.
