### ISSUE TITLE
help with upgrading autocompletion to 0.9.15 

### ISSUE THREAD

**Issue by teto** [python-cmd2/cmd2#748]
I am looking into upgrading my code to 0.9.15. The new methods for autocomplete look useful but right now I wonder about
`setattr(load_pcap1, argparse_completer.ACTION_ARG_CHOICES, ('path_complete', ))`
ACTION_ARG_CHOICES seems to have disappeared.
a file has been renamed to argparse_custom too.
Anyway I've tried 
`setattr(load_pcap1, cmd2.argparse_completer.ATTR_CHOICES_CALLABLE, completer_method=cmd2.Cmd.path_complete)`
to no avail

**Comment by tleonhardt** [comment]
Hey Matthieu,

We got rid of the use of `setattr` and `ACTION_ARG_CHOICES`, but in the process we made the API **MUCH** easier to use by adding options to the *argparse* `add_argument()` method for `argparse.ArgumentParsers`.  

The new API looks like:
```Python
my_parser.add_argument('a_positional', completer_method=cmd2.Cmd.path_complete)
```

The tab-completion methods available within `cmd2` for use inside `add_argument` are as follows:
* `choices` - built-in, but we hook it and tab complete
* `choices_function`
* `choices_method`
* `completer_function`
* `completer_method`

We will work on updating the documentation soon to make everything more clear.  But for now you can look at the updated [tab_autocompletion.py](https://github.com/python-cmd2/cmd2/blob/master/examples/tab_autocompletion.py) example or at the [PyOhio 2019 slides and examples](https://github.com/python-cmd2/talks/tree/master/PyOhio_2019) from a presentation about `cmd2` that @kmvanbrunt and I gave this past weekend.  Video should be available within a week or two.

**Comment by kmvanbrunt** [comment]
@teto While we are in the process of updating our docs, the best documentation for this new change is the header to [argparse_custom](https://github.com/python-cmd2/cmd2/blob/master/cmd2/argparse_custom.py).

[tab_autocompletion.py](https://github.com/python-cmd2/cmd2/blob/master/examples/tab_autocompletion.py) does give examples, but it is rather long. I hope to rewrite it as something simpler in the future.

**Comment by teto** [comment]
I have custom parser actions that I would like to upgrade:
```
class LoadSinglePcap(DataframeAction):
    '''
    Test action !!
    '''
    def __init__(self, loader=TsharkConfig(), **kwargs) -> None:
        super().__init__(df_name=kwargs.get("dest"), **kwargs)
        self.loader = loader

        # 'completer_method': cmd2.Cmd.path_complete
        setattr(self, cmd2.argparse_completer.ACTION_ARG_CHOICES, ('path_complete', os.path.isfile))

```
would adding a simple line with the correct function be enough https://github.com/python-cmd2/cmd2/blob/4aa8370092d1aba5edaf77bf9a867b23adf4aa97/cmd2/argparse_custom.py#L365 ?

I suppose I could convert some of the code to use the post hooks but I've grown fond of custom actions and postprocessing hooks are not a 1:1 replacement either.

**Comment by kmvanbrunt** [comment]
@teto There is no problem with using custom actions. It will work just by replacing the line with:

```Py
completer_method = functools.partial(path_complete, path_filter=lambda path: os.path.isfile(path))
setattr(self, ATTR_CHOICES_CALLABLE,
           ChoicesCallable(is_method=True, is_completer=True, to_call=completer_method))
```

But I'm gonna write wrapper functions to support cases like this. That way developers don't need to worry about the lower level stuff like attribute names. It should be checked in tonight. At that point just do:

```Py
completer_method = functools.partial(path_complete, path_filter=lambda path: os.path.isfile(path))
set_completer_method(self, completer_method)
```

**Comment by kmvanbrunt** [comment]
@teto Please review #750

**Comment by teto** [comment]
seems like these are working thanks !
I would like to rehaul my parsing system but now that it works and as I get constrained in time, I might keep it as is xD

**Comment by teto** [comment]
I wanted to add some features that I believe possible with the new completion infra but I noticed that there was no doc for it ? like https://cmd2.readthedocs.io/en/latest/search.html?q=completer_method&check_keywords=yes&area=default# gives nothing :'(

This page is empty https://cmd2.readthedocs.io/en/latest/features/plugins.html, which looked weird as well

**Comment by tleonhardt** [comment]
@teto We are in the middle of major refactoring our Sphinx documentation and at this time there are still significant chunks that are still missing which are primarily related to new and/or advanced features.

The goal we are working towards is to have the documentation complete and up-to-date prior to a 1.0 release, but we have been focusing first on getting to the point of API stability.

The best documentation we have for things like `completer_method` at this time is the file-header docstring comment in [argparse_custom.py](https://github.com/python-cmd2/cmd2/blob/master/cmd2/argparse_custom.py).
