### ISSUE TITLE
completion: allow descriptions next to the completion

### ISSUE THREAD

**Issue by teto** [python-cmd2/cmd2#763]
I have been thinking about how to leverage the completion of cmd2 and I would like to display a description next to each  completion entry as zsh does in
https://camo.githubusercontent.com/a2482f01ad4813e544d8fe76a6f0092b00a414b0/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3337343738362f323433303336332f61333239666164382d616364372d313165332d383361632d6436323634343935363865392e706e67

Like I would like the completion candidates to be 0, 1 , 2 and display a score next to it:

```
cmd2_prompt> plot stream <tab>
0    --- score of +oo
1     ---- score of 60
2     ---- score of 0
```
is that possible ?

**Comment by kmvanbrunt** [comment]
This can be done using the `CompletionItem` class. It is documented in the header for [argparse_custom.py](https://github.com/python-cmd2/cmd2/blob/master/cmd2/argparse_custom.py). Until we are able to update our official docs, that header is the best source for argparse tab completion.

[cmd2.py](https://github.com/python-cmd2/cmd2/blob/master/cmd2/cmd2.py) makes use of `CompletionItems` in a few places. Check out that code for examples.

The easiest way to see it in action is:
1. Open your app
2. Type `set <tab><tab>`

**Comment by teto** [comment]
indeed that worked. ty
