### ISSUE TITLE
1.0.0 documentation additions and updates

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#765]
This issue will track all the documentation updates and changes to be done in advance of releasing 1.0.0.

**Comment by tleonhardt** [comment]
FYI, I merged *master* into the *doc_additions* branch (primarily to make sure we didn't have any conflicts)

**Comment by tleonhardt** [comment]
@kotfu Would it be OK if we create a PR to merge in your changes on the **doc_additions** branch?  I'd like to get them in sooner rather than later.  I know we still have more doc improvements after that, but I'd rather get what we have in.

**Comment by tleonhardt** [comment]
# Summary of documentation improvements needed
This comment is essentially a **TODO** list of documentation improvements which should be done.

## Missing Sections
These are sections of documentation which we haven't created a place for yet, but probably should:
* Something focused on piping and redirecting and the powers it provides
  * Make sure it shows complicated but useful examples like piping and redirecting in the same command and multiple pipes
* Something about recommended best practices when using `cmd2` with an overall application plugin framework and how to deal with things like sub-command arguments processed by a plugin
* More examples in the Examples section of the Sphinx docs

## Empty Sections
These are sections which exist, but don't contain any content:
* [Features/Initialization](https://cmd2.readthedocs.io/en/latest/features/initialization.html)
* [Features/Plugins](https://cmd2.readthedocs.io/en/latest/features/plugins.html)
* [Features/Startup Commands](https://cmd2.readthedocs.io/en/latest/features/startup_commands.html])

## Woefully Inadequate/Incomplete Sections
These are sections which exist and contain some minimal content, but the content they contain doesn't do `cmd2`'s feature set justice:
* [Features/Completion](https://cmd2.readthedocs.io/en/latest/features/completion.html#)
  * `cmd2`'s tab-completion capabilities are fantastic and extensive - what we have here doesn't even begin to scratch the surface
* [Features/Scripts/Python Scripts](https://cmd2.readthedocs.io/en/latest/features/scripting.html#python-scripts)

**Comment by tleonhardt** [comment]
@kotfu I merged **master** into the **generating_output_docs** branch.  There were a few conflicts due to some ansi/style stuff getting renamed.  But I think it is in a good state.  It looks like you made a bunch of nice documentation updates there that we should get merged in sometime soon.
