### ISSUE TITLE
disable_command() throws exception if None passed as message

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#766]
The disable_command() method requires a `message_to_print` parameter. If the user tries to run a disabled command, the value of this string is displayed for the user. There is no way for the developer to disable a command without printing a message. You can set this parameter to an empty string, but then a blank line is output when the user tries to run the command.

We should make this parameter optional and default to `None`. If set to `None`, nothing should be printed when the user tries to run a disabled command.

**Comment by kmvanbrunt** [comment]
You want nothing to happen at all? No feedback of any kind? I can do that, but help me understand the use case.

**Comment by kotfu** [comment]
I opened this issue while writing documentation for hiding and disabling commands. I had a simple test program open so I could verify the behavior matched what I was writing, and also so I could paste known working code snippets into the documentation. With this end in mind, I wanted the simplest code I could possibly write, so I put `None` as the `message_to_print` parameter, which when executed throws an attribute error. I don't have a real use case other than simple documentation.

However, I've been thinking about this issue, and your comment changed my mind. It probably doesn't make sense to just be silent if the developer passes `None` in `message_to_print`. Here's how I'm now thinking about it now.

If the user tries to run a command which the developer has disabled, one of two things should happen. By far the most desirable outcome is the behavior currently implemented by `disable_command()`: `cmd2` should print the message given by the developer when the command was disabled. This makes a ton of sense and allows the developer to customize the message given to the user.

However, it might also be desirable to have `cmd2` treat a disabled command just like it would treat an unknown command. At the moment, that means `cmd2` spits out an error message like:
```
(Cmd) nope
nope is not a recognized command, alias, or macro
```

The developer could try and copy the error message generated by `cmd2`, but that is subject to change. So what if the developer just passed `None` as `message_to_print`, and then `cmd2` generates the same error message it would have otherwise.

At a minimum, we should fix this exception which is thrown if you pass `None`:
```
(Cmd) lock
Traceback (most recent call last):
  File "/Users/jared/src/cmd2/cmd2/cmd2.py", line 1754, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
  File "/Users/jared/src/cmd2/cmd2/cmd2.py", line 2149, in onecmd
    stop = func(statement)
  File "examples/simple.py", line 13, in do_lock
    self.disable_command('open', None)
  File "/Users/jared/src/cmd2/cmd2/cmd2.py", line 4101, in disable_command
    message_to_print=message_to_print.replace(COMMAND_NAME, command))
AttributeError: 'NoneType' object has no attribute 'replace'
EXCEPTION of type 'AttributeError' occurred with message: ''NoneType' object has no attribute 'replace''
```
By the way, after this exception is thrown, if you try and enable the command (i.e. `lock` in this example), you get another exception.

Here's the example program I used when testing this stuff:
```
#!/usr/bin/env python
"""A simple cmd2 application."""
import cmd2


class FirstApp(cmd2.Cmd):
    """A simple cmd2 application."""

    def do_echo(self, line):
        self.poutput(line)

    def do_lock(self, line):
        self.disable_command('open', None)
        self.poutput('the door is locked')

    def do_unlock(self, line):
        self.enable_command('open')
        self.poutput('the door is unlocked')

    def do_open(self, line):
        """open the door"""
        self.poutput('opening the door')

if __name__ == '__main__':
    import sys
    c = FirstApp()
    sys.exit(c.cmdloop())
```

**Comment by kotfu** [comment]
Also, if we do change this logic, we should make it work the same way for `disable_category()`.

**Comment by kotfu** [comment]
OK, you have persuaded me. I've updated the issue title to indicate the bug to be fixed is that it shouldn't break if I pass None as the message. I guess we'll need to think about what we should do if the developer passes an empty string as the message. I think I'm OK with just printing the message, and if the developer passes an empty string, their users will just be clueless.

**Comment by kmvanbrunt** [comment]
Since `disable_command()` has type hinting and a detailed docstring explaining that `message_to_print` is a string, I would rather not add support to handle passing **None** since that is incorrect usage of our API.

**Comment by tleonhardt** [comment]
In general for `str` arguments, we have favored an approach of defaulting to something like an empty string and possibly treating that special, but **NOT** accepting `None`.  I think we should continue to favor that type of approach when/where appropriate.  

Down the road I would like to see better static analysis based on type hints using something like `mypy`.

**Comment by tleonhardt** [comment]
If I am understanding correctly, I don't think any code change is strictly required here.

So I am going to close this issue.  If anyone feels strongly otherwise, please feel free to re-open it.
