### ISSUE TITLE
do_ command :: can they be defined in a loop?

### ISSUE THREAD

**Issue by adriansev** [python-cmd2/cmd2#767]
Hi! I have a list of commands that in fact do the same thing : send text (the command) to the server and then print the answer. Is there a way to define the required do_ functions by looping over a list of the commands? Or it is required do define them one by one?
Thank you!

**Comment by tleonhardt** [comment]
Hi @adriansev Since this is Python and we have first class functions, yes there is definitely a way to do what you want.  Actually there are a lot of different ways you could do this.

One basic way to do it would look like the following:
```Python3
import functools
import cmd2
COMMAND_LIST = ['foo', 'bar', 'baz']


class CommandsInLoop(cmd2.Cmd):
    """Example of dynamically adding do_* commands."""
    def __init__(self):
        super().__init__(use_ipython=True)

    def send_text(self, args: cmd2.Statement, *, text: str):
        """Simulate sending text to a server and printing the response."""
        self.poutput(text.capitalize())

    def text_help(self, *, text: str):
        """Deal with printing help for the dynamically added commands."""
        self.poutput("Simulate sending {!r} to a server and printing the response".format(text))


for command in COMMAND_LIST:
    setattr(CommandsInLoop, 'do_{}'.format(command), functools.partialmethod(CommandsInLoop.send_text, text=command))
    setattr(CommandsInLoop, 'help_{}'.format(command), functools.partialmethod(CommandsInLoop.text_help, text=command))


if __name__ == '__main__':
    app = CommandsInLoop()
    app.cmdloop()
```

**Comment by tleonhardt** [comment]
I'll probably go ahead and add a simple example to demonstrate this.  I know @kmvanbrunt has toyed with the idea of adding an even better example for how to break down the the definition of `do_*` commands into multiple files.
