### ISSUE TITLE
Allow to dynamically extend a cmd2.Cmd object with a custom do_xxx method at runtime.

### ISSUE THREAD

**Issue by GnikDroy** [python-cmd2/cmd2#771]
Issue #267 also addresses the same issue.

Extending the `cmd2.Cmd` object with `do_xxx` perhaps might not be the what most users what.
But since the solution is simple and is not an API breaking change, I thought I would mention it anyway. This approach also seems more reasonable than the current method.

As noted in the earlier issue, the main issue is that the `do_xxx` methods are not registered in the help menu. Perhaps a minor oversight from Cpython cmd developers (since this is a minor issue that can be fixed by extending the class), but `dir(self.__class__)` doesn't account for the functions added at runtime.

A simple fix would be to override the `get_names()` in `cmd2.Cmd` to change the default implementation (from [cpython's source](https://github.com/python/cpython/blob/master/Lib/cmd.py#L281))
```python
 def get_names(self):
        return dir(self.__class__)
``` 
into 
```python
def get_names(self):
        return dir(self)
```

I believe **making this minor change would allow users to extend the cmd2 module at runtime**. :)

**Comment by kmvanbrunt** [comment]
Adding commands at runtime is a feature I've been working as well and I also ran into the problem you are describing. `get_names()` will be updated when I push up the changes.
