### ISSUE TITLE
Remove support for use_rawinput

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#772]
Since we've already broken full compatibility with **cmd**, can we remove support for setting `self.raw_input` to False? I'm not sure the use case for doing so, and handling this obscure case complicates our code.

See #206 for a previous reference to this issue.

**Comment by tleonhardt** [comment]
The use case for setting `self.raw_input` to `False` is that the `cmd.Cmd.__init__()` base class initializer accepts an optional `stdin` argument which species the input file object that the `Cmd` instance or subclass instance will use for input.  If not specified, it will default to `sys.stdin`.

From the [cmd documentation](https://docs.python.org/3/library/cmd.html):
> If you want a given *stdin* to be used, make sure to set the instance’s `use_rawinput` attribute to **False**, otherwise stdin will be ignored.

**Comment by kmvanbrunt** [comment]
Closing this issue since `self.use_rawinput` is needed.
