### ISSUE TITLE
Create CompletionError exception

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#773]
Add an exception that can be raised during tab completion to print an error to the user.
Possible use cases

1. Reading a database to retrieve a tab completion data set failed
2. A previous command line argument that determines the data set being completed is invalid

**Comment by tleonhardt** [comment]
Once this enhancement is in, I think we should put out the next release.  The bug fixes related to `pyperclip` deficiencies would probably be beneficial for lots of potential users.
