### ISSUE TITLE
Bind function to keyboard shortcuts

### ISSUE THREAD

**Issue by Jab2870** [python-cmd2/cmd2#791]
Hi,

Thanks for this great library. Is it possible to bind funtions to keyboard shortcuts?

**Comment by tleonhardt** [comment]
Hi Jonathan,

`cmd2` has several capabilities for creating different kinds of "shortcuts" including all of the following:
* [Shortcuts](https://cmd2.readthedocs.io/en/latest/features/shortcuts_aliases_macros.html#shortcuts)
  - Shortcuts are generally single character and are used without a space separating them from their arguments, like `!ls` (where `!` is the shortcut)
* [Aliases](https://cmd2.readthedocs.io/en/latest/features/shortcuts_aliases_macros.html#aliases)
  - Aliases work in a similar fashion to aliases in the Bash shell
* [Macros](https://cmd2.readthedocs.io/en/latest/features/shortcuts_aliases_macros.html#macros)
  - The major difference between macros and aliases is that macros can contain argument placeholders

Given that `cmd2` is a **line-oriented command interpreter** and not a full-screen text user interface, we are generally doing most processing of what the user types only after they hit <Enter> or <Tab>; thus we cannot easily support the kinds of keyboard shortcuts which are common in GUIs.

**Comment by tleonhardt** [comment]
@Jab2870 [fzf](https://github.com/junegunn/fzf) looks like it can be used as an interactive command-line utility in its own right.  There is nothing within `cmd2` to stop you from running an interactive command-line utility within a `cmd2` command; in fact I've done that quite frequently to build in a command which invokes a tool like [pgcli](https://www.pgcli.com/) for browsing through a database.  If you do that, you can have your `cmd2` command invoke `fzf`.  Once `fzf` is in control, whatever keyboard shortcuts it supports will "just work".  Then once `fzf` exists and returns control to `cmd2` you are "back to normal" (from a `cmd2` perspective).

**Comment by Jab2870** [comment]
Thanks, I think you mis-understood me. I have fzf working inside cmd2 without a problem. What I would like to do is use a keyboard shortcut inside cmd2 to invoke fzf.

For example, i might want to use `<ctrl>`+`t` to use fzf to select a filename (as it works in a bash readline prompt). This filename is then added to my current readline prompt where the cursor is.

**Comment by tleonhardt** [comment]
Thanks for clarifying.

We don't have any build-in support within `cmd2` for doing what you want, but I think you should pretty easily be able to use a a package like [pynput](https://pynput.readthedocs.io/en/latest/keyboard.html#monitoring-the-keyboard) to setup additional keyboard shortcuts.

@kmvanbrunt @kotfu Do either of you have any further insight?

**Comment by Jab2870** [comment]
@tleonhardt , thanks very much. I have not come accross pynput before. I am doing this as a project to learn python.

I will take a look.

**Comment by kmvanbrunt** [comment]
@Jab2870 Look into `readline.parse_and_bind()`. I've not used this for anything other than binding `tab`  for completion. But there may be a way to bind `<ctrl>`+`t`

**Comment by Jab2870** [comment]
@kmvanbrunt, Thanks, I will look into that

**Comment by tleonhardt** [comment]
@Jab2870 I'm going to close this.  Feel free to ask further questions.
