### ISSUE TITLE
AppVeyor windows tests get stuck by random keyboard interrupts

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#797]
The Windows unit tests for `cmd2` which run on AppVeyor are sometimes getting stuck by a keyboard interrupt error which is then waiting for the user to type "Y/YES" in the non-interactive shell.

**Comment by kmvanbrunt** [comment]
I may have fixed this in [8fd8c56](https://github.com/python-cmd2/cmd2/commit/8fd8c56bdabafd58fbe0af284ced4765952557bc). I ran it through AppVeyor numerous times on a now deleted branch with no issues.
