### ISSUE TITLE
Does it parse correct arguments with spaces?

### ISSUE THREAD

**Issue by FedericoCeratto** [python-cmd2/cmd2#8]
Originally reported by: **Anonymous**

---

```
#!python

import sys
from cmd2 import Cmd, make_option, options

class DemoApp(Cmd):
    """Simple command processor example."""

    @options([make_option('-n', '--name', action="store", help="your name"),
         ])
    def do_hello(self, command, opts):
        if opts.name:
            sys.stdout.write('Hello %s\n' % opts.name)
        else:
            sys.stdout.write('Hello Nobody\n')

if __name__ == '__main__':
    DemoApp().cmdloop() 
```

if you pass:
hello 'Catherine Devlin'
it is printed:
Hello 'Catherine

the same with double quotes

---
- Bitbucket: https://bitbucket.org/catherinedevlin/cmd2/issue/8

**Comment by FedericoCeratto** [comment]
(Cmd) hello 'foo bar'      does not work anymore, leading to Hello Nobody
(Cmd) hello -n 'foo bar'      still returns only "Hello 'foo"

**Comment by tleonhardt** [comment]
This issue has been fixed with the most recent commit and a couple unit tests have been added to help make sure it doesn't get broken again.
