### ISSUE TITLE
Improve tab-completion Sphinx documentation

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#800]
Update the [completion.rst](https://github.com/python-cmd2/cmd2/blob/master/docs/features/completion.rst) file to include most, if not all, of the header to [argparse_custom.py](https://github.com/python-cmd2/cmd2/blob/master/cmd2/argparse_custom.py).

The best way to do this would be to reformat that module docstring so that it is valid [reStructuredText](http://docutils.sourceforge.net/rst.html) so that the [Sphinx AutoDoc](http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) **automodule** command will automatically import it.

If that proves too difficult or time consuming, then we could manually cut-and-paste and reformat to valid reStructuredText.

**Comment by tleonhardt** [comment]
#887 updated the tab completion examples

**Comment by kmvanbrunt** [comment]
I still plan on updating these documents, but they don't need to delay the 1.0 release
