### ISSUE TITLE
pwarning() should have an apply_style argument

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#815]
`perror()` and `pexcept()` both have an `apply_style` argument which defaults to `True`. If that argument is `True`, then the method applies an ansi style to the message before sending it to the output stream. `pwarning()`` always applies the style. It should have an `apply_style` argument like it's sister methods.

**Comment by kmvanbrunt** [comment]
`pwarning()` is a convenience wrapper around `perror()` for adding the warning style. Does it make sense to add the `apply_style` argument? If a user wants to print to stderr with no style, they can just call `perror()` with `apply_style` set to False.

**Comment by tleonhardt** [comment]
I can see the advantage of adding the `apply_style` argument to `pwarning()` for consistency and in case the developer is programmatically setting `apply_style` to these calls.  So overall I think it might be a good idea.  I do see the point of view that it is just a convenience wrapper.  However it is a convenience wrapper with contextual meaning based on color of the output which is distinct from the default style/color of `perror`.

Regardless I don't feel particularly strongly one way or the other.

**Comment by kmvanbrunt** [comment]
I can see a case where a user overrides `pwarning()` to prepend "WARNING" or something. In that case they may want an apply_style.
