### ISSUE TITLE
Documenting Attributes

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#821]
As I work on writing documentation, I have come across the following situation:

1. We have many attributes, especially in `cmd2.Cmd`, which impact the behavior of the application, for the purposes of this example, let's use `broken_pipe_warning`.
2. These attributes should be treated as part of the public API that `cmd2` offers to developers.
3. We reference these attributes and their behavior when writing about features or in examples.
4. It's desirable to have these references link to our API documentation, which is generated from source code
5. You can put a docstring on the line after an attribute, and Sphinx will pick it up, but that only works if the attribute is defined on the class, outside of the `_init_` method. For example, Sphinx picks up the docstring for `NATURAL_SORT_KEY`, but not for `broken_pipe_warning`

To fix this issue, I propose the following and invite discussion, feedback, and alternative solutions:

1. All class attributes that are intended to be part of the "public interface" should be implemented as properties, using `@property` (and friends) decorators for the getter and setter methods.
2. The attribute/property is documented in the docstring of the getter method.

See the API documentation for `allow_ansi` for an example of how this works. I believe this proposal offers 2 benefits, with no downsides.

1. It forces us to clarify and document the public API of our module, especially the `cmd2.Cmd` class.
2. It makes it easy to generate and reference the API documentation for the attributes

Because Python properties and their getter/setter methods behave exactly as attributes, there will be no disruption to consumers of our library.

What do you think of this proposal?

**Comment by tleonhardt** [comment]
@kotfu So are you proposing adding a getter/setter for all instance attributes of `cmd2.Cmd` which we intend to make part of the public API?  That seems like overkill, but if it helps make the documentation easier and not against it.

**Comment by kmvanbrunt** [comment]
This seems like a maintenance burden. I understand the desire to simplify documentation, but requiring all public attributes to have a getter and setter is the kind of knowledge that becomes forgotten over time.

**Comment by kotfu** [comment]
@tleonhardt, yes, that's what I'm proposing.

You are both right, it may be overkill, and it is a maintenance burden. But is it worse than having a list of attributes in the documentation (which are disconnected from the source code) so people can understand what they are and what behaviors they drive? If we can't remember to do getters and setters for public attributes, how will we ever remember to update the documentation when we add new attributes or change the behavior of existing attributes?

I understand that we can just say that every attribute in `cmd2.Cmd` which doesn't start with an underscore is part of the public API. I would love to be able to produce documentation from the source code for those attributes. We can certainly decide not to produce such documentation, or decide it doesn't need to be produced from the source code, but in my mind both of those options are worse than adding the getters and setters.

**Comment by tleonhardt** [comment]
One way or another I see that we have a maintenance burden for adding attributes to `cmd2.Cmd` which we intend to be part of the public API.  In either case a developer needs to remember to do *something* special - be it add a getter/setter or update the documentation.

From my experience developers suck at updating documentation more than they suck at updating code.

So **if** @kotfu's proposal can be proven to eliminate the burden of a developer having to manually update the documentation as long as they remember to add a getter/setter when adding a new public attribute, then I am potentially in favor of accepting this maintenance burden.  @kotfu Since this will be somewhat of a burden, would it be possible for you to prototype this approach on a branch so that we can all take a look at what it looks like and what it gives us?

**Comment by kotfu** [comment]
In the `generating_output_docs` branch, I demonstrate several ways to document attributes in the source code such that they show up in the sphinx generated documentation. To view the documentation, check out the branch and then do `$ invoke clean.docs livehtml` and point your browser at [http://localhost:8000/api/cmd.html](http://localhost:8000/api/cmd.html). One note when using the `livehtml` and autodoc (i.e. `autoclass::` directive): autodoc requires Sphinx to import the code it is generating documentation from, and livehtml will only import that code once. So if you change your docstring and want to see if in the output, you have to bail out of the `livehtml` and regenerate the documentation.

Here are 4 ways to document attributes in `cmd2.Cmd`:

1. Create properties for all of the public attributes, and write a docstring on the getter. We had one of these already for `allow_ansi` because it required additional logic on the setter. I added a new property for the `broken_pipe_warning`. It's 6 lines of code for the property, instead of 1 line of code for the attribute plus whatever documentation you write on the getter. When done this way `docs/api/cmd.rst` picks up the documentation for this attribute when you use:
```
.. autoclass:: cmd2.cmd2.Cmd
    :members:
```

2. Create class attributes with the appropriate docstring. When we later create the instance attribute in `__init__()`, its value will be used instead of the class attribute. I did this for `debug`. This approach is also requires nothing in the documentation, all you need is:
```
.. autoclass:: cmd2.cmd2.Cmd
    :members:
```
We got rid of all our instance attributes in #548, and if we use this approach we have class attributes and instance attributes.

3. Document attributes in the documentation instead of the source code. I've showed how to do this with `help_error`. You don't make any changes to the source, and the documentation source file looks like:
```
.. autoclass:: cmd2.cmd2.Cmd
    :members:

    .. attribute:: help_error

      The error message displayed to the user when they request help for a
      command with no help defined.
```

4. Add docstrings to instance attributes. See `default_error` for an example. The Sphinx part is easy:
```
.. autoclass:: cmd2.cmd2.Cmd
    :members:
```

but Sphinx always displays the default value of "None", even though there is a value set when the instance attribute is defined.  There is a [four year old issue](https://github.com/sphinx-doc/sphinx/issues/904) for this, but it has never been fixed. I don't think we should use this approach because the documentation will always show the incorrect default value.

**Comment by kotfu** [comment]
Any thoughts on these approaches? I would like to move forward with option #1, getters and setters. I believe the formalization of our public API is worth the extra code (even if it does make our code look java-ish which makes me shudder a little bit).

**Comment by kotfu** [comment]
I don't like the class attributes method because it pollutes the namespace, and leaves the potential to create hard-to-track-down bugs: https://dzone.com/articles/python-class-attributes-vs-instance-attributes.

**Comment by kmvanbrunt** [comment]
I'd rather keep the code simple and manually document what we have to. For many of those public attributes, a code example would be more useful than a docstring anyway.

**Comment by tleonhardt** [comment]
If Sphinx didn't have that bug, I would prefer option **4** - that would be by far the easiest from a maintenance perspective.

I think approach **2** would be a bad idea for the reasons you mention above.

Approach **1** seems like it unnecessarily complicates the code by having to add a getter and setter for each public instance attribute.  This brings back bad memories of the early days of Java programming where there was a lot of B.S. boilerplate to get anything done.

Given that I guess I dislike **3** the least, but thats not to say that I like it.

This really seems like a technical problem which should be solvable by Sphinx and/or a Sphinx extension.

Is there anything in the Python language to support attribute annotations which could then be picked up by Sphinx?  Java has a lot of libraries/extensions that can make a lot of cool magic happen with annotations.  I'm thinking of something like a `@public` annotation which could be added to an instance attribute which would then automatically generate a getter and/or setter property - kind of analogous to how decorators take functions and do stuff - here I would want to take instance attributes and auto-create properties.  If we could do that, then it would dramatically reduce the maintenance burden of approach **1**.

**Comment by kotfu** [comment]
It's unlikely that instance attributes can be identified by static inspection: under the hood they just to `setattr` on the dictionary of the instance object. For now, I guess we'll just move forward with option 3: we'll write the documentation for attributes separately in the `docs/api/*` files, instead of trying to get sphinx to pull it from somewhere in the source code.
