### ISSUE TITLE
Undocumented breaking change in 0.9.12

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#830]
In 0.9.12 we removed the public `.keywords` attribute from `cmd2.Cmd`. This change broke the abbrev plugin, as described in https://github.com/python-cmd2/cmd2-abbrev/issues/2. I can fix the plugin. However, this breaking change was not documented in our CHANGELOG. Should we retroactively update the CHANGELOG? Should we do nothing?

**Comment by tleonhardt** [comment]
I’d say we should retroactively update the Changelog

**Comment by kmvanbrunt** [comment]
I updated the change log and release information for 0.9.12.
