### ISSUE TITLE
why cant input 'a'?

### ISSUE THREAD

**Issue by bestgopher** [python-cmd2/cmd2#845]
![image](https://user-images.githubusercontent.com/36840497/72304113-86ac4b00-36aa-11ea-9c66-caf1558607ac.png)

**Comment by bestgopher** [comment]
em....I overwrite the "completekey" args。。。。。。。。。。

**Comment by tleonhardt** [comment]
Hi @bestgopher,

Can you please elaborate?  What exactly is your question and/or what is the problem you are encountering?  What are you doing beforehand to get things in that state?

From the screenshot above it looks like you are just hitting `<TAB><TAB>` at the command prompt.
