### ISSUE TITLE
how to change this tag?

### ISSUE THREAD

**Issue by bestgopher** [python-cmd2/cmd2#846]
![image](https://user-images.githubusercontent.com/36840497/72399168-4919f180-3780-11ea-8b91-7062a29ac066.png)

**Comment by tleonhardt** [comment]
Hi @bestgopher,

You simply set `self.prompt`.  See the [pirate.py](https://github.com/python-cmd2/cmd2/blob/master/examples/pirate.py) for a simple static example or the [python_scripting.py](https://github.com/python-cmd2/cmd2/blob/master/examples/python_scripting.py) example for a more complex dynamic one.  Also, refer to the cmd2 documentation on [Initialization](https://cmd2.readthedocs.io/en/latest/features/initialization.html)

**Comment by tleonhardt** [comment]
For really fancy capabilities for updating it asynchronously even while the user is typing, see the [async_printing.py](https://github.com/python-cmd2/cmd2/blob/master/examples/async_printing.py) example

**Comment by bestgopher** [comment]
thanks your help。
