### ISSUE TITLE
Simple Dynamic Autocomplete

### ISSUE THREAD

**Issue by luzik** [python-cmd2/cmd2#863]
example/tab_autocomp_dynamic.py disapear from git for some reason.

Could you please add simple example of dynamic autocomplete ? 
I just need to filter choice of second argument based on the first one

```

class STGP_Cmd(cmd2.Cmd):
  def __init__(self, *args, **kwargs):
    self.a = {'a': ['ab', 'ac', 'ad'], 'b': ['bb', 'bc', 'bd']}

  def get_groups(self):
    return self.a.keys()

  def get_params(self, group):
    return self.a[group]

  get_param_parser = argparse.ArgumentParser()
  get_param_parser.add_argument('group', choices_method=get_groups)
  get_param_parser.add_argument('param', choices_method=get_params)

  @cmd2.with_argparser(get_param_parser)
    def do_get_param(self, args):
      self.poutput(self.get_param(args.param, args.group))

```

**Comment by tleonhardt** [comment]
@kmvanbrunt Is the expert when it comes to all things tab completion.  Perhaps he can weigh in on this.

I think a simple example demonstrating dynamic autocompletion would be useful.  Though I believe if you look closely you might find such an example within cmd2 itself (but we should not expect all developers to dive through our source code).

**Comment by kmvanbrunt** [comment]
@luzik Right now, our argparse tab completion documentation really only exists in the header of [argparse_custom.py](https://github.com/python-cmd2/cmd2/blob/master/cmd2/argparse_custom.py). I will be adding it to the official documentation soon.

Within that header, you will find the following text which addresses your situation. 

> There are times when what's being tab completed is determined by a previous argument on the command line. In these cases, `Autocompleter` can pass a dictionary that maps the command line tokens up through the one being completed to their argparse argument name. To receive this dictionary, your choices/completer function should have an argument called arg_tokens.
> 
> Example:
> ```Python
> def my_choices_method(self, arg_tokens)
> def my_completer_method(self, text, line, begidx, endidx, arg_tokens)
> ```
> 
> All values of the arg_tokens dictionary are lists, even if a particular argument expects only 1 token. Since `AutoCompleter` is for tab completion, it does not convert the tokens to their actual argument types or validate their values. All tokens are stored in the dictionary as the raw strings provided on the command line. It is up to the developer to determine if the user entered the correct argument type (e.g. int) and validate their values.

So for your case, this function should do what you need.

```Python
def get_params(self, arg_tokens):
    group = arg_tokens['group'][0]
    if not group:
        return []
    return self.a[group]
```

**Comment by kmvanbrunt** [comment]
@luzik I updated my original answer so it would handle a tab completion error when a user types an invalid group. It uses another **cmd2** class called `CompletionError`. Let me know if this helps.

**Comment by luzik** [comment]
@kmvanbrunt your example is working like a charm. Didn't know it will be such simple one.
