### ISSUE TITLE
API Documentation Approach

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#880]
I've been working on the API documentation. We have lots of constants, functions, and classes which we use internally and which are not really intended to be part of the public API. For example, in `constants.py` the `COMMAND_FUNC_PREFIX` constant is only for internal use.

Somewhere/somehow we need to indicate whether this item is part of the public API. We could:

1. Go through a renaming exercise and rename everything that isn't public to start with an underscore.
2. Declare that the documentation, not the source code, is the authoritative declaration of the public api.
2a. Don't use the `:members:` Sphinx directive; it will include everything that doesn't start with an underscore. Instead, individually add methods, functions, and constants that are part of the public API to the documentation. This is how `decorators.py` is built now. It's OK when there are only a handful of items, but it would be quite unwieldy for `cmd2.Cmd`, which has nearly a hundred methods.
2b. I haven't experimented with this, but we could use something like https://public.readthedocs.io/en/latest/README.html, a decorator which magically populates `__all__`, and which it appears that the Sphinx `:members:` directive honors.
2c. Wait for Sphinx 3.0 to be released, which includes a `:meta private:` info field. By adding this to the docstring of a method, you can tell Sphinx that it's private and it will be excluded from `:members:`.

The nice thing about 1 is that it's abundantly clear from the source code what's public and what isn't. This makes it more visible when modifying or enhancing so a developer can be more thoughtful about breaking changes. The downside to renaming everything is that the potential for breaking downstream consumers is high.

If we choose the documentation to be the definition of the public API, then we have to manually include or exclude items when creating and maintaining the documentation.

If there is single function in a module that we don't want to be public, and which doesn't begin with an underscore, we can't use the sphinx `:members:` directive to generate the documentation, we will have to list all the functions out one by one. For example, I could argue that the `cmd_func()` method in the `cmd2.Cmd` class should not be part of the public API. If we decided that it shouldn't be, then when building and maintaining the documentation for the `cmd2.Cmd` class you have to manually create a list of the approx 100 other methods in that class instead of just putting `:members:`

This seems like a bit of work, but doable. To reduce that work we could experiment with some sort of `@public` decorator, or wait for Sphinx 3.0 (who know how long that will be) and exclude things using the private info field in the docstrings.

Any preferences on what to do here?

**Comment by tleonhardt** [comment]
I think either 1 or 2c sounds good.

I did some research and Sphinx 3 is planned to be released around April 1, 2020.  I would be OK adding the meta private tag before Sphinx 3 is released in preparation for it.

I am also fine going the underscore route.

**Comment by kotfu** [comment]
After doing some more work documenting the API (api_docs branch), I'm not sure a renaming party is the right thing to do. Class names that start with an underscore are ugly. So I think we should do the "if it's not in the documentation it isn't part of the public interface" route for 1.0. We can let things settle for some period, make sure we have our public api nailed down in the documentation, and then if we choose to rename a _lot_ of our private variables, methods, and classes, we could do so as part of a future 2.0 release.
