### ISSUE TITLE
Tab completions after pipe | is still active on disabled redirection

### ISSUE THREAD

**Issue by luzik** [python-cmd2/cmd2#885]
With
self.allow_redirection = False

I can list system commands using any_command | <TAB>

My goal is to lock user in CLI without any way to run system command or access system files and with that in mind default cmd2 is quite "open"

**Comment by kmvanbrunt** [comment]
See #746 and #747.
Even though it's tab completing, redirection does not occur when you hit enter.

**Comment by kmvanbrunt** [comment]
If your goal is to prevent any introspection into the file system, then cmd2 in its current state makes that more complicated.

The following give access to the file system via tab completion with `path_complete`:

- edit
- history
- run_script
- run_pyscript
- alias create
- macro create
- shell
- all macros
- redirection and pipes

The following run arbitrary executables:

- shell
- edit
- piping

The question is whether cmd2 needs to make it easy for a developer to lock users out of the system. If so, then we need a better flag than `allow_redirection`. It should be respected by `path_complete` and `do_shell` and any command that writes to a user defined path (e.g. history, run_script)

In reality, with out any of these other changes, setting `allow_redirection` to False offers little security.

**Comment by kmvanbrunt** [comment]
@tleonhardt @kotfu Please provide your feedback. This would be another breaking change.

**Comment by tleonhardt** [comment]
@kmvanbrunt I don't necessarily see this as a breaking change.  If we add an attribute which can prevent any introspection or interaction with the file system, as long as it defaults to the current behavior then it won't be a breaking change.

But it does sound like a major feature addition.  So my gut feeling is that we should wait until after the 1.0 release.  Then we can revisit adding this for the 1.1 or 1.2 release.

I do like the concept of giving `cmd2` developers the option to lock down their applications.  However, if I put on my devil's advocate hat for a second, perhaps this can already be achieved with normal operating system and filesystem permissions? `cmd2` applications effectively act normally like any other shell.

**Comment by kmvanbrunt** [comment]
@tleonhardt That's my view as well. There are so many corner cases we'd have to code around to provide security, and we may not get them all. A user could even run a pyscript with a `popen()` call.

Having the `allow_redirection` flag is helpful because it's not something a developer could turn off easily otherwise. But all other cases need to be handled in an application-specific way (e.g delete commands, remove variables like edit from settables).

I do wonder if we want two flags though. `allow_redirection` and `allow_piping`. I could see a case where a user just wants to disable piping.

**Comment by luzik** [comment]
Thanks for your considerations. My exact use case is to provide ssh cli for embedded device (Like Cisco IOS). I can't allow user to access OS because of many reasons - including warranty related issues.
I do not need any macros, aliases, scripts, edits, sets. But I do like pipe functionality, especially for grep purposes :). Unfortunately cmd2 pipe do not allow pipe to self command nor it provide self grep, wc, etc...
I do like an idea of running cmd2 shell in sandboxed environment (for example unix chroot) - but on first look it is not a trivial task.
Thank you for complete list of "unsafe" commands. I disabled them all already.
A dedicated flag or many small ones (that leads to the same goal) would be great!

**Comment by kmvanbrunt** [comment]
I think I have a solution to this. If redirection is disabled and someone tries to tab complete after a > or |, then I will raise a CompletionError exception and let the user know redirection is disabled.

**Comment by tleonhardt** [comment]
If I'm developing a `cmd2` app for end users that are not super technical and I disable redirection, I'd rather attempted tab completion simply do nothing instead of spit an error message which might confuse the end user.
