### ISSUE TITLE
Re-evaluate visibility of EmptyStatement exception

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#889]
In `cmd2.py` we define an `EmptyStatement` exception. In `__init__.py` we import that exception, making it available as `cmd2.EmptyStatement`. As far as I can tell, we only use this exception for internal purposes: no methods available as part of our public API throw this exception.

If this is true, then it seem like:

1. We shouldn't document `EmptyStatement` as part of our public API, and
2. We should remove the package level import of `EmptyStatement` from `__init__.py`.

What do you think?

**Comment by kmvanbrunt** [comment]
I don't actually know why it's imported in `__init__.py`. I'm OK with your suggestions unless @tleonhardt has additional insight.

**Comment by tleonhardt** [comment]
I cant' think of any good reason why it should be imported in `__init__.py`.  I think the suggestion here is a good one.
