### ISSUE TITLE
history command does not show persistent history (persistent_history_file)

### ISSUE THREAD

**Issue by grolinet** [python-cmd2/cmd2#891]
When using `persistent_history_file` as seen in example `https://github.com/python-cmd2/cmd2/blob/master/examples/hooks.py`, after exiting and restarting the script, i would expect the `history` command to show the history of the previous session. However only the commands of the current session are displayed. 
The saved history works fine when using "up-arrow" or searching with "ctrl+r". 
Is this behaviour intended? 

Steps to reproduce: 
- Start script
- Execute some commands
- Exit script
- Restart script
- type `history` + enter

Expected behaviour:
Commands of the previous session are displayed

Observed behaviour:
Commands of previous session are not displayed

**Comment by tleonhardt** [comment]
@grolinet The behavior you report is both intentional and documented.

The history command has a -a / —all flag for showing the complete history including history persisted from previous sessions.

If you have any suggestions for how we can make this behavior more clear for users please let us know.

**Comment by grolinet** [comment]
My bad, i didn't see that. I just expected it to work like in other shells, such as bash. 
Yes, it is well documented, and it would probably be bad to change the default behaviour now.

**Comment by tleonhardt** [comment]
@grolinet No problem.  Thanks for reporting the issue anyways.  We would much rather end users report possible bugs than not, because if they are bugs we want to fix them!  I'm going to close this issue.  But let us know if you run into any other problems.  Good luck with your `cmd2` development.
