### ISSUE TITLE
Should we implement hook methods from `cmd.Cmd` so we can document them?

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#896]
We are not consistent in defining and documenting methods from `cmd.Cmd` which we use/rely-on, but which perform the same function as they do in our superclass. For example, `cmd2.Cmd` provides an implementation of the `precmd()` method from our superclass, which does exactly the same thing as the superclass method. We do not implement `postcmd()` or `preloop()` or `postloop()`, which are no-ops in the superclass, i.e. they are stub methods waiting to be over-ridden.

Providing an implementation of these methods allows us to reference them in our documentation, which is nice.

I don't care whether we do or don't provide an implementation for these methods, but whichever we choose, we ought to do it the same for all four of these hook-type methods.

Any preference?

**Comment by tleonhardt** [comment]
I’m in favor of providing an override of all cmd.Cmd hook methods within cmd2.Cmd for the following reasons:
- It makes them more discoverable to anyone browsing the cmd2 code
- We can provide a better doctring which can help developers properly understand correct usage
- As you mentioned, it makes it easier for us to document them in our Sphinx docs
