### ISSUE TITLE
Fix for issue #8

### ISSUE THREAD

**Issue by FedericoCeratto** [python-cmd2/cmd2#9]
Originally reported by: **Giorgio Kaka (Bitbucket: [gosom](http://bitbucket.org/gosom), GitHub: [gosom](http://github.com/gosom))**

---

I figured out what was happening.
check the patch file for a fix.

Thanks for the nice module

---
- Bitbucket: https://bitbucket.org/catherinedevlin/cmd2/issue/9

**Comment by tleonhardt** [comment]
@gosom Thanks for the suggested fix.  A modified variant of what you suggested has been applied and works great.
