### ISSUE TITLE
Postcommand Hooks and argparse

### ISSUE THREAD

**Issue by grolinet** [python-cmd2/cmd2#905]
Hi

I am using argparse for autocompletion and with sub-commands. 
I always annotate my command methods with `@with_argparser(parser)` which i think is the right way to use the argparser with cmd2. 
I did experiment with postcommand hooks using the `register_postcmd_hook` method. 
The documentation states, that the registered postcommand is only executed when the command method was called (in case of a raised exception the postcommand it is not executed). 

Now, if argparse can't parse the submitted args (for example when there are too few), the command method is not executed, but the postcommand hooks will be executed anyway. 

I understand, that in this context, the `@with_argparser(parser)` belongs to the method and thus one could argument, the method was called and didn't raise an exception, but on the other side, in most cases (i think), it makes not a lot of sense to execute postcommands if argparse can't parse the arguments of the command method. 
Is this behaviour intended? And if yes, is there a possibility to change it? I know i could ditch the annotations, use the argparser inside the command method and raise an exception if argparse fails, but this seems to be a lot of overhead (and i would lose the autocomplete stuff).

Could i possibly "monkey patch" the `with_argparser` method so a exception will be raised? (Also not a very elegant solution i think)

Thanks for any help.

**Comment by grolinet** [comment]
I just did a test with overwriting the `with_argparser` decorator:
I replaced this code in `cmd2/decorators.py` (beginning on line 216)
```
            try:
                args = parser.parse_args(parsed_arglist, namespace)
            except SystemExit:
                return
            else:
                setattr(args, '__statement__', statement)
                return func(cmd2_app, args)
```
Whit this code:
```
            args = parser.parse_args(parsed_arglist, namespace)
            setattr(args, '__statement__', statement)
            return func(cmd2_app, args)
```
Essentially i just removed the try/catch/else so that argparse will raise the SystemExit exception when parsing fails.
When i use this patched version, the postcommand is only executed when argparse succeeds. The behaviour (error message that gets printed) if argparse raises the SystemExit  is exactly the same. 
This could of course have some other side-effects which i could miss, but until now, i didn't see any.

**Comment by kmvanbrunt** [comment]
@grolinet I believe you're correct that we should be raising an exception in this case.

**Comment by tleonhardt** [comment]
I don't believe that it is intentional for `cmd2` to call post-command hooks when there is an `argparse` parsing error.  I suspect that was simply an oversight on our part.

I think we should fix this, but make sure we do it in a way that doesn't print a stack trace or encourage users to set debug to `True` to see such a stack trace.
