### ISSUE TITLE
command scripts cannot be interrupted

### ISSUE THREAD

**Issue by JimRowan** [python-cmd2/cmd2#909]
It seems that even with quit_on_sigint set to True, ^C doesn't interrupt a command script.  Am I missing something?

**Comment by kmvanbrunt** [comment]
@JimRowan 
`quit_on_sigint` only applies when someone presses Ctrl-C at the prompt. I'll update the documentation to clarify this.

However, you are correct about this script issue. We should be stopping a running command script if Ctrl-C is pressed. I'll get a fix pushed up soon.
