### ISSUE TITLE
test_which_editor_good (obviously) fails on systems without vi installed

### ISSUE THREAD

**Issue by mgorny** [python-cmd2/cmd2#926]
See also: https://bugs.gentoo.org/710174#c1

Long story short, it is very wrong to assume that `vi` will exist. Firstly, because there are Linux distributions where vi is not even part of default package set. Gentoo, for example, requires 'some' editor to exist, and defaults to nano. Secondly, because it is entirely valid to have vim installed without 'vi' symlink.

If you want to rely on some specific tool being available, I would suggest using something from base POSIX set.

**Comment by tleonhardt** [comment]
@mgorny Thanks for reporting this.  That is a a poorly written test on our part.  We will fix it shortly.
