### ISSUE TITLE
async_alert and long running scripts

### ISSUE THREAD

**Issue by astrand** [python-cmd2/cmd2#935]
I'd like to create an application where status information ("Current time is 2020-04-20 21:44") is continuously updated, even though a script is active. In particular, I'd like to create a Python script which sleeps, ie something like:

cmd1
time.sleep(2)
cmd2
...

However, it seems like when the script is running, async_alert is not called. Is it possible to, for example, run the script in a separate thread, or use some kind of select based solution? I need support for both Linux and Windows, though.

**Comment by tleonhardt** [comment]
@astrand Can you provide a scaled-down simple code example of what you are trying to that isn't working?  

Ultimately any long-running thing providing asynchronous alerts needs to be in another thread.  If you haven't already, please see the [async_printing.py](https://github.com/python-cmd2/cmd2/blob/master/examples/async_printing.py) example

**Comment by astrand** [comment]
I'm trying async_printing.py:

`(APR)> run_pyscript myscript.py`

myscript.py looks like:

```
import time
time.sleep(200)
```
When myscript.py starts, the applications appears blocked, and alerts are no longer printed. 

I'm also open for and interested in non-Python scripts, but the problem seems to be the same. I tweaked async_printing.py and added a function:

```
def do_sleep(self, _):
    time.sleep(200)
```
The problem is the same, though, as long as "sleep" is called, everything is blocked. I guess I can manually create a new thread in this function - is that how it should be done? Or should I rather look at using an external event loop?

**Comment by kmvanbrunt** [comment]
@astrand `async_alert()` is for alerting while at the prompt.

When you're in a `do_*` function, there is no prompt. Therefore the `_alerter_thread_func()` in the [async_printing.py](https://github.com/python-cmd2/cmd2/blob/master/examples/async_printing.py) example isn't going to print anything. Please read through the example to understand `async_alert()'s` purpose and how best to use it.

**Comment by tleonhardt** [comment]
As I think the question has been answered, I am going to close this issue.  If I am mistaken, please feel free to re-open.
