### ISSUE TITLE
Testsuite failure because of editor preferences

### ISSUE THREAD

**Issue by DerDakon** [python-cmd2/cmd2#936]
As I have [reported in Gentoo bugzilla](https://bugs.gentoo.org/710174#c1) the test_which_editor_good failed for me.

I hate vi. With passion ;) That's why I don't have it installed on my systems as I don't use it anyway. Seriously speaking: testing for things like "true" or "false" or maybe just "ls" seems a more safe option to find something that should be universally available.

**Comment by kmvanbrunt** [comment]
Sorry you had trouble with the unit tests. This issue was actually fixed a few days ago in PR #927.
It should be in our next release.

**Comment by DerDakon** [comment]
Ha, he even reported my bug upstream. Nice one.
