### ISSUE TITLE
Consider an appropriate time to drop support for Python 3.5

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#938]
The recent [Python Developers Survey 2019 Results](https://www.jetbrains.com/lp/python-developers-survey-2019/) show that only 4% of Python 3 users are still using Python 3.5

Python 3.5 is scheduled to be end-of-life in [September 2020](https://devguide.python.org/#status-of-python-branches).  Major projects like [Django](https://code.djangoproject.com/ticket/30116) have already dropped support for Python 3.5 for new versions.  We should plan for when we want `cmd2` to stop supporting Python 3.5 

By moving to support 3.6+ we open up the ability to use things like [f-strings](https://realpython.com/python-f-strings/), [syntax for variable annotations](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep526), and [pathlib](https://docs.python.org/3/library/pathlib.html).

**Comment by kmvanbrunt** [comment]
I'm OK removing support but we should give sufficient advanced warning. I know Debian 9 has Python 3.5 as it's default, so **cmd2** developers on that system will need to upgrade Python for new **cmd2** features.

**Comment by tleonhardt** [comment]
I recommend that before we put out the **1.1** release, lets update the README to remove the old warning about dropping support for Python 2.7 and add a new warning about dropping support for Python 3.5, say perhaps August 31, 2020.

**Comment by kotfu** [comment]
Sounds good to me. What will the version number of `cmd2` be for the first release we drop python 3.5 support? 2.0?

**Comment by tleonhardt** [comment]
Good question about version after we drop support for Python 3.5 .... Yeah I guess **2.0** might be the right answer in that case.

**Comment by kotfu** [comment]
I'm not certain that 2.0 is the right version number we should use. I was just thinking of how Requests didn't drop support for python 2.7 and 3.5 in their 2.x series. 3.x will only support python 3.6+. But they had lots of other changes in requests 3.x too.

**Comment by tleonhardt** [comment]
I'm not certain of the right answer either.  I think **1.2** or **1.3** or whatnot could be fine as well.

**Comment by anselor** [comment]
Things to do when we cut 3.5 support:

- travis.yml, noxfile.py - remove the special 3.5.x test handling. Remove conditional checks related to 3.5.x
- utils.py - restore type annotations for `get_defining_class`
- setup.py - Remove conditional module dependencies for 3.5.x
- table_creator.py - Remove fallback redeclaration of typing.Deque needed for versions earlier than 3.5.4.
- cmd2.py, many others - Every instance of `self.var_name = [something]  #type: type-declaration` can be replaced with `self.var_name: type-declaration = [something]`

**Comment by tleonhardt** [comment]
I already removed Python 3.5 testing already in PR #1051 - it was failing in GitHub Actions for reasons related it to being significantly past its EOL.  

So I think we should drop 3.5 support ASAP.  I'm happy if we do that as in a 1.5 release or if we put out 2.0 soon.  But we shouldn't delay since we will no longer have continuous integration testing for Python 3.5 (any version).

**Comment by tleonhardt** [comment]
Since the 2.0 branch has been merged into the main branch, we should be able to drop support for 3.5 any time now.
