### ISSUE TITLE
Bug in Cmd2HelpFormatter and ArgparseCompleter when metavar is a tuple

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#974]
The [Cmd2HelpFormatter](https://github.com/python-cmd2/cmd2/blob/master/cmd2/argparse_custom.py#L600-L716) class has a bug which causes a crash in the following circumstances:
- `nargs` is an int and > 1
- [metavar](https://docs.python.org/3/library/argparse.html#metavar) is a tuple

Tested with `cmd2` 1.2.0 but verified the bug exists in the current version as well.

In my case, the crash occurs on line 780 in the current code with the [_format_args](https://github.com/python-cmd2/cmd2/blob/master/cmd2/argparse_custom.py#L763-L784) method.

**Comment by kmvanbrunt** [comment]
@tleonhardt This bug also affects the `ZERO_OR_MORE` and `ONE_OR_MORE` cases when `metavar` is a tuple.

**Comment by tleonhardt** [comment]
Specifying `metavar` as a tuple only really seems to make sense if `nargs` is an integer greater than 1.  

But perhaps the simplest solution is to remove our custom help formatting for this except when nargs is a range?

**Comment by kmvanbrunt** [comment]
A `metavar` tuple also crashes `ArgparseCompleter` when creating a `CompletionItem` table. I will fix this in the same PR.
