### ISSUE TITLE
Enhance read_input()

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#982]
Add following feature to `cmd2.Cmd.read_input()`.

1. Ability to tab complete custom values
    * Support passing in list of choices
    * Support passing in argparse.ArgumentParser which tab completes similar to our commands
    * Preserve support for doing command tab completion since this is called by `cmd2.Cmd._read_command_line()`.
    * Default will be no tab completion

2. Support passing in custom up-arrow history

We need to hammer out an interface to `read_input()`. This will be a 2.0 feature since its signature will change.

**Comment by tleonhardt** [comment]
@kmvanbrunt Can you explain the overall motivation for this feature?  Understanding that will help inform my thoughts on your proposal.

**Comment by kmvanbrunt** [comment]
@tleonhardt `read_input()` is cmd2's version of the`input()` function. This enhancement will given developers the ability to prompt a user for input and provide tab completion from a known set of values. The history aspect will allow the user to up arrow through previous entries and perform history searches (e.g. Ctrl-R).

**Comment by tleonhardt** [comment]
Ok, I get it now.  That is one super-powered function for reading input - it seems to handle every conceivable thing people might want.  But it does so in a way where all the advanced functionality is optional so the basic use case is simple.  I like it.

**Comment by anselor** [comment]
This looks like a great feature that will make #944 a ton easier to implement. I like it.

**Comment by kmvanbrunt** [comment]
Finished in #991
